### ISSUE TITLE
Refactor into smaller, combinable units

### ISSUE THREAD

**Issue by benjamin-bader** [jupp0r/prometheus-cpp#101]
I'm interested in using portions of this library, specifically the various metrics implementations.  I do not wish to take dependencies on protobuf or civet.  I think there's a lot of value in having Counter, Histogram, etc available independently of transport concerns.

It seems reasonable that we might refactor the library into separate components, that would still be combined into one binary but which could also be incorporated individually - for example, in pseudo-cmake:

```cmake
add_library(metrics, ${METRICS_SRCS})
add_library(metrics_protobuf ${PROMETHEUS_PROTO_SRCS})
add_library(civet_exposer, ${EXPOSER_SRCS})
add_library(prometheus-cpp
  $<TARGET_OBJECTS:metrics>
  $<TARGET_OBJECTS:metrics_protobuf>
  $<TARGET_OBJECTS:civet_exposer>
)

# etc
```

I haven't looked too deeply into the feasibility, but (as one unfamiliar with the code) it doesn't seem too far-fetched.  Is there any interest in supporting this kind of refactor?

**Comment by jupp0r** [comment]
Metrics currently all implement `Collectable`, which depends on protobuf representations of prometheus' metrics. With protobuf content-type support gone in prometheus 2.0, we could move away from using protobuf as a dependency alltogether. I'd definitely support that change.

Once this refactoring would be complete, splitting metrics out of the library would be easy.

**Comment by gjasny** [comment]
I'll try getting rid of the protobuf dependency.

**Comment by gjasny** [comment]
PR #105 should get rid of protobuf.

**Comment by gjasny** [comment]
Please give #127 a try.

**Comment by gjasny** [comment]
Hope current master is providing what you need.
