### ISSUE TITLE
maybe-uninitialized warning with optimized Bazel build

### ISSUE THREAD

**Issue by drigz** [jupp0r/prometheus-cpp#102]
Steps to reproduce (on Debian Buster-like system with GCC 7.3.0):

```
git clone https://github.com/jupp0r/prometheus-cpp
cd prometheus-cpp
bazel build -c opt //...
```

This produces the warning:

```
INFO: From Compiling lib/summary.cc:
In file included from lib/summary.cc:1:0:
bazel-out/k8-opt/bin/_virtual_includes/prometheus_cpp/prometheus/summary.h: In constructor 'prometheus::detail::TimeWindowQuantiles::TimeWindowQuantiles(const std::vector<prometheus::detail::CKMSQuantiles::Quantile>&, std::chrono::_V2::steady_clock::duration, int)':
bazel-out/k8-opt/bin/_virtual_includes/prometheus_cpp/prometheus/summary.h:17:7: warning: '<anonymous>.prometheus::detail::CKMSQuantiles::buffer_' may be used uninitialized in this function [-Wmaybe-uninitialized]
 class CKMSQuantiles {
       ^~~~~~~~~~~~~
```

The warning seems to only occur without `-fPIC`. The default `fastbuild` configuration always builds with `-fPIC`, but adding `-c opt` causes each object to be built twice, with and without `-fPIC`, resulting in this warning. I searched briefly but didn't find anywhere discussing an interaction between `-fPIC` and `-Wmaybe-uninitialized`.

Do you think the warning is meaningful? If not, should we suppress it by adding `"-Wno-maybe-uninitialized"` to `copts`?

**Comment by jupp0r** [comment]
I think it's a valid warning, we should value-initialize (as opposed to default-initialize) the buffer array in the `CKMSQuantiles` constructor.

**Comment by jupp0r** [comment]
@drigz : can you verify the warning is gone? Thanks for going the extra mile to report this in any case!
