### ISSUE TITLE
Add interface documentation

### ISSUE THREAD

**Issue by jupp0r** [jupp0r/prometheus-cpp#11]
All public interfaces need to be documented, especially regarding to memory management contracts and thread safety.

**Comment by 0mp** [comment]
Any suggestions on how/where we may want to document it?

**Comment by jupp0r** [comment]
A good start would be in the headers.

**Comment by gjasny** [comment]
We now have https://jupp0r.github.io/prometheus-cpp/ which is generated from the master branch.
