### ISSUE TITLE
I can't build the project in my windows gitbash

### ISSUE THREAD

**Issue by willl0320** [jupp0r/prometheus-cpp#115]
I can't build the project in my windows gitbash. Could you help to offer some advice, appreciate for your great support.
errors,

$ cmake ..
-- Building for: Visual Studio 11 2012
-- The C compiler identification is MSVC 17.0.50727.1
-- The CXX compiler identification is MSVC 17.0.50727.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find GoogleBenchmark (missing: GoogleBenchmark_LIBRARY GoogleBenchmark_INCLUDE_DIR)
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/18.8/prometheus-cpp-master/_build/CMakeFiles/CMakeOutput.log".
See also "D:/18.8/prometheus-cpp-master/_build/CMakeFiles/CMakeError.log".

**Comment by gjasny** [comment]
You need zlib (required) and google benchmark (optional).

**Comment by gjasny** [comment]
Could you please try to remove the `REQUIRED` keyword from `find_package(ZLIB)` and see if it works? Bazel does not add it, so I wonder if it's a left-over.

**Comment by gjasny** [comment]
zlib dependency is being removed: #116

**Comment by gjasny** [comment]
Please reopen if the error persists.
