### ISSUE TITLE
Link CivetWeb dynamically or hide its symbols

### ISSUE THREAD

**Issue by tudor** [jupp0r/prometheus-cpp#117]
The Prometheus C++ client library builds CivetWeb internally, but then exposes all symbols from CivetWeb:

```
# objdump -TC /usr/local/lib/libprometheus-cpp.so  | egrep -i '(civet|mg_)' | wc -l
118
# objdump -TC /usr/local/lib/libprometheus-cpp.so  | egrep -i '(civet|mg_)' | head
0000000000048290 g    DF .text  0000000000000021  Base        CivetServer::removeWebSocketHandler(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000056250 g    DF .text  0000000000000208  Base        mg_set_request_handler
0000000000048040 g    DF .text  0000000000000002  Base        CivetWebSocketHandler::handleReadyState(CivetServer*, mg_connection*)
0000000000052f20 g    DF .text  000000000000001a  Base        mg_lock_connection
0000000000049810 g    DF .text  00000000000002c6  Base        CivetServer::CivetServer(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, CivetCallbacks const*)
0000000000056700 g    DF .text  0000000000000208  Base        mg_set_auth_handler
000000000004bf40 g    DF .text  000000000000005e  Base        mg_get_ports
00000000000482c0 g    DF .text  0000000000000010  Base        CivetServer::removeAuthHandler(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000048040 g    DF .text  0000000000000002  Base        CivetWebSocketHandler::handleClose(CivetServer*, mg_connection const*)
000000000004be00 g    DF .text  0000000000000047  Base        mg_strcasecmp
```

This means that an application linked with the Prometheus C++ client library can't use CivetWeb for its own purposes: I can't use the CivetWeb from the Prometheus library (because the header files are not installed) and I can't use another copy unless I can be absolutely sure that I have the exact version that Prometheus uses (or else I'd violate the One Definition Rule).

**Comment by jupp0r** [comment]
What would be preventing you from using the same version?

**Comment by gjasny** [comment]
@tudor Are you using the CMake or bazel to build those?

**Comment by gjasny** [comment]
Hi @tudor could you please give #122 a try?

**Comment by tudor** [comment]
We decided to go another way; we have counters and gauges and histograms represented internally in another way, so exporting them into Prometheus required using a custom `Collectable`, so it was relatively easy for us to serialize directly to the text format (I wrote prometheus-cpp's current `text_serializer.cc` so I'm somewhat familiar with the wire format :) )

But I built with #122 and verified that the CivetWeb symbols are indeed no longer visible in `libprometheus-cpp.so`, so I think this would work.
