### ISSUE TITLE
Hello! Does it work well in project in which files suffix with ".cpp"？

### ISSUE THREAD

**Issue by shiqikai** [jupp0r/prometheus-cpp#128]
Can it make successful?
freshman, sorry.
(In our server , it can not connect the internet, so I can only use the CMake?)

**Comment by gjasny** [comment]
Hello,

It should not make any difference that `prometheus-cpp` uses `.cc` suffixes and your project uses `.cpp`. Both are usually recognized as being C++.

If you cannot download source code on your build machine from the internet, just mirror those unaccessible repositories within your infrastructure and use a [insteadOf](https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf) rewrite.

Hope this helps!
-Gregor

**Comment by shiqikai** [comment]
Thank you for your reply.
I will try.
{Creator of the "Only C++ library of prometheus"}
哈哈
