### ISSUE TITLE
Can we set label value dynamically ?

### ISSUE THREAD

**Issue by baiwfg2** [jupp0r/prometheus-cpp#129]
Hi, jupp0r. I know we can use this to set static label,
```
auto& second_counter = counter_family.Add(
      {{"another_label", "value"}, {"yet_another_label", "value"}});
```
what about dynamic labels, for example, I want to set linux `errno` value as a label. How could I do that ?

**Comment by jupp0r** [comment]
Each set of label pairs adds a new time series. Prometheus' data model assumes that the number of time series is finite (can be very large (100s of millions on a single server, though). We tried to reflect this in the API for this library. If you wanted to reflect `errno` values, I'd look at the man page for the call you want to monitor, create a list of possible errno values and associate a counter with each one in your own code.

Makes sense?

**Comment by gjasny** [comment]
You'd do it like in the example:
https://github.com/jupp0r/prometheus-cpp/blob/77a5b0172833786ec014498d61a4dd87c500dc3b/pull/tests/integration/sample_server.cc#L68
