### ISSUE TITLE
Can you add this library to vcpkg?

### ISSUE THREAD

**Issue by IronsDu** [jupp0r/prometheus-cpp#130]
Thanks.

**Comment by jupp0r** [comment]
My understanding is that anyone could contribute to vcpkg. If you point it at a release source code archive, you should be able to open a PR with them.

**Comment by furiousbanana** [comment]
I need this library to be added to vcpkg as well. We are building cross platform tool that supposed to work on both Windows and Linux. So need all the dependent packages to have support for both.

**Comment by gjasny** [comment]
I started an initial port [here](https://github.com/gjasny/vcpkg/commits/add-prometheus-cpp) but I need civetweb added for pull library support. Also it needs testing on Windows.

**Comment by gjasny** [comment]
I submitted a pull request to vcpkg and await feedback

**Comment by gjasny** [comment]
It finally got merged.
