### ISSUE TITLE
(gcc4.8.5)When I make, "use of deleted function "happens, How to solve it?

### ISSUE THREAD

**Issue by shiqikai** [jupp0r/prometheus-cpp#131]
``/home/shiqikai/prometheus-cpp/push/src/gateway.cc: In member function ‘int prometheus::Gateway::push(prometheus::Gateway::PushMode)’:
/home/shiqikai/prometheus-cpp/push/src/gateway.cc:63:34: error: use of deleted function ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’
     auto uri = std::stringstream{};
                                  ^
In file included from /home/shiqikai/prometheus-cpp/push/include/prometheus/gateway.h:6:0,
                 from /home/shiqikai/prometheus-cpp/push/src/gateway.cc:2:
/usr/include/c++/4.8.2/sstream:502:11: note: ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8.2/sstream:38:0,
                 from /home/shiqikai/prometheus-cpp/push/include/prometheus/gateway.h:6,
                 from /home/shiqikai/prometheus-cpp/push/src/gateway.cc:2:
/usr/include/c++/4.8.2/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8.2/istream:795:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.8.2/istream:58:11: note: ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/istream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/sstream:38,
                 from /home/shiqikai/prometheus-cpp/push/include/prometheus/gateway.h:6,
                 from /home/shiqikai/prometheus-cpp/push/src/gateway.cc:2:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/ios:42:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/sstream:38,
                 from /home/shiqikai/prometheus-cpp/push/include/prometheus/gateway.h:6,
                 from /home/shiqikai/prometheus-cpp/push/src/gateway.cc:2:
/usr/include/c++/4.8.2/bits/ios_base.h:786:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);

**Comment by gjasny** [comment]
I have a fix and am working on it.

**Comment by pradeep-roy-guavus** [comment]
I can confirm the existence of this issue when building on CentOS 7.3.1611 (g++ 4.8.5, cmake 2.8.12.2). It got resolved by using the changes in the 63a5c61 commit. Thanks!
