### ISSUE TITLE
summary endpoint to existing web server

### ISSUE THREAD

**Issue by benitogf** [jupp0r/prometheus-cpp#134]
is there a way to add an endpoint handler that exports the summary?

**Comment by jupp0r** [comment]
Yes, you'll have to implement some glue logic. It'll basically work like the `Exposer` that prometheus-cpp comes with already and I'd encourage you to look at the code here: https://github.com/jupp0r/prometheus-cpp/tree/master/pull/src

The rough flow is as follows:

1. Your existing http server gets a request on a metrics endpoint (url). 
2. You get a copy of the current metrics state from a registry via the `Collect()` method
3. You use the [text serializer](https://github.com/jupp0r/prometheus-cpp/blob/master/core/src/text_serializer.cc) to render the metrics to prometheus' text format
4. You set a bunch of response headers for your response (see the exposer code or prometheus docs)
5. Send the response and cross fingers

Let me know how that goes.

**Comment by benitogf** [comment]
> Send the response and cross fingers
:smile: 

Thanks for your kind response, I did exactly that, using only `src/core` was enough to setup the endpoint. Here's the endpoint handler as a reference in case that someone else needs to do something similar:

```
#pragma once
#include "seasocks/PageHandler.h"
#include "prometheus/registry.h"
#include "prometheus/serializer.h"
#include "prometheus/text_serializer.h"

using std::shared_ptr;
using seasocks::PageHandler;
using seasocks::Response;
using seasocks::Request;
using prometheus::Registry;
using prometheus::Serializer;
using prometheus::TextSerializer;

class MetricsHandler: public PageHandler {
 private:
  shared_ptr<Registry> metrics;
 public:
  explicit MetricsHandler(shared_ptr<Registry> metrics_registry):
    metrics(metrics_registry) {}
  virtual std::shared_ptr<Response> handle(const Request& request) {
    auto serializer = std::unique_ptr<Serializer>{new TextSerializer()};
    if (request.verb() == Request::Verb::Get &&
        request.getRequestUri() == "/metrics") {
      return Response::textResponse(
        serializer->Serialize(metrics.get()->Collect()));
    }
    return Response::unhandled();
  }
};
```

**Comment by yaminisridaran** [comment]
I have a existing http server already running. I need to expose a metrics rest api and how to get the metrics to be sent to this metrics api.
Any pointers to some sample code for handling this situation.

**Comment by jupp0r** [comment]
@yaminisridaran see the example code and verbal explanation above.
