### ISSUE TITLE
Cannot build properly in ubuntu

### ISSUE THREAD

**Issue by lasanthaa** [jupp0r/prometheus-cpp#139]
I am trying to build the following source code.
`
```
#include <chrono>
#include <map>
#include <memory>
#include <string>
#include <thread>

#include <prometheus/exposer.h>
#include <prometheus/registry.h>

int main(int argc, char** argv) {
  using namespace prometheus;

  // create an http server running on port 8080
  Exposer exposer{"127.0.0.1:8080"};

  // create a metrics registry with component=main labels applied to all its
  // metrics
  auto registry = std::make_shared<Registry>();

  // add a new counter family to the registry (families combine values with the
  // same name, but distinct label dimenstions)
  auto& counter_family = BuildCounter()
                             .Name("time_running_seconds")
                             .Help("How many seconds is this server running?")
                             .Labels({{"label", "value"}})
                             .Register(*registry);

  // add a counter to the metric family
  auto& second_counter = counter_family.Add(
      {{"another_label", "value"}, {"yet_another_label", "value"}});

  // ask the exposer to scrape the registry on incoming scrapes
  exposer.RegisterCollectable(registry);

  for (;;) {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    // increment the counter by one (second)
    second_counter.Increment();
  }
  return 0;
}`
```
But this gives me undefined reference errors

I am using g++ 7.3 

Here is the command i used
g++ -o out -c main.cpp -I/usr/local/include 
g++ -out.exe out -L/usr/local/lib

**Comment by lasanthaa** [comment]
![screenshot from 2018-08-26 15-38-21](https://user-images.githubusercontent.com/12367805/44627127-1cc0c380-a946-11e8-93e7-0d3fc8e6cfa6.png)


![screenshot from 2018-08-26 15-40-17](https://user-images.githubusercontent.com/12367805/44627147-61e4f580-a946-11e8-9681-ce3b13538e0f.png)

**Comment by gjasny** [comment]
Hi, your `g++ -out.exe out -L/usr/local/lib` line lacks linking the prometheus-cpp library.

**Comment by lasanthaa** [comment]
I have copied libs (libprometheus-cpp-core.a , libprometheus-cpp-pull.a ,libprometheus-cpp-push.a) in deploy  folder to /usr/local/lib folder and include them when linking.
Is n`t is right?
Can you send me the command used to link it?

**Comment by gjasny** [comment]
You need to tell g++ to actually link those by adding something like: `-lprometheus-cpp-pull -lprometheus-cpp-pusg -lprometheus-cpp-core` to the link line.

I'd suggest that you use CMake instead of invoking the toolchain yourself.

**Comment by lasanthaa** [comment]
thank you. it worked!
