### ISSUE TITLE
Error during make of c++ application

### ISSUE THREAD

**Issue by aligher** [jupp0r/prometheus-cpp#140]
/home/tcsapp/nghttp2/prometheus-cpp/_build/deploy/usr/local/lib64/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::MetricsHandler::MetricsHandler(std::vector<std::weak_ptr<prometheus::Collectable>, std::allocator<std::weak_ptr<prometheus::Collectable> > > const&, prometheus::Registry&)':
handler.cc:(.text+0x425): undefined reference to `prometheus::BuildSummary()'
handler.cc:(.text+0x43e): undefined reference to `prometheus::detail::SummaryBuilder::Name(std::string const&)'
handler.cc:(.text+0x450): undefined reference to `prometheus::detail::SummaryBuilder::Help(std::string const&)'
handler.cc:(.text+0x462): undefined reference to `prometheus::detail::SummaryBuilder::Register(prometheus::Registry&)'
/home/tcsapp/nghttp2/prometheus-cpp/_build/deploy/usr/local/lib64/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::Serializer::Serializer()':
handler.cc:(.text._ZN10prometheus10SerializerC2Ev[_ZN10prometheus10SerializerC5Ev]+0xf): undefined reference to `vtable for prometheus::Serializer'
/home/tcsapp/nghttp2/prometheus-cpp/_build/deploy/usr/local/lib64/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::TextSerializer::TextSerializer()':
handler.cc:(.text._ZN10prometheus14TextSerializerC2Ev[_ZN10prometheus14TextSerializerC5Ev]+0x1f): undefined reference to `vtable for prometheus::TextSerializer'
collect2: error: ld returned 1 exit status

I have the .a files link in my c++ make file but during the build there seems to be some missing references within the pull. 

[EDIT] Im linking to the .a files through a Makefile, not CMakeList.txt.

**Comment by aligher** [comment]
Am I not linking a header files correctly?

**Comment by gjasny** [comment]
Did you forget to link the `libprometheus-cpp-core.a` library? It should be placed behind push or pull.

**Comment by aligher** [comment]
I was linking the libprometheus-cpp-core.a file before push and pull. Once I moved it behind those two it seemed to work.

**Comment by gjasny** [comment]
The joy of single pass linkers. CMake or shared libs would have helped here.
