### ISSUE TITLE
If the library support GZIP compression or other type compression when send out the restful response

### ISSUE THREAD

**Issue by willl0320** [jupp0r/prometheus-cpp#141]
When I execute "http://127.0.0.1:8080/metrics", I can get metrics response which is http response.
There is one question for me,
if the library support GZIP compression or other type compression when send out the restful response? if it support, how to configure  it when coding?

**Comment by gjasny** [comment]
Hi, right now prometheus-cpp does not support gzip encoding. It should not be too hard to add it to `MetricsHandler::handleGet`. Do you want to give it a try?

**Comment by gjasny** [comment]
I added gzip support in a feature branch (#143). Could you please give it a try? (Right now it's only working for CMake built prometheus-cpp, not Bazel).

**Comment by willl0320** [comment]
Sorry, I am a beginner for C/C++ program, maybe it is difficult for me
