### ISSUE TITLE
Issue while exporting to MetricBeat

### ISSUE THREAD

**Issue by saikat-prabhakar-guavus** [jupp0r/prometheus-cpp#145]
I am trying to use Prometheus exporters in multiple applications and export the stats to Metricbeat (and to ElasticSearch) on some remote server.
My issues is that I am able to get stats exported from my Kafka cluster using JMX exporter. 
However, when using the cpp exporter I have not been able to get the stats into Metricbeat.
Although, when I do request using browser or curl request on 8090 port, then I can see those stats.

My simple question is that do I need to take care of any pre-requisites while exporting Prometheus stats to third-party tools. Or any constraints in particular for this cpp agent ?

**Comment by jupp0r** [comment]
I haven't used MetricBeat personally, but it looks like it would just access the metrics endpoint, as prometheus does. We recently fixed a bug in the text format (https://github.com/jupp0r/prometheus-cpp/pull/142), can you try building with that? Does MetricBeat give you any hints why it cannot read metrics from your endpoint? Another possibility would be that the metrics names in your code are not compliant (check against these guidelines: https://prometheus.io/docs/practices/naming/). I'm merely speculating here. Getting an error message from MetricBeat would be really helpful.

**Comment by gjasny** [comment]
@saikat-prabhakar-guavus Is this still an issue?

**Comment by jupp0r** [comment]
Closing, feel free to reopen when more info is available.
