### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by 0mp** [jupp0r/prometheus-cpp#149]
I'm rather new to Prometheus clients so please correct me if I misunderstood some concepts.

---

I would like to use the pull library to expose metrics to my Prometheus server. Ideally, those metrics would be gathered by the client program on every request. Is that possible in prometheus-cpp? I'm looking for some kind of an interface to define a callback function to be called whenever client's HTTP server is requested to serve new metrics.

Thank you!

**Comment by jupp0r** [comment]
> I would like to use the pull library to expose metrics to my Prometheus server. Ideally, those metrics would be gathered by the client program on every request. Is that possible in prometheus-cpp?

That's the standard use case and is well supported. The client library opens an http metrics endpoint and the prometheus server is configured to scrape it periodically. How you perform that configuration is dependent on your service discovery solution. You can add the ip address of the client statically or use something like kubernetes or consul and many others to detect your clients automatically.

> I'm looking for some kind of an interface to define a callback function to be called whenever client's HTTP server is requested to serve new metrics.

The interface you are looking for is Collectable https://github.com/jupp0r/prometheus-cpp/blob/master/core/include/prometheus/collectable.h. If you want to use it or not depends on the architecture of your application. Prometheus-cpp comes with an embedded http server that makes it very easy to expose the metrics endpoint that the prometheus server can scrape (using this code creates it: https://github.com/jupp0r/prometheus-cpp/blob/master/core/include/prometheus/collectable.h).

In more advanced use cases, people want to reuse their existing HTTP stack and do not want to use the embedded one prometheus-cpp comes with. In that scenario the Collectable interface you asked about comes into play. You'd call that interface from your existing HTTP request handler, Collectable would return the collected metrics and you'd be responsible for rendering those into the right format (there are helpers for that in the library), set the proper response HTTP headers and send the rendered HTTP response back to the prometheus server in terms of your own HTTP library. If you are interested of how this looks like, you can take a look at https://github.com/jupp0r/prometheus-cpp/blob/master/pull/src/handler.cc, where we do exactly that for the embedded HTTP server prometheus-cpp comes with.

I hope that clarifies these two options and answers your question. I should probably add this information to the Readme.md as well.
