### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED : error in gzip when opening metrics page in browser

### ISSUE THREAD

**Issue by sipian** [jupp0r/prometheus-cpp#151]
I have created a docker container and built prometheus-cpp in it
```
FROM ubuntu:xenial
RUN git clone https://github.com/jupp0r/prometheus-cpp /prometheus-cpp
WORKDIR /prometheus-cpp
RUN git submodule init
RUN git submodule update
RUN mkdir _build
RUN apt-get install -y libcurl4-gnutls-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN cd _build && cmake .. && make -j 4 && make install
```
I installed zlib using `apt-get install zlib1g-dev`

On running the example given in the readme, I am able to get the metrics using 
`curl http://localhost:8001/metrics`.

But when I open this URL in the browser (Chrome & Firefox), I am getting an error. 
`ERR_CONTENT_DECODING_FAILED` 

Based on [this](https://stackoverflow.com/a/14040312/5730790), 
> It happens when your HTTP request's headers claim that the content is gzip encoded, but it isn't.

**Comment by gjasny** [comment]
I messed up. I check for and advertise `gzip` but send out `deflate`.
