### ISSUE TITLE
undefined reference to `prometheus::Exposer::Exposer(

### ISSUE THREAD

**Issue by furiousbanana** [jupp0r/prometheus-cpp#153]
I'm trying to compile the sample code on Ubuntu and i'm running in to undefined reference for line in the code. I'm compiling the cc file using "g++ -o ptest test.cc" command. I followed all the instructions and compiled everything. I even copied all the 3 libraries in the same folder as the test.cc (libprometheus-cpp-core.a  libprometheus-cpp-pull.a  libprometheus-cpp-push.a) but i still get these errors. I'm new to linux environment so please bear with me. What am i missing here?

test.cc:(.text+0x223): undefined reference to `prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cc:(.text+0x27d): undefined reference to `prometheus::BuildCounter()'
test.cc:(.text+0x2c2): undefined reference to `prometheus::detail::CounterBuilder::Name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cc:(.text+0x303): undefined reference to `prometheus::detail::CounterBuilder::Help(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cc:(.text+0x38e): undefined reference to `prometheus::detail::CounterBuilder::Labels(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
test.cc:(.text+0x3ab): undefined reference to `prometheus::detail::CounterBuilder::Register(prometheus::Registry&)'
test.cc:(.text+0x564): undefined reference to `prometheus::Exposer::RegisterCollectable(std::weak_ptr<prometheus::Collectable> const&)'
test.cc:(.text+0x5b4): undefined reference to `prometheus::Counter::Increment()'
test.cc:(.text+0x749): undefined reference to `prometheus::Exposer::~Exposer()'
/tmp/cc2ZH45l.o: In function `prometheus::Counter::Counter()':
test.cc:(.text._ZN10prometheus7CounterC2Ev[_ZN10prometheus7CounterC5Ev]+0x14): undefined reference to `prometheus::Gauge::Gauge()'
/tmp/cc2ZH45l.o: In function `prometheus::Counter& prometheus::Family<prometheus::Counter>::Add<>(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
test.cc:(.text._ZN10prometheus6FamilyINS_7CounterEE3AddIJEEERS1_RKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_St4lessISB_ESaISt4pairIKSB_SB_EEEDpOT_[_ZN10prometheus6FamilyINS_7CounterEE3AddIJEEERS1_RKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_St4lessISB_ESaISt4pairIKSB_SB_EEEDpOT_]+0x8d): undefined reference to `prometheus::CheckLabelName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cc2ZH45l.o: In function `prometheus::Registry::Registry()':
test.cc:(.text._ZN10prometheus8RegistryC2Ev[_ZN10prometheus8RegistryC5Ev]+0x1b): undefined reference to `vtable for prometheus::Registry'

**Comment by gjasny** [comment]
Please take a look at #139

**Comment by furiousbanana** [comment]
Thank you. I had to add -lz and -pthread on top of those 3 libs to make it work.
