### ISSUE TITLE
expected equal, got "LNAME"

### ISSUE THREAD

**Issue by furiousbanana** [jupp0r/prometheus-cpp#154]
Prometheus web page shows this error in the Targets under Status for my endpoint. I'm running simple test app using sample code except that I added a gauge as well. If i remove the gauge it works fine. I'm adding gauge like this:

    // Gauge
    auto& gauge_family = BuildGauge()
                             .Name("some_gauge")
                             .Help("some gauge help")
                             .Labels({{"some gauge label", "some value"}})
                             .Register(*registry);

    auto& some_gauge = gauge_family.Add({});
 
And then increment it in the for loop.
      some_gauge.Increment(0.1);

What am i doing wrong?

**Comment by jupp0r** [comment]
What version of prometheus and prometheus-cpp are you using?

**Comment by furiousbanana** [comment]
Both are latest. I downloaded them yesterday. prometheus-cpp is cloned from master branch.

**Comment by furiousbanana** [comment]
btw, i should be adding both the counter family and gauge family to same registry right?
.Register(*registry);

**Comment by jupp0r** [comment]
> btw, i should be adding both the counter family and gauge family to same registry right?
.Register(*registry);

Yeah that's correct.

Can you visit the metrics endpoint and post what it exposes?

**Comment by furiousbanana** [comment]
When i do curl get http://localhost:8080/metrics this is what it returns

curl: (7) Failed to connect to get port 80: No route to host
# HELP exposer_bytes_transferred bytesTransferred to metrics services
# TYPE exposer_bytes_transferred counter
exposer_bytes_transferred 2488.000000
# HELP exposer_total_scrapes Number of times metrics were scraped
# TYPE exposer_total_scrapes counter
exposer_total_scrapes 7.000000
# HELP exposer_request_latencies Latencies of serving scrape requests, in microseconds
# TYPE exposer_request_latencies summary
exposer_request_latencies_count 7
exposer_request_latencies_sum 3575.000000
exposer_request_latencies{quantile="0.500000"} 433.000000
exposer_request_latencies{quantile="0.900000"} 572.000000
exposer_request_latencies{quantile="0.990000"} 572.000000
# HELP time_running_seconds How many seconds is this server running?
# TYPE time_running_seconds counter
time_running_seconds{label="value",another_label="value",yet_another_label="value"} 32.000000
# HELP some_gauge some gauge help
# TYPE some_gauge gauge
some_gauge{some gauge label="some value"} 3.200000

**Comment by jupp0r** [comment]
"some gauge label" is not a valid label. Can you try "some_gauge_label" instead? See https://prometheus.io/docs/practices/naming/. We do actually check for this in https://github.com/jupp0r/prometheus-cpp/blob/master/core/src/check_names.cc, but checks are disabled for some very old compilers that don't support `std::regex`.

**Comment by furiousbanana** [comment]
Cool. that worked. thanks a lot.
Btw, do you have any documentation on how to configure summary and histogram? I'm not completely clear from the unit tests that you have.
