### ISSUE TITLE
cannot build from tar.gz

### ISSUE THREAD

**Issue by skarlsson** [jupp0r/prometheus-cpp#155]
When I do a'source build without checking out a repo the build fails due to a hardcoded search path to prometheus-cpp/3rdparty/civetweb/include

I've already built all dependencys and placed them at /usr/local/include (and lib)

My build look like this:

wget -O prometheus-cpp.tar.gz "https://github.com/jupp0r/prometheus-cpp/archive/v0.4.2.tar.gz" && \
mkdir -p prometheus-cpp && \
tar \
  --extract \
  --file prometheus-cpp.tar.gz \
  --directory prometheus-cpp \
  --strip-components 1 && \
cd prometheus-cpp && \
mkdir build && cd build && \
cmake  -DCMAKE_BUILD_TYPE=Release ..

error...
CMake Error at cmake/civetweb-config.cmake:6 (message):
  File or directory /home/saka/prometheus-cpp/3rdparty/civetweb/include
  referenced by variable CIVETWEB_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  cmake/civetweb-config.cmake:10 (set_and_check)
  pull/CMakeLists.txt:1 (find_package)

**Comment by gjasny** [comment]
Right now the CMake build embeds civetweb from a submodule directly into the pull library. If you don't use civetweb somewhere else in your process I'd suggest that you put civetweb into the expected directory.

I need to work on a patch to use an external civetweb library. But it might take some days.

**Comment by skarlsson** [comment]
my problem is that I'm using somewhere else - that's why I need to build it out of source to be sure of the versions. copy from /usr/local/include will work for now. Thanks

**Comment by gjasny** [comment]
Hi, could you please give https://github.com/jupp0r/prometheus-cpp/tree/external-dependencies a try? It's a rough version that allows one to use external civetweb (no cpr yet).
Please build with: `-DUSE_THIRDPARTY_LIBRARIES=OFF -DENABLE_PUSH=OFF -DENABLE_TESTING=OFF`

**Comment by gjasny** [comment]
Could you please give #159 a try?

**Comment by skarlsson** [comment]
Sorry missed this, will try tomorrow

**Comment by skarlsson** [comment]
Thanks, works like a charm - can I which for cpr also?

**Comment by yaminisridaran** [comment]
[yamini_sridaran@abdee642ae19 _build]$ cmake .. -DUSE_THIRDPARTY_LIBRARIES=OFF -DENABLE_PUSH=OFF -DENABLE_TESTING=OFF
CMake Error at cmake/civetweb-config.cmake:6 (message):
  File or directory
  /src/cna/.build/prometheus/BUILD/prometheus-cpp-0.5.0/3rdparty/civetweb/include
  referenced by variable CIVETWEB_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  cmake/civetweb-config.cmake:10 (set_and_check)
  pull/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by yaminisridaran** [comment]
Can anyone please let me know about the above mentioned issue
