### ISSUE TITLE
Does this c++ prometheus client can collect pod information automatically?

### ISSUE THREAD

**Issue by yaminisridaran** [jupp0r/prometheus-cpp#161]
Does this c++ prometheus client can collect pod information automatically?

**Comment by jupp0r** [comment]
I assume you are referring to [prometheus' kubernetes service discovery configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Ckubernetes_sd_config%3E)? If so, then this library is completely oblivious about it and should work well for any service discovery mechanism.
