### ISSUE TITLE
Can prometheus client library be used in application library

### ISSUE THREAD

**Issue by yaminisridaran** [jupp0r/prometheus-cpp#168]
I am trying to use prometheus client library in application library.
I am getting below mentioned error
usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(check_names.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(counter_builder.cc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(gauge.cc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(registry.cc.o): relocation R_X86_64_32 against symbol `_ZTVN10prometheus11CollectableE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(summary.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(counter.cc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprometheus-cpp-core.a(histogram.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

**Comment by jupp0r** [comment]
prometheus-cpp can be used in libraries. Certain compile flags you are using for your library have to match, more specifically, `-fPIC` has to be either set or unset for both prometheus-cpp and your library in order to link them together. You can read more about position independent code at https://en.wikipedia.org/wiki/Position-independent_code

**Comment by yaminisridaran** [comment]
Is it -fPIC to set in cmake (eg: cmake -fPIC ..)
