### ISSUE TITLE
can we compile the prometheus client library to .so shared library

### ISSUE THREAD

**Issue by yaminisridaran** [jupp0r/prometheus-cpp#171]
can we compile the prometheus client library to .so shared library.
If we can compile the prometheus client library to shared library (.so file).
Please let me know the steps how to compile?

**Comment by gjasny** [comment]
Just add the CMake flag `-DBUILD_SHARED_LIB=ON`

**Comment by yaminisridaran** [comment]
cmake -DBUILD_SHARED_LIB=ON .. . Does not provide .so files? Please correct me if the command is incorrect

**Comment by gjasny** [comment]
Whoops missed the trailing S: https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by yaminisridaran** [comment]
Thank you so much for response. I am completely new to cmake. Can you please let me know how to set this flag.

**Comment by yaminisridaran** [comment]
Thank you. cmake -DBUILD_SHARED_LIBS=ON works for me now

**Comment by palmerlao** [comment]
I would like this for one of my Bazel builds, and have created a PR at #181 containing a patch that helped me.
