### ISSUE TITLE
dynamic creation and deletion of counters.

### ISSUE THREAD

**Issue by sunildr** [jupp0r/prometheus-cpp#178]
I have a use-case where my component (object) which creates the prometheus counters is dynamically created when a connection comes up. And when the connection goes down, the component is deleted. 

What happens to the counters and the registry when the holding object is deleted? Is there a way to unregister/deregister the counters from the registry before my component is deleted?

The registry is not part of this component i.e. it stays even without the component.

**Comment by jupp0r** [comment]
Does that make sense?

**Comment by hhoffstaette** [comment]
So this affects me too, even if it's with low cardinality. In my case I'm trying to write an exporter for filesystems, and even though those have unique fsids (effectively limiting the cardinality to at most a dozen) they can be mounted/unmounted, and I need to stop collecting & updating metrics for filesystems that have disappeared. I understand the point you made in #183 (use a map to manage my own sets of counters) but I still need a way to unregister Collectables from the registry again.
The only other way would be to stop the scraper & recreate everything - which seems unnecessarily complicated, not to mention fragile. A simple Delete() that takes a collection (for batching) of the refs returned from Add() would be super useful.

**Comment by jupp0r** [comment]
Just to give you a heads up, I'm implementing this right now and should have something ready for review in the next few days.

**Comment by laozhang007** [comment]
This affects me too.Hope to delete all counters or registry at once and free the memory.

**Comment by brian-brazil** [comment]
> In my case I'm trying to write an exporter for filesystems, and even though those have unique fsids (effectively limiting the cardinality to at most a dozen) they can be mounted/unmounted, and I need to stop collecting & updating metrics for filesystems that have disappeared

This doesn't sound right, you wouldn't be deleting metrics in that case but removing children. It sounds like what you're looking for is a custom collector, which appears to be the `Collectable` interface in this client library.

**Comment by hhoffstaette** [comment]
> This doesn't sound right, you wouldn't be deleting metrics in that case but removing children.
> It sounds like what you're looking for is a custom collector, which appears to be the `Collectable`
> interface in this client library.

You'll be glad to hear that's exactly what I did back when. :)

**Comment by gjasny** [comment]
The `Exposer` nowadays has a `RemoveCollectable` function:
https://github.com/jupp0r/prometheus-cpp/blob/77a5b0172833786ec014498d61a4dd87c500dc3b/pull/include/prometheus/exposer.h#L34-L35

**Comment by CoderPoet** [comment]
> The `Exposer` nowadays has a `RemoveCollectable` function:
> 
> https://github.com/jupp0r/prometheus-cpp/blob/77a5b0172833786ec014498d61a4dd87c500dc3b/pull/include/prometheus/exposer.h#L34-L35


This doesn't seem to be able to clean up stale metrics all at once?
