### ISSUE TITLE
Target app not built

### ISSUE THREAD

**Issue by SkipUFO** [jupp0r/prometheus-cpp#187]
I have built promethues-cpp lib

>
The C compiler identification is GNU 7.3.0 
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find GoogleBenchmark (missing: GoogleBenchmark_LIBRARY GoogleBenchmark_INCLUDE_DIR)
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/prometheus-cpp
Scanning dependencies of target core
Scanning dependencies of target cpr
Scanning dependencies of target civetweb
Scanning dependencies of target gmock_main
[  2%] Building CXX object core/CMakeFiles/core.dir/src/check_names.cc.o
[  4%] Building CXX object pull/CMakeFiles/civetweb.dir/__/3rdparty/civetweb/src/CivetServer.cpp.o
[  6%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/auth.cpp.o
[  8%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googletest/src/gtest-all.cc.o
[ 10%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/cookies.cpp.o
[ 12%] Building C object pull/CMakeFiles/civetweb.dir/__/3rdparty/civetweb/src/civetweb.c.o
[ 14%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/cprtypes.cpp.o
[ 16%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/digest.cpp.o
[ 16%] Built target civetweb
[ 18%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googlemock/src/gmock-all.cc.o
[ 20%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/error.cpp.o
[ 22%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/multipart.cpp.o
[ 24%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/parameters.cpp.o
[ 26%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/payload.cpp.o
[ 28%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/proxies.cpp.o
[ 30%] Building CXX object core/CMakeFiles/core.dir/src/counter.cc.o
[ 32%] Building CXX object core/CMakeFiles/core.dir/src/counter_builder.cc.o
[ 34%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/session.cpp.o
[ 36%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googlemock/src/gmock_main.cc.o
[ 38%] Building CXX object core/CMakeFiles/core.dir/src/gauge.cc.o
[ 40%] Building CXX object core/CMakeFiles/core.dir/src/gauge_builder.cc.o
[ 42%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/ssl_options.cpp.o
[ 44%] Building CXX object core/CMakeFiles/core.dir/src/histogram.cc.o
[ 46%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/timeout.cpp.o
[ 48%] Building CXX object push/CMakeFiles/cpr.dir/__/3rdparty/cpr/cpr/util.cpp.o
[ 51%] Building CXX object core/CMakeFiles/core.dir/src/histogram_builder.cc.o
[ 53%] Linking CXX static library libgmock_main.a
[ 53%] Built target gmock_main
[ 55%] Building CXX object core/CMakeFiles/core.dir/src/registry.cc.o
[ 57%] Building CXX object core/CMakeFiles/core.dir/src/serializer.cc.o
[ 57%] Built target cpr
[ 59%] Building CXX object core/CMakeFiles/core.dir/src/summary.cc.o
[ 61%] Building CXX object core/CMakeFiles/core.dir/src/summary_builder.cc.o
[ 63%] Building CXX object core/CMakeFiles/core.dir/src/text_serializer.cc.o
[ 65%] Linking CXX static library libprometheus-cpp-core.a
[ 65%] Built target core
Scanning dependencies of target push
Scanning dependencies of target pull
Scanning dependencies of target prometheus_test
[ 67%] Building CXX object pull/CMakeFiles/pull.dir/src/handler.cc.o
[ 69%] Building CXX object push/CMakeFiles/push.dir/src/gateway.cc.o
[ 71%] Building CXX object pull/CMakeFiles/pull.dir/src/exposer.cc.o
[ 73%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/check_names_test.cc.o
[ 75%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/counter_test.cc.o
[ 77%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/family_test.cc.o
[ 79%] Linking CXX static library libprometheus-cpp-pull.a
[ 79%] Built target pull
[ 81%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/gauge_test.cc.o
[ 83%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/histogram_test.cc.o
[ 85%] Linking CXX static library libprometheus-cpp-push.a
[ 85%] Built target push
Scanning dependencies of target sample_server
[ 87%] Building CXX object pull/tests/integration/CMakeFiles/sample_server.dir/sample_server.cc.o
[ 89%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/registry_test.cc.o
[ 91%] Building CXX object core/tests/CMakeFiles/prometheus_test.dir/summary_test.cc.o
[ 93%] Linking CXX executable sample_server
[ 93%] Built target sample_server
Scanning dependencies of target sample_client
[ 95%] Building CXX object push/tests/integration/CMakeFiles/sample_client.dir/sample_client.cc.o
[ 97%] Linking CXX executable prometheus_test
[100%] Linking CXX executable sample_client
[100%] Built target prometheus_test
[100%] Built target sample_client
[ 26%] Built target core
[ 34%] Built target gmock_main
[ 51%] Built target prometheus_test
[ 55%] Built target civetweb
[ 61%] Built target pull
[ 65%] Built target sample_server
[ 91%] Built target cpr
[ 95%] Built target push
[100%] Built target sample_client
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/cmake/prometheus-cpp/prometheus-cpp-targets.cmake
-- Installing: /usr/local/lib/cmake/prometheus-cpp/prometheus-cpp-targets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/prometheus-cpp/prometheus-cpp-config.cmake
-- Installing: /usr/local/lib/libprometheus-cpp-core.a
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/prometheus
-- Installing: /usr/local/include/prometheus/gauge.h
-- Installing: /usr/local/include/prometheus/metric_family.h
-- Installing: /usr/local/include/prometheus/counter.h
-- Installing: /usr/local/include/prometheus/text_serializer.h
-- Installing: /usr/local/include/prometheus/registry.h
-- Installing: /usr/local/include/prometheus/check_names.h
-- Installing: /usr/local/include/prometheus/summary_builder.h
-- Installing: /usr/local/include/prometheus/client_metric.h
-- Installing: /usr/local/include/prometheus/metric_type.h
-- Installing: /usr/local/include/prometheus/summary.h
-- Installing: /usr/local/include/prometheus/family.h
-- Installing: /usr/local/include/prometheus/counter_builder.h
-- Installing: /usr/local/include/prometheus/gauge_builder.h
-- Installing: /usr/local/include/prometheus/serializer.h
-- Installing: /usr/local/include/prometheus/collectable.h
-- Installing: /usr/local/include/prometheus/histogram.h
-- Installing: /usr/local/include/prometheus/histogram_builder.h
-- Installing: /usr/local/lib/libprometheus-cpp-pull.a
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/prometheus
-- Installing: /usr/local/include/prometheus/exposer.h
-- Installing: /usr/local/lib/libprometheus-cpp-push.a
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/prometheus
-- Installing: /usr/local/include/prometheus/gateway.h
--

I try example from repo and have link error

> 
g++ -m64 -Wl,-O1 -o online-backend main.o    -L/usr/lib/x86_64-linux-gnu -lprometheus-cpp-core -lprometheus-cpp-pull -lQtGui -lQtCore -lpthread 
//usr/local/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::MetricsHandler::MetricsHandler(std::vector<std::weak_ptr<prometheus::Collectable>, std::allocator<std::weak_ptr<prometheus::Collectable> > > const&, prometheus::Registry&)':
handler.cc:(.text+0x479): undefined reference to `prometheus::BuildSummary()'
handler.cc:(.text+0x4be): undefined reference to `prometheus::detail::SummaryBuilder::Name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
handler.cc:(.text+0x4ff): undefined reference to `prometheus::detail::SummaryBuilder::Help(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
handler.cc:(.text+0x514): undefined reference to `prometheus::detail::SummaryBuilder::Register(prometheus::Registry&)'
//usr/local/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::GZipCompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
handler.cc:(.text+0x9a5): undefined reference to `deflateInit2_'
handler.cc:(.text+0xa7d): undefined reference to `deflate'
handler.cc:(.text+0xab3): undefined reference to `deflateEnd'
//usr/local/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::Serializer::Serializer()':
handler.cc:(.text._ZN10prometheus10SerializerC2Ev[_ZN10prometheus10SerializerC5Ev]+0xb): undefined reference to `vtable for prometheus::Serializer'
//usr/local/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::TextSerializer::TextSerializer()':
handler.cc:(.text._ZN10prometheus14TextSerializerC2Ev[_ZN10prometheus14TextSerializerC5Ev]+0x1b): undefined reference to `vtable for prometheus::TextSerializer'
collect2: error: ld returned 1 exit status
Makefile:102: recipe for target 'online-backend' failed
make: *** [online-backend] Error 1
--

**Comment by jerryct** [comment]
Do you use CMake or Bazel or did you create the 'g++' command by yourself? If you made it yourself note that the order of providing the libraries with `-l` is important. I think you need to swap `-lprometheus-cpp-core`  and `-lprometheus-cpp-pull`. Also it seems the gzip library is missing in `-l`.

**Comment by SkipUFO** [comment]
If i build with -DBUILD_SHARED_LIBS=ON  there is no link problem

**Comment by SkipUFO** [comment]
> Do you use CMake or Bazel or did you create the 'g++' command by yourself? If you made it yourself note that the order of providing the libraries with `-l` is important. I think you need to swap `-lprometheus-cpp-core` and `-lprometheus-cpp-pull`. Also it seems the gzip library is missing in `-l`.
--
I have built prometheus cpp as static libs and I have an error. 
I use Qt
`
TARGET = online-backend
TEMPLATE = app

CONFIG   -= app_bundle
CONFIG   += c++11

LIBS += \
    -lprometheus-cpp-core \
    #-lprometheus-cpp-push \
    -lprometheus-cpp-pull

#

SOURCES += \
    main.cpp
`
this is .pro file

**Comment by jerryct** [comment]
I tried the code snippet from the frontpage and this command line

`g++ -o app main.o -L/tmp/lib -lprometheus-cpp-pull -lprometheus-cpp-core -lpthread -lz`

works. If I remove `-lz` and use `-lprometheus-cpp-core -lprometheus-cpp-pull` I get the same errors as you. As I said you should try to swap ...core and ...pull and add `-lz`.

**Comment by SkipUFO** [comment]
Thanks a lot! 
Swapping libs order helped 
True order is 
`-lprometheus-cpp-pull -lprometheus-cpp-core -lz`
