### ISSUE TITLE
Scope for Boost.MultiIndex in Family template class?

### ISSUE THREAD

**Issue by zerodefect** [jupp0r/prometheus-cpp#226]
The Family template class would be a good candidate for using Boost's MultiIndex (header only) - there are a number of insert/lookup operations which could be simplified.

I appreciate that there may be hesitation since this would mean an additional third-party dependency.

**Comment by jerryct** [comment]
Hi. My preference would be to avoid this additional dependency. Currently the core part only relies on the C++ standard library. This makes it usable in restricted environments.

**Comment by jupp0r** [comment]
I agree with @jerryct here, while boost is a phenomenal set of libraries I'd want to avoid it at any cost to make consumption of prometheus-cpp easier (civetweb etc make it somewhat tricky already).
