### ISSUE TITLE
Consider use modern cmake target_* instead of global options

### ISSUE THREAD

**Issue by gocarlos** [jupp0r/prometheus-cpp#238]
I think that to not break people builds we should use target_compile_definitions and target_compile_options  instead of add_compile_options due to the fact that those options pollute the whole build, not only this library

**Comment by gjasny** [comment]
Could you please describe a case where pollution will happen? IMHO the chosen approach will not pollute the exported targets because the compile options will be applied as directory property. Those are only applied to subdirs like core, pull, and push.

**Comment by gocarlos** [comment]
you are right, I was thinking that add_compile_options would pollute also binaries linking to this lib... 
none the less, I think that the right approach for the future is the usage of the target_* commands


ref: https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#forget-the-commands-add_compile_options-include_directories-link_directories-link_libraries

**Comment by jerryct** [comment]
Hi. 

You are right that one should prefer target_* commands. But if you want to specify a warning level set for the whole project, I think the best approach is to use add_compile_options(). The alternative would be to create a global variable in the top-level CMakeLists.txt which is used by all target_compile_options() commands (without the global variable you have to copy all flags all over with the burden to keep them in sync).

So I don't see such a big difference between the two approaches for this specific use case (define one global set of project level warnings). But the add_compile_options() has the advantage that it applies to all targets and cannot be forgotten. The other approach has the drawback that one could forget to add these flags to a target, for example if someone adds a new target afterwards. 

Also your link suggests only one section above: Define project properties globally:
https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#define-project-properties-globally

**Comment by gocarlos** [comment]
Thats right, I agree with your points 👍 

The whole point of this issue was that i thought add_compile_options would also affect targets that use this lib, as this is not the case, i close this issue, thanks
