### ISSUE TITLE
Build error due to bad pragma in utils.h

### ISSUE THREAD

**Issue by jplflyer** [jupp0r/prometheus-cpp#241]
The first line of utils.h is:

#pragma onece

and should be

#pragma once

Exposed readily with -Wall compile option as shown:

g++ -c -o obj/FirstProm.o --std=c++11 -I../../CT-StandardLibrary/src -I../../CT-StandardLibrary/src/includes -Wall -x c++ src/FirstProm.cpp
In file included from ../../CT-StandardLibrary/src/includes/prometheus/family.h:20:0,
                 from ../../CT-StandardLibrary/src/includes/prometheus/registry.h:16,
                 from ../../CT-StandardLibrary/src/includes/prometheus/exposer.h:10,
                 from src/FirstProm.cpp:7:
../../CT-StandardLibrary/src/includes/prometheus/detail/utils.h:1:0: warning: ignoring #pragma onece  [-Wunknown-pragmas]

**Comment by gjasny** [comment]
That should have been fixed by #237
