### ISSUE TITLE
find civetweb not working as expected

### ISSUE THREAD

**Issue by gocarlos** [jupp0r/prometheus-cpp#244]
civetweb now exports the cmake files, so when you install civetweb we get `civetweb::civetweb` targets in the `usr/local/lib/cmake/civetweb`

those are different then the ones that we have here in the cmake folder: `CivetWeb::CivetWeb`

due to the lowercase vs camecase, I get an compilation (configuration) error when using the newest version of civetweb and the newest version of prometheus-cpp...

**Comment by gocarlos** [comment]
cc/ @bachp

**Comment by gjasny** [comment]
Unfortunately there's no release of civetweb, yet.

Could you please try to add the `MODULE` keyword to the civetweb `find_package()` command?

**Comment by gjasny** [comment]
Due to the upcoming holiday season I'm short on time. Could you please file a pull request?

**Comment by gocarlos** [comment]
Let me have a look on this tomorrow

**Comment by gjasny** [comment]
Closed by #245
