### ISSUE TITLE
git_repository rule doesn't support attribute "branch"

### ISSUE THREAD

**Issue by AlexTaran** [jupp0r/prometheus-cpp#25]
Added dependency to workspace as described in README.md
Got a build error:
//external:prometheus-cpp: no such attribute 'branch' in 'git_repository' rule.

According to bazel doc, there's no such attribute:
https://www.bazel.io/versions/master/docs/be/workspace.html#git_repository

Also got an error:
git_repository rule //external:prometheus-cpp's name field must be a legal workspace name.
According to this https://bazel.build/versions/master/docs/be/functions.html#workspace
and this
https://github.com/bazelbuild/bazel/commit/d21c2d6653a3d9bc3376bcb190ba0ac31f52195b

repository name must not contain underscores.

**Comment by jupp0r** [comment]
Thanks for pointing this out. I'll fix it asap and also add a test.

**Comment by jupp0r** [comment]
@AlexTaran, you could also potentially benefit from the recently added cmake support.
