### ISSUE TITLE
how to build prometheus-cpp as shared libraries with cmake? 

### ISSUE THREAD

**Issue by AmitBawer** [jupp0r/prometheus-cpp#251]
Hi
currently cmake build process creates only static libraries (.a)
is it possible to apply cmake some config/flag to create the libraries as .so objects instead?

**Comment by gjasny** [comment]
Hello,

Sorry for not documenting this. Have a look at #171.

Thanks,
Gregor

**Comment by AmitBawer** [comment]
Thanks. This did the trick :)
