### ISSUE TITLE
Gateway's AsyncPush is Broken

### ISSUE THREAD

**Issue by MichaelMitchellM** [jupp0r/prometheus-cpp#252]
I believe there is a bit of a race condition in [Gateway::async_push](https://github.com/jupp0r/prometheus-cpp/blob/master/push/src/gateway.cc#L154).

On [L156](https://github.com/jupp0r/prometheus-cpp/blob/master/push/src/gateway.cc#L156) we declare a vector on the stack. This vector will be destructed at the end of `async_push` in the calling thread. On [L176](https://github.com/jupp0r/prometheus-cpp/blob/master/push/src/gateway.cc#L176) we reference the `futures` vector in a lambda that captures the stack allocated vector by reference and executes uses it in a [guaranteed new thread](https://en.cppreference.com/w/cpp/thread/launch). There is a good chance that before that new thread gets to use its reference to `futures` that it will be destructed in the thread that calls `async_push` 😢.

A possible solution is allocating the `futures` vector in a `std::shared_ptr` and then use a by-copy capture of the `shared_ptr` in the lambda. This should defer the destruction of the vector until `async`'s thread is done with it.

Another solution could be to forward the `futures` vector as an argument of the lambda and do a `std::move` as an argument to the `std::async` call.

**Comment by jupp0r** [comment]
Definitely a dangling reference there. Either solution should be fine.

**Comment by MichaelMitchellM** [comment]
@jupp0r I am currently unable to submit a pull request due to company legal stuff 🙃

**Comment by jupp0r** [comment]
I know that one. I'll fix it.

**Comment by MichaelMitchellM** [comment]
Would it be possible to get this patch in vcpkg?
