### ISSUE TITLE
bazel error when adding project as a dependency

### ISSUE THREAD

**Issue by truephelle** [jupp0r/prometheus-cpp#256]
When I tried to add prometheus-cpp as a dependency in my project (sample_server with another name), I have got the error:
`INFO: Invocation ID: 1b1c785e-de5a-49a1-8134-4f4b72720f5a
INFO: SHA256 (https://github.com/jupp0r/prometheus-cpp/archive/master.zip) = 61fffdbec46377152c4ff5806a29bd6b7cd9b97befcbd55527829ef81e3df09f
DEBUG: Rule 'com_github_jupp0r_prometheus_cpp' modified arguments {"sha256": "61fffdbec46377152c4ff5806a29bd6b7cd9b97befcbd55527829ef81e3df09f"}
ERROR: /media/developer/ssd/unidbstore/src/unidbstore/BUILD.bazel:2:1: no such target '@com_github_jupp0r_prometheus_cpp//:prometheus_cpp': target 'prometheus_cpp' not declared in package '' defined by /home/developer/.cache/bazel/_bazel_developer/3348f9b651467b8243c27bd2ab843ea0/external/com_github_jupp0r_prometheus_cpp/BUILD.bazel and referenced by '//src/unidbstore:unidbstore'
ERROR: Analysis of target '//src/unidbstore:unidbstore' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.336s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded, 55 targets configured)`
`src/unidbstore/BUILD.bazel `contains:
```
cc_binary(
       name = "unidbstore",
       srcs = ["unidbstore.cpp"],
       deps = ["@com_github_jupp0r_prometheus_cpp//:prometheus_cpp"],
)
```
Building with 
bazel build //src/unidbstore:unidbstore

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
  name = "com_github_jupp0r_prometheus_cpp",
  strip_prefix = "prometheus-cpp-master",
  urls = ["https://github.com/jupp0r/prometheus-cpp/archive/master.zip"],
)
load("@com_github_jupp0r_prometheus_cpp//:repositories.bzl", "prometheus_cpp_repositories")
prometheus_cpp_repositories()

```

**Comment by gjasny** [comment]
Prometheus-cpp has been slit into core, push, and pull. You probably need to depend on `@com_github_jupp0r_prometheus_cpp//pull`
