### ISSUE TITLE
need clarification on labels

### ISSUE THREAD

**Issue by davehorton** [jupp0r/prometheus-cpp#260]
I'm confused about how to use labels, and the simple "yet another label" example is not very illustrative.

Could you please show how to implement the following simple example:
I have a server that will be both sending and receiving http requests.
I want to track the metric 'http_requests_total' along these dimensions:
- 'direction' (allowed values could be 'in' or 'out')
- 'method' (allowed values could be 'POST' or 'GET')

Other client libraries [like this Node.js one](https://github.com/siimon/prom-client#labels) take the approach of specifying the allowed label names, which seems straightforward.  I think you have  a different approach, wherein I need to also specify all of the possible allowable values (?) but I am not quite following from the simple example...

**Comment by gjasny** [comment]
Hello,

the following code
```c++
  auto& http_requests_family = BuildCounter()
      .Name("http_requests_total")
      .Help("How many requests were served?")
      .Register(*registry);

  auto& http_requests_post_in = http_requests_family.Add(
      {{"method", "POST"}, {"direction", "in"}});
  auto& http_requests_post_out = http_requests_family.Add(
      {{"method", "POST"}, {"direction", "out"}});
  auto& http_requests_get_in = http_requests_family.Add(
      {{"method", "GET"}, {"direction", "in"}});
  auto& http_requests_get_out = http_requests_family.Add(
      {{"method", "GET"}, {"direction", "out"}});

  http_requests_post_in.Increment(3);
  http_requests_post_out.Increment(5);
  http_requests_get_in.Increment(7);
  http_requests_get_out.Increment(9);
```

would result in the following metrics:
```
# HELP http_requests_total How many requests were served?
# TYPE http_requests_total counter
http_requests_total{direction="out",method="GET"} 9.000000
http_requests_total{direction="in",method="GET"} 7.000000
http_requests_total{direction="out",method="POST"} 5.000000
http_requests_total{direction="in",method="POST"} 3.000000
```

Does that answer your question?

Thanks,
Gregor

**Comment by davehorton** [comment]
Yes, indeed.  Thanks!
