### ISSUE TITLE
Failed to make on ubuntu16.04

### ISSUE THREAD

**Issue by jacqueline0124** [jupp0r/prometheus-cpp#264]
when I  make -j failure as follows

[ 95%] Building CXX object pull/tests/integration/CMakeFiles/sample_server.dir/sample_server.cc.o
[ 97%] Linking CXX executable sample_server
[ 97%] Built target sample_server
[100%] Linking CXX executable benchmarks
/usr/local/lib/libbenchmark.a(benchmark_runner.cc.o): In function `benchmark::internal::RunBenchmark(benchmark::internal::BenchmarkInstance const&, std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> >*)':
benchmark_runner.cc:(.text+0xb08): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
core/benchmarks/CMakeFiles/benchmarks.dir/build.make:252: recipe for target 'core/benchmarks/benchmarks' failed
make[2]: *** [core/benchmarks/benchmarks] Error 1
CMakeFiles/Makefile2:233: recipe for target 'core/benchmarks/CMakeFiles/benchmarks.dir/all' failed
make[1]: *** [core/benchmarks/CMakeFiles/benchmarks.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gjasny** [comment]
Which OS in which version are you using?

**Comment by gjasny** [comment]
I'll take a look when I'm back at work next week.
