### ISSUE TITLE
Could you kindly provide the license owner name?

### ISSUE THREAD

**Issue by luxion** [jupp0r/prometheus-cpp#265]
To Whom It May Concern,

Hello, I would like to use your library "promethus-cpp".
However, I realized your license file doesn't mentions the name of license owner as such `Copyright (c) [year] [fullname]` . Therefore, I can't use it at this moment.

https://github.com/jupp0r/prometheus-cpp/blob/master/LICENSE#L3

Could you kindly provide the license owner name for use whenever you have time?
I understand you are very busy and appreciate your time and attention.

Best regards,

**Comment by gjasny** [comment]
IANL. Hope this works for you.
