### ISSUE TITLE
Metricbeat issue to export to ELK

### ISSUE THREAD

**Issue by GilGil1** [jupp0r/prometheus-cpp#275]
Hi, 
I got an issue with ELK **MetricBeat** agent to scrape metrics and publish to elastic search. 
I believe the issue is located. It was caused by my coding mistake, I created multiple counter families with the **same name**. 
Prometheus was able to ingest it. However, metric beat couldn't (and didn't log the exception).
My question - is it a valid 'open metrics' format to have multiple counters with the same header as in my input below?

**Example of erroneous text output**
``` 
# TYPE fictuous_counter counter
fictuous_counter{id="guid-1-2-3-4",process="agent1"} 2.000000
fictuous_counter{id="guid-1-2-3-4",process="agent2"} 4.000000
# HELP fictuous_counter counter counter
# TYPE fictuous_counter counter
fictuous_counter{id="guid-1-2-3-4",process="agent1"} 2.000000
fictuous_counter{id="guid-1-2-3-4",process="agent2"} 4.000000
# HELP fictuous_counter counter counter
# TYPE fictuous_counter counter
fictuous_counter{id="guid-1-2-3-4",process="agent1"} 2.000000
fictuous_counter{id="guid-1-2-3-4",process="agent2"} 4.000000
```

**Comment by brian-brazil** [comment]
This is not valid Prometheus text exposition format (due to the duplicates), nor is it valid OpenMetrics format (for several reasons). A client library should generally throw an exception when there's a duplicate registration, as this is a programming error.

**Comment by gjasny** [comment]
With the current implementation you cannot create the same family name within the same registry. But you register two independent registries within the same exposer endpoint it could still happen. Do you think this is a case worth testing for?
