### ISSUE TITLE
Build issue with prometheus-cpp-0.7.0 CIVETWEB_INCLUDE_DIR

### ISSUE THREAD

**Issue by adriantong1024** [jupp0r/prometheus-cpp#276]
Build issue with prometheus-cpp-0.7.0 on Linux. Any insight on how to fix is greatly appreciated. 

Thanks 
-Adrian
~/prometheus-cpp-0.7.0/_build$ cmake .. -DBUILD_SHARED_LIBS=ON 
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find benchmark (missing: benchmark_DIR)
CMake Error at cmake/civetweb-3rdparty-config.cmake:6 (message):
  File or directory
  /home/adrian/prometheus-cpp-0.7.0/3rdparty/civetweb/include referenced by
  variable CIVETWEB_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  cmake/civetweb-3rdparty-config.cmake:10 (set_and_check)
  pull/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/adrian/prometheus-cpp-0.7.0/_build/CMakeFiles/CMakeOutput.log".
See also "/home/adrian/prometheus-cpp-0.7.0/_build/CMakeFiles/CMakeError.log".

**Comment by gjasny** [comment]
If you rely on the embedded third party libraries (default, `-DUSE_THIRDPARTY_LIBRARIES=ON`) you need to initialize the git submodules. If you'd like to use your own copy of civetweb and googletest, please pass `-DUSE_THIRDPARTY_LIBRARIES=OFF`.
