### ISSUE TITLE
push gateway issue

### ISSUE THREAD

**Issue by dark-slayer** [jupp0r/prometheus-cpp#277]
in the readme file, under the topic Usage, the main function given is the one to be used in case we want to use the pull method i.e exposer. It runs ok for me, but to implement the push gateway, I guess we need the main function in the sample_client .cc file. When I use that  and open prometheus in the browser, it dosent show any datapoints , so I guess it is not really collecting metrics for my port which I mention in the Gateway structure used in the sample_client.cc. I have obviously added that port in the targets in yml file and changed the ip to mine, but it is showing as down in the browser. I repeat, everything is ok when i use the same yml file but the main function in the usage example for pull method.
The sample client I am using for main is given below-
[sample_client.txt](https://github.com/jupp0r/prometheus-cpp/files/3259831/sample_client.txt)

**Comment by gjasny** [comment]
The push gateway code requires a push gateway. The following works for me:
```
# Start pushgateway
$ docker run -d -p 9091:9091 prom/pushgateway

# Build sample_client
$ ninja sample_client

# Run sample_client
$ push/tests/integration/sample_client 
returnCode is 200
returnCode is 200
returnCode is 200

# open http://localhost:9091/ in browser
# or scrape http://localhost:9091/metrics
```

**Comment by dark-slayer** [comment]
Thanks a lot 😃😁
