### ISSUE TITLE
double guages incorrectly formatted in non-C locales

### ISSUE THREAD

**Issue by mjj29** [jupp0r/prometheus-cpp#281]
The prometheus ToString(double) calls std::to_string which if you're running in a non-english locale and you've called setlocale (which in our case initializing a in-process JVM will do) can format numbers to be: 123,45 rather than 123.45.

For formatting the output of /metrics I think it needs to always be .-format and not locale-dependent, so you need to use a different mechanism (it looks like getting an ostringstream and calling imbue on it to force a C locale is probably simplest)

To demonstrate outside of prometheus use:

```c++
#include <string>
#include <iostream>

int main( int, char** )
{
   std::locale::global(std::locale(""));
   double d = 123.45;
   std::cout << std::to_string(d) << std::endl;
}
```

To demonstrate with prometheus-cpp just call std::locale::global(std::locale(""));

Unfortunately leaving the global locale set to C isn't an option because loading a JVM with the invocation API in the same process seems to do that.

**Comment by gjasny** [comment]
Hi,

thanks for the report. I added an naive fix as well as a test. Will refine it later.

Thanks,
Gregor

**Comment by capone212** [comment]
I can confirm that after the  problem is gone. Thanks
