### ISSUE TITLE
Shared libs under Windows

### ISSUE THREAD

**Issue by david-antiteum** [jupp0r/prometheus-cpp#288]
Can you please export symbols when build shared libs? Under Window no symbol is exported, only the core DLL is created but not the LIB and the compilation for push and pull libs fails.

Thanks !

**Comment by gjasny** [comment]
I'm not too familiar how to interact with DLL interfaces, STL and templates. Could you please take a look at the `symbol-visibility` branch and make it compile properly?

**Comment by david-antiteum** [comment]
I have no time at this moment but this will help with core:
core -> CMakeLists.txt:
```
if( BUILD_SHARED_LIBS )
	add_compile_definitions( PROMETHEUS_CPP_CORE_DLL )
	add_compile_definitions( PROMETHEUS_CPP_CORE_EXPORTS )
endif()
```

There is some missing files (*_export.h). This one should do the trick: core/include/prometheus/detail/core_export.h

```
#pragma once

#ifdef PROMETHEUS_CPP_CORE_DLL
	#ifdef WIN32
		#pragma warning(disable:4251)
		#ifdef PROMETHEUS_CPP_CORE_EXPORTS 
			#define PROMETHEUS_CPP_CORE_EXPORT __declspec(dllexport)
		#else
			#define PROMETHEUS_CPP_CORE_EXPORT __declspec(dllimport)
		#endif
	#else
		#ifdef PROMETHEUS_CPP_CORE_EXPORTS
			#define PROMETHEUS_CPP_CORE_EXPORT __attribute__((visibility("default")))
		#else
			#define PROMETHEUS_CPP_CORE_EXPORT
		#endif
	#endif
#else
	#define PROMETHEUS_CPP_CORE_EXPORT
#endif
```

Is a starting point :)

**Comment by gjasny** [comment]
I re-organized the template code and now got something working in the `symbol-visibility` branch. Maybe you could give it a try?

**Comment by gjasny** [comment]
@david-antiteum could you please test v0.8.0 or master. This issue should be solved.

**Comment by david-antiteum** [comment]
I got link errors using v0.8.0. I´m using VS 2017 15.9.17 with this CMake:

`
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON  -DENABLE_TESTING=OFF
`
The errors:

`
   Creating library lib\prometheus-cpp-push.lib and object lib\prometheus-cpp-push.exp
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_global_init referenced in function "public: __cdecl prometheus::Gateway::Gateway(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0Gateway@prometheus@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00AEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@3@00@Z)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_global_cleanup referenced in function "public: __cdecl prometheus::Gateway::~Gateway(void)" (??1Gateway@prometheus@@QEAA@XZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_slist_append referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_slist_free_all referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_easy_init referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_easy_setopt referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_easy_perform referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_easy_cleanup referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
gateway.cc.obj : error LNK2019: unresolved external symbol __imp_curl_easy_getinfo referenced in function "public: int __cdecl prometheus::Gateway::Delete(void)" (?Delete@Gateway@prometheus@@QEAAHXZ)
bin\prometheus-cpp-push.dll : fatal error LNK1120: 9 unresolved externals
`
I hope that this helps.

**Comment by gjasny** [comment]
Because only `curl` related symbols are missing I'd guess it's a problem with your curl setup.

Compilation and test worked for me with the following configure line:

```
cmake .. -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF
```

I see many C4251 warnings originating from the C++ STL classes.

**Comment by david-antiteum** [comment]
And you are right :) Sorry to misread the errors. Fixing my curl version solves the issue. Thanks a lot!
