### ISSUE TITLE
Push errors are silently ignored

### ISSUE THREAD

**Issue by rb587** [jupp0r/prometheus-cpp#289]
When pushing using the Gateway class, errors such as using unknown hostnames, or specifying a target URL where no gateway listens, are silently ignored, and Gatway::push() returns ok.

This is due to Gateway::push() hiding any error codes <400, which also includes the general curl errors mapped to negative numbers.

Is this on purpose, or is it ok to fix it to at least `if (status_code >= 400 || status_code < 0)`?

(BTW: For Delete(), no such error hiding is performed)

**Comment by gjasny** [comment]
Which version are you looking at? The current code handles error codes similar as you suggest:

https://github.com/jupp0r/prometheus-cpp/blob/d83dd68e496e024ae0f1f0c19ac2ab0d27330330/push/src/gateway.cc#L180

**Comment by rb587** [comment]
Sorry - I had 0.6.0 checked out, and failed to check for later fixes...

Thanks!

(Even though it is still interesting for me that for Delete there is no similar mapping, and that e.g. 3xx are considered success for push()?)
