### ISSUE TITLE
Add support for LTO

### ISSUE THREAD

**Issue by zerodefect** [jupp0r/prometheus-cpp#292]
In my wholly unscientific(!) testing, I'm noticing some nice performance gains when hacking the CMakeLists.txt to support compiler LTO when used in conjunction with gcc v8.2.

I see from this [post](https://stackoverflow.com/questions/31355692/cmake-support-for-gccs-link-time-optimization-lto) on StackOverflow, that CMake doesn't support the `check_ipo_supported()` function until CMake 3.9.

Without this native CMake support, could we consider adding a CMake option to enable LTO (by manually adding the -flto switch)?

**Comment by zerodefect** [comment]
For the record, I was testing core only.

**Comment by gjasny** [comment]
Hello,

I'd rather suggest to either update your CMake installation to benefit from the built-in IPO code.
Or inject the necessary variables via the `CFLAGS`, CXXFLAGS`, and `LDFLAGS` environment variables.

Thanks,
Gregor

**Comment by zerodefect** [comment]
Ok. Thanks.
