### ISSUE TITLE
Functionality to reset a counter

### ISSUE THREAD

**Issue by usey11** [jupp0r/prometheus-cpp#299]
The counter metric should be able to be reset. Is there any plans to add this functionality to the counter?

**Comment by jupp0r** [comment]
What makes you think that it "should be able to reset"?  From the prometheus docs:

> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero **on restart.** 

(my emphasis)

Neither the Go nor the Java client implementations allow you to reset the counter manually. What use case do you have for it?

**Comment by usey11** [comment]
I am creating a system that monitors a number of FPGA's and would like to expose the number of times an FPGA performs a task. The FPGA's can be restarted whilst the monitoring system stays online so it would be useful to reset the counter to 0 when the FPGA is restarted.

**Comment by bdangit** [comment]
You should use a gauge which can go up and down. You would also be able to set it to any value you want.

**Comment by usey11** [comment]
That's what I will do but I feel like a reset isn't simple a value going down, it's a reset to zero which a counter supports from the prometheus definition of a counter.

> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be **reset to zero on restart**.

**Comment by jupp0r** [comment]
Restart in prometheus refers to the restart of the monitoring system, which normally is the same as the monitored system. Can you reset the monitoring system on restart (either kill the process or restart the `Exposer`).

**Comment by usey11** [comment]
Okay, thanks for the help.
