### ISSUE TITLE
Git submodule issue with CivetWeb

### ISSUE THREAD

**Issue by GuillaumeDua** [jupp0r/prometheus-cpp#321]
When compiling https://github.com/jupp0r/prometheus-cpp using CMake :
> Unable to checkout 'ce8f6d38a60eb16c996afee1e5340f76ef4d0923' in submodule path '3rdparty/civetweb'

> CMake Error at <my_project>/Prometheus_cpp_external-prefix/tmp/Prometheus_cpp_external-gitclone.cmake:52 (message):
>  Failed to update submodules in:
>  '<my_project>/Prometheus_cpp_external-prefix/src/Prometheus_cpp_external'

**Comment by hhoffstaette** [comment]
Works for me..maybe a temporary Github hiccup?
```
$git clone git@github.com:jupp0r/prometheus-cpp.git
Cloning into 'prometheus-cpp'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 3002 (delta 27), reused 31 (delta 12), pack-reused 2938
Receiving objects: 100% (3002/3002), 648.12 KiB | 2.15 MiB/s, done.
Resolving deltas: 100% (1837/1837), done.
$cd prometheus-cpp 
$git submodule init 
Submodule 'civetweb' (https://github.com/civetweb/civetweb.git) registered for path '3rdparty/civetweb'
Submodule 'googletest' (https://github.com/google/googletest.git) registered for path '3rdparty/googletest'
$git submodule update 
Cloning into '/tmp/prometheus-cpp/3rdparty/civetweb'...
Cloning into '/tmp/prometheus-cpp/3rdparty/googletest'...
Submodule path '3rdparty/civetweb': checked out 'ce8f6d38a60eb16c996afee1e5340f76ef4d0923'
Submodule path '3rdparty/googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'
$mkdir build && cd build && cmake .. && make -j8
<bla bla>
Scanning dependencies of target core
[  2%] Building CXX object core/CMakeFiles/core.dir/src/check_names.cc.o
[  4%] Building CXX object core/CMakeFiles/core.dir/src/counter.cc.o
...etc..
```

**Comment by GuillaumeDua** [comment]
Thanks for your feedback.

Actually, it does build. But the process has errors, which prevent CMake to go on other steps in parent project.

> $ git clone https://github.com/jupp0r/prometheus-cpp.git ; cd prometheus-cpp ; git submodule init ; git submodule update; mkdir build && cd build && cmake .. && make -j8
> Cloning into 'prometheus-cpp'...
> remote: Enumerating objects: 64, done.
> remote: Counting objects: 100% (64/64), done.
> remote: Compressing objects: 100% (52/52), done.
> remote: Total 3002 (delta 27), reused 31 (delta 12), pack-reused 2938
> Receiving objects: 100% (3002/3002), 648.12 KiB | 2.25 MiB/s, done.
> Resolving deltas: 100% (1837/1837), done.
> Submodule 'civetweb' (https://github.com/civetweb/civetweb.git) registered for path '3rdparty/civetweb'
> Submodule 'googletest' (https://github.com/google/googletest.git) registered for path '3rdparty/googletest'
> Cloning into '/mnt/c/DEV/repos/rulesengine/src/REST_server/TMP/prometheus-cpp/3rdparty/civetweb'...
> Cloning into '/mnt/c/DEV/repos/rulesengine/src/REST_server/TMP/prometheus-cpp/3rdparty/googletest'...
> **error: unable to create file test/windows.cgi.cmd: File exists**
> **error: unable to create file test/windows_fail.cgi.cmd: File exists**
> **error: unable to create file test/windows_fail_silent.cgi.cmd: File exists**
> Submodule path '3rdparty/googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'
> **Unable to checkout 'ce8f6d38a60eb16c996afee1e5340f76ef4d0923' in submodule path '3rdparty/civetweb'**
> -- The C compiler identification is GNU 7.4.0
> <loads of stuffs here ...>
> [ 95%] Linking CXX executable ../../../bin/sample_server
> [ 95%] Built target sample_server
> [ 97%] Linking CXX executable ../../../bin/sample_client
> [100%] Linking CXX executable ../../bin/prometheus_test
> [100%] Built target sample_client
> [100%] Built target prometheus_test

As mentioned before, errors stop the parent process.

So for instance, if I use CMake `ExternalProject_Add` :

> ExternalProject_Add(Prometheus_cpp_external
>     GIT_REPOSITORY "https://github.com/jupp0r/prometheus-cpp.git"
>     GIT_TAG         master
>     CMAKE_ARGS  "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}"
>                 "-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}"
>                 "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
>                 "-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}"
>                 "-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}"
>                 "-DCMAKE_AR=${CMAKE_AR}"
>                 "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
>                 "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
>                 "-DCMAKE_RC_COMPILER=${CMAKE_RC_COMPILER}"
>                 "-DCMAKE_COMPILER_PREFIX=${CMAKE_COMPILER_PREFIX}"
>                 "-DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}"
> 
>                 "-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/3rd_party/Prometheus-cpp"
>                 "-DBUILD_TESTS=OFF"
>                 "-DENABLE_TESTING=OFF"
>                 "-DBUILD_SHARED_LIBS=ON" #OFF for static lib
>                 "-DUSE_THIRDPARTY_LIBRARIES=OFF"
> )

The project CMake process stops after the first error :

Scanning dependencies of target Prometheus_cpp_external
[  5%] Creating directories for 'Prometheus_cpp_external'
[ 11%] Performing download step (git clone) for 'Prometheus_cpp_external'
Cloning into 'Prometheus_cpp_external'...
Already on 'master'
Your branch is up to date with 'origin/master'.
Submodule 'civetweb' (https://github.com/civetweb/civetweb.git) registered for path '3rdparty/civetweb'
Submodule 'googletest' (https://github.com/google/googletest.git) registered for path '3rdparty/googletest'
Cloning into '<my_project>/Prometheus_cpp_external-prefix/src/Prometheus_cpp_external/3rdparty/civetweb'...
Cloning into '<my_project>Prometheus_cpp_external-prefix/src/Prometheus_cpp_external/3rdparty/googletest'...
error: unable to create file test/windows.cgi.cmd: File exists
error: unable to create file test/windows_fail.cgi.cmd: File exists
error: unable to create file test/windows_fail_silent.cgi.cmd: File exists
Submodule path '3rdparty/googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'
Unable to checkout 'ce8f6d38a60eb16c996afee1e5340f76ef4d0923' in submodule path '3rdparty/civetweb'
CMake Error at <my_project>/Prometheus_cpp_external-prefix/tmp/Prometheus_cpp_external-gitclone.cmake:52 (message):
  Failed to update submodules in:
  '<my_project>/Prometheus_cpp_external-prefix/src/Prometheus_cpp_external'


CMakeFiles/Prometheus_cpp_external.dir/build.make:90: recipe for target 'Prometheus_cpp_external-prefix/src/Prometheus_cpp_external-stamp/Prometheus_cpp_external-download' failed
make[2]: *** [Prometheus_cpp_external-prefix/src/Prometheus_cpp_external-stamp/Prometheus_cpp_external-download] Error 1
CMakeFiles/Makefile2:134: recipe for target 'CMakeFiles/Prometheus_cpp_external.dir/all' failed
make[1]: *** [CMakeFiles/Prometheus_cpp_external.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any further idea ?

**Comment by GuillaumeDua** [comment]
Looks like the issue is only related to **CivetWeb**, even from scratch.
Only append in the computer, not on others.

> $ git clone https://github.com/civetweb/civetweb.git
> Cloning into 'civetweb'...
> remote: Enumerating objects: 95, done.
> remote: Counting objects: 100% (95/95), done.
> remote: Compressing objects: 100% (69/69), done.
> remote: Total 21218 (delta 50), reused 49 (delta 26), pack-reused 21123
> Receiving objects: 100% (21218/21218), 24.60 MiB | 9.63 MiB/s, done.
> Resolving deltas: 100% (13599/13599), done.
> error: unable to create file test/windows.cgi.cmd: File exists
> error: unable to create file test/windows_fail.cgi.cmd: File exists
> error: unable to create file test/windows_fail_silent.cgi.cmd: File exists
> Checking out files: 100% (1251/1251), done.
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'

**Comment by GuillaumeDua** [comment]
Looks like the issue is related to **WSL**.
https://github.com/civetweb/civetweb/issues/809
