### ISSUE TITLE
Question for Family labels

### ISSUE THREAD

**Issue by goudan-er** [jupp0r/prometheus-cpp#327]
What the meaning of Family labels(const labels)? Is it necessary? Any use cases?

**Comment by bigc2000** [comment]
Yeah, same to me. for conviency when adding metric? does it make the design confused and complicated?

**Comment by gjasny** [comment]
Hello and sorry for the late reply.

The documentation states:
> Assign a set of key-value pairs (= labels) to the metric. All these labels are propagated to each time series within the metric.

It means that all the labels you specify there are always added regardless of the labels that the `Family::Add` function adds.

Usually this is used to add something like a server instance identifier which never changes during the lifetime of the process and is thus: constant.

Thanks,
Gregor
