### ISSUE TITLE
Support for Https & client certs

### ISSUE THREAD

**Issue by mtottenh** [jupp0r/prometheus-cpp#329]
The underlying web framework Civetweb supports HTTPS and client authentication using openssl, the pull framework should expose a mechanism to setup these features.

**Comment by jupp0r** [comment]
I completely agree this is a missing feature.

**Comment by gjasny** [comment]
Hello,

I started implementing the necessary pieces to configure https and client certs. But I guess I need your help.

First you need to enable SSL support in civetweb. If you use the embedded thirdparty copy add `-DTHIRDPARTY_CIVETWEB_WITH_SSL=ON` to the CMake options. If you use a locally built one, enable SSL support there (a [patch](https://github.com/microsoft/vcpkg/pull/10431) for vcpkg is pending).

For the Exposer I added a second ctro which exposes the civetweb configuration vector. There you might need code like this:

```c++
  const auto civetConfig = std::vector<std::string>{
          "listening_ports", "8443s",
          "ssl_certificate", "/path/to/ssl_cert.pem",
          "ssl_ca_file", "/path/to/calist.pem",
          "ssl_verify_peer", "yes",
          "num_threads", "2",
  };
  Exposer exposer{civetConfig, "/metrics"};
```

Please refer to [OpenSSL](https://github.com/civetweb/civetweb/blob/master/docs/OpenSSL.md) and 
[UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md) for the configuration parameters.

With the parameters above I was able to set up HTTPS and made the browser prompting for a client certificate. I fear I'm short on time to look into generating a client certificate. That's where I need your help. Could you please test if the branch fits your needs?

Thanks,
Gregor
