### ISSUE TITLE
Test cases fail on centos 7.2 gcc 8.31 in docker container

### ISSUE THREAD

**Issue by marcpawl** [jupp0r/prometheus-cpp#330]
Create docker container based on centos 7.2
In container install devtoolset-8, cmake3

Makefile:
all: build_rhel72_64

src:
        git clone -b v0.8.0 http://github.com/jupp0r/prometheus-cpp.git src
        cd src && git submodule init && git submodule update

build_rhel72_64: src
        (docker exec rhel72_64 make -C `pwd` rhel72_64) || (rm -rf build/rhel72_64 && false)

rhel72_64:
        mkdir -p build/rhel72_64
        source /opt/rh/devtoolset-8/enable && \
          cd build/rhel72_64 && \
          cmake3 \
             -Dbenchmark_DIR=$(abspath ../../google-benchmark/rhel72_64/usr/local/lib64/cmake/benchmark/) \
             -G "Unix Makefiles" \
             ../../src
        source /opt/rh/devtoolset-8/enable && \
          ${MAKE} -C build/rhel72_64 
        source /opt/rh/devtoolset-8/enable && \
          ${MAKE} -C build/rhel72_64 test
        source /opt/rh/devtoolset-8/enable && \
          ${MAKE} -C build/rhel72_64 DESTDIR=$(abspath rhel72_64) install

The tests fail:
make[1]: Entering directory '/home/mpawlowsky/r18_1_0_dcr/nb20200108.9999/all_3rdparty_NB/prometheus/prometheus-cpp-0.8.0/build/rhel72_64'
Running tests...
Test project /home/mpawlowsky/r18_1_0_dcr/nb20200108.9999/all_3rdparty_NB/prometheus/prometheus-cpp-0.8.0/build/rhel72_64
    Start 1: prometheus_test
1/1 Test #1: prometheus_test ..................***Failed   22.20 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  22.20 sec

The following tests FAILED:
	  1 - prometheus_test (Failed)
Errors while running CTest
make[1]: *** [Makefile:130: test] Error 8

**Comment by gjasny** [comment]
Could you please run crest with -V or run the test directly to see the output?
My bet would be the serialization test fails because your docker image lacks the de_DE locale.

**Comment by marcpawl** [comment]
Failing test case is:

1: [ RUN      ] SerializerTest.shouldSerializeLocaleIndependent
1: unknown file: Failure
1: C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in the test body.
1: [  FAILED  ] SerializerTest.shouldSerializeLocaleIndependent (68 ms)

**Comment by gjasny** [comment]
The problem with tests that automatically skip is that you can never be sure that they don't skip in CI.
If that's a problem in your setup maybe filtering the test with the [GTEST_FILTER](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#running-a-subset-of-the-tests)  environment  variable would help.
