### ISSUE TITLE
No cmake package generation for libprometheus-cpp

### ISSUE THREAD

**Issue by sbates130272** [jupp0r/prometheus-cpp#339]
The CmakeLists.txt for prometheus-cpp does not include a Cpack step to allow for the generation of .deb/.rpm or other packages supported via cpack generators. This makes it harder to distribute packages that depend on libprometheus-cpp-*.

Add support for Cpack in the Cmake framework for prometheus-cpp.

**Comment by gjasny** [comment]
Thanks for the suggestion and the example. I'll add those to the repo. One change I made is leaving the `CPACK_GENERATOR` at the default value and expect the user to override it.

**Comment by sbates130272** [comment]
Thanks @gjasny for applying this before I could even submit a PR! One issue I see is that the version number in the package name does not seem to align with what is set in the project() cmake definition. I'll file a new issue for that.
