### ISSUE TITLE
Initialize and display custom counter metrics when exporter is deployed

### ISSUE THREAD

**Issue by josrolgil** [jupp0r/prometheus-cpp#355]
Hello, I can not see my custom metrics before the first request arrives and the counter value is 1. 
Can I write and initialize the metric just as:
my_metric 0 ??
Instead of 
my_metric 1

**Comment by gjasny** [comment]
The following code:
```c++
  auto& packet_counter = BuildCounter()
                             .Name("observed_packets_total")
                             .Help("Number of observed packets")
                             .Register(*registry);
  auto& instance = packet_counter.Add({});
```

results in:
```
# HELP observed_packets_total Number of observed packets
# TYPE observed_packets_total counter
observed_packets_total 0
```

I'm unsure what you mean with custom? Maybe an own implementation of `Collectable`? The following code works for me as well:
```c++
struct Foo : public prometheus::Collectable
{
  std::vector<prometheus::MetricFamily> Collect() const override {
    std::vector<prometheus::MetricFamily> collected(1);

    auto& family = collected.front();
    family.name = "custom";
    family.help = "A custom family";
    family.type = prometheus::MetricType::Counter;
    family.metric.resize(1);

    return collected;
  }
};

//...

  auto foo = std::make_shared<Foo>();
  exposer.RegisterCollectable(foo);
```

and results in:
```
# HELP custom A custom family
# TYPE custom counter
custom 0
```

**Comment by daijiaqi123** [comment]
hello，I followed the example provided by you, but the expected result was not obtained. The REST interface did not return any result.

Would you please write out the complete sample?

**Comment by daijiaqi123** [comment]
> The following code:
> 
> ```c++
>   auto& packet_counter = BuildCounter()
>                              .Name("observed_packets_total")
>                              .Help("Number of observed packets")
>                              .Register(*registry);
>   auto& instance = packet_counter.Add({});
> ```
> 
> results in:
> 
> ```
> # HELP observed_packets_total Number of observed packets
> # TYPE observed_packets_total counter
> observed_packets_total 0
> ```
> 
> I'm unsure what you mean with custom? Maybe an own implementation of `Collectable`? The following code works for me as well:
> 
> ```c++
> struct Foo : public prometheus::Collectable
> {
>   std::vector<prometheus::MetricFamily> Collect() const override {
>     std::vector<prometheus::MetricFamily> collected(1);
> 
>     auto& family = collected.front();
>     family.name = "custom";
>     family.help = "A custom family";
>     family.type = prometheus::MetricType::Counter;
>     family.metric.resize(1);
> 
>     return collected;
>   }
> };
> 
> //...
> 
>   auto foo = std::make_shared<Foo>();
>   exposer.RegisterCollectable(foo);
> ```
> 
> and results in:
> 
> ```
> # HELP custom A custom family
> # TYPE custom counter
> custom 0
> ```

hello，I followed the example provided by you, but the expected result was not obtained. The REST interface did not return any result.

Would you please write out the complete sample?
