### ISSUE TITLE
Is that necessary to add a function for GaugePtr to known whether Metric was collected

### ISSUE THREAD

**Issue by laoshanxi** [jupp0r/prometheus-cpp#357]
In some case, Set a Gauge value have will cost too much compute work and if the metric was not scraped, it is not necessary to set too frequency, so I am thinking is that necessary to add a function for GaugePtr to known whether Metric was collected, such as 
`
bool prometheus::Gauge::collected()
`

**Comment by epkugelmass** [comment]
Perhaps it makes sense to support a Gauge value callback instead. [Go](https://github.com/prometheus/client_golang/blob/master/prometheus/gauge.go#L264), [Java](https://prometheus.github.io/client_java/io/prometheus/client/SimpleCollector.html#setChild(Child,java.lang.String...)), and [Python](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L383) all support this.

**Comment by jdx-john** [comment]
I was just looking for this exact feature. I hadn't realised other client-libs support callbacks but it makes perfect sense especially in the context of exporters and similar.

**Comment by laoshanxi** [comment]
callback may introduce much complex for C++, expecially when the metric was add/release dynamiclly. not sure whether this direction is possible :  

for the metric set function, just make simple and do less work, but do more calculate work in Collect() function.

like Increment() and Decrement(), do not sync the two actions when set the metric, just calculate the metric value when scrap was triggered.

**Comment by gjasny** [comment]
This is duplicated by #527. I'm closing this issue in favour if the other one.
