### ISSUE TITLE
CMake build with optimizations

### ISSUE THREAD

**Issue by bruno-kakele** [jupp0r/prometheus-cpp#358]
Hi,

Is there a way to provide custom flags when building Prometheus with CMake and make?

I would like to use the -O2 flag and to also define NDEBUG when compiling, but I can't find a straightforward way without making modifications to the current setup.

Thanks in advance

**Comment by gjasny** [comment]
Hello,

first you have the four CMake built-in configurations which could be chosen by setting [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html).

In addition you could inject C/CXX flags by setting [CXXFLAGS](https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html) or [CFLAGS](https://cmake.org/cmake/help/latest/envvar/CFLAGS.html) environment variables.

Is that what you need?

Thanks,
Gregor

**Comment by bruno-kakele** [comment]
Thanks, for some reason I thought the build type wasn't working, but I had a typo in it :(

**Comment by EZ-Phantom** [comment]
If someone can post an example with makefile to build proj with prometheus I will be very happy
