### ISSUE TITLE
Flags for prometheus in Makefile

### ISSUE THREAD

**Issue by EZ-Phantom** [jupp0r/prometheus-cpp#359]
After looking through close issues I have found this flags: 
`-lprometheus-cpp-pull -lprometheus-cpp-core -lz`

But I wish to know how exactly did you find these ones? I mean there is no any instruction about how to add correct flags to Makefile or how to create correct Cmakefile for project which uses prometheus-cpp.

I understand it seems like an offtopic, but will appreciate any guides and answers, thx.

**Comment by gjasny** [comment]
If you use CMake for your project there's an example how to import and use prometheus-cpp: 
[cmake/project-import/CMakeLists.txt](https://github.com/jupp0r/prometheus-cpp/blob/30326ebf917815913246814a5875f5705e0a0da6/cmake/project-import/CMakeLists.txt)

If you use a plain Makefile you should know what you're doing:

`prometheus-cpp-pull` depends on `prometheus-cpp-core` and the `z` (zlib) library. Therefore the order on the link line to please single-pass-linkers is:
```
-lprometheus-cpp-pull -lprometheus-cpp-core -lz
```

(See for example [this](https://stackoverflow.com/a/21854528) StackOverflow post): 
> So, you can see that in order to be sure everything is found in a single pass, the things that NEED symbols from libraries must come before the libraries that provide those symbols, or else when the linker hits the library in its single pass it won't know that the libraries are needed and will skip them.

**Comment by EZ-Phantom** [comment]
First of all thx for your answer @gjasny and the thing about linker was nice as well.
I will try to explain more clearly what I am looking for and will be glad if you can answer on this question too.

I have found prometheus, I wish to use it in my project. I have found this repo for prometheus-cpp lib, nice! But the main thing that I couldn't find any info about this flags `-lprometheus-cpp-pull -lprometheus-cpp-core -lz`

I mean I can not find this information in README.md and it is a problem for me. For example can you help me to realize how can I explore what kind of flags should I add to my makefile. If there any instruments or possible ways of understanding how should I find these flags if I only have source code and build guide.

It is not a reproach, but a try to understand a little bit more, thx!
