### ISSUE TITLE
Compiling prometheus client example

### ISSUE THREAD

**Issue by adam-abed-abud** [jupp0r/prometheus-cpp#360]
Hi! I created an RPM package with static libraries for Centos 7 and I'm trying to compile the client example. Unfortunately, I get the following errors: 

[root@adam-dev2 user]# g++ --std=c++11 prometheus.cpp 
/tmp/ccHTO3sF.o: In function `main':
prometheus.cpp:(.text+0x131): undefined reference to `prometheus::Exposer::Exposer(std::string const&, std::string const&, unsigned long)'
prometheus.cpp:(.text+0x18b): undefined reference to `prometheus::BuildCounter()'
prometheus.cpp:(.text+0x1ce): undefined reference to `prometheus::detail::Builder<prometheus::Counter>::Name(std::string const&)'
prometheus.cpp:(.text+0x20d): undefined reference to `prometheus::detail::Builder<prometheus::Counter>::Help(std::string const&)'
prometheus.cpp:(.text+0x294): undefined reference to `prometheus::detail::Builder<prometheus::Counter>::Labels(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
prometheus.cpp:(.text+0x2b1): undefined reference to `prometheus::detail::Builder<prometheus::Counter>::Register(prometheus::Registry&)'
prometheus.cpp:(.text+0x447): undefined reference to `prometheus::Exposer::RegisterCollectable(std::weak_ptr<prometheus::Collectable> const&)'
prometheus.cpp:(.text+0x485): undefined reference to `prometheus::Counter::Increment()'
prometheus.cpp:(.text+0x614): undefined reference to `prometheus::Exposer::~Exposer()'
/tmp/ccHTO3sF.o: In function `prometheus::Counter& prometheus::Family<prometheus::Counter>::Add<>(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)':
prometheus.cpp:(.text._ZN10prometheus6FamilyINS_7CounterEE3AddIJEEERS1_RKSt3mapISsSsSt4lessISsESaISt4pairIKSsSsEEEDpOT_[_ZN10prometheus6FamilyINS_7CounterEE3AddIJEEERS1_RKSt3mapISsSsSt4lessISsESaISt4pairIKSsSsEEEDpOT_]+0x30): undefined reference to `prometheus::Family<prometheus::Counter>::Add(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> >)'
/tmp/ccHTO3sF.o: In function `prometheus::Counter::Counter()':
prometheus.cpp:(.text._ZN10prometheus7CounterC2Ev[_ZN10prometheus7CounterC5Ev]+0x18): undefined reference to `prometheus::Gauge::Gauge(double)'
/tmp/ccHTO3sF.o: In function `void __gnu_cxx::new_allocator<prometheus::Registry>::construct<prometheus::Registry>(prometheus::Registry*)':
prometheus.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN10prometheus8RegistryEE9constructIS2_JEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN10prometheus8RegistryEE9constructIS2_JEEEvPT_DpOT0_]+0x32): undefined reference to `prometheus::Registry::Registry(prometheus::Registry::InsertBehavior)'
collect2: error: ld returned 1 exit status

Can you please help me out? 

More info:
OS: Centos 7 
GCC: 8.3.1

**Comment by gjasny** [comment]
I'd recommend that you use CMake instead of plain make. Please see #359.

**Comment by adam-abed-abud** [comment]
I did run cmake following instructions for building the project via CMake. 
I'm using cmake3 version 3.14.7

**Comment by gjasny** [comment]
You get those errors because you don't link against the prometheus-cpp libraries. The relevant CMake snippet is:

```cmake
find_package(prometheus-cpp CONFIG REQUIRED)
target_link_libraries(yourtarget PRIVATE prometheus-cpp::pull)
```

**Comment by adam-abed-abud** [comment]
Thank for your reply @gjasny !  

I created a new directory with the following CMakeLists file and the example code from the prometheus-cpp repository.

cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(prometheus-cpp-example)
set(CMAKE_CXX_STANDARD 11)
find_package(prometheus-cpp CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example PRIVATE prometheus-cpp::pull)


Unfortunately the cmake fails: 

CMake Error at /lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake:11 (message):
  File or directory //include referenced by variable
  prometheus-cpp_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake:18 (set_and_check)
  CMakeLists.txt:7 (find_package)

**Comment by gjasny** [comment]
How did you create your RPM? It looks like the header files in `/include` are missing.
You could use CPack to create an RPM: https://github.com/jupp0r/prometheus-cpp#packaging

I tested it and it worked without problems.

Content of my RPM: `rpm -ql prometheus-cpp`
```
/usr/include/prometheus
/usr/include/prometheus/check_names.h
/usr/include/prometheus/client_metric.h
/usr/include/prometheus/collectable.h
/usr/include/prometheus/counter.h
/usr/include/prometheus/detail
/usr/include/prometheus/detail/builder.h
/usr/include/prometheus/detail/ckms_quantiles.h
/usr/include/prometheus/detail/core_export.h
/usr/include/prometheus/detail/future_std.h
/usr/include/prometheus/detail/pull_export.h
/usr/include/prometheus/detail/push_export.h
/usr/include/prometheus/detail/time_window_quantiles.h
/usr/include/prometheus/detail/utils.h
/usr/include/prometheus/exposer.h
/usr/include/prometheus/family.h
/usr/include/prometheus/gateway.h
/usr/include/prometheus/gauge.h
/usr/include/prometheus/histogram.h
/usr/include/prometheus/metric_family.h
/usr/include/prometheus/metric_type.h
/usr/include/prometheus/registry.h
/usr/include/prometheus/serializer.h
/usr/include/prometheus/summary.h
/usr/include/prometheus/text_serializer.h
/usr/lib64/cmake
/usr/lib64/cmake/prometheus-cpp
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-targets-noconfig.cmake
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-targets.cmake
/usr/lib64/libprometheus-cpp-core.a
/usr/lib64/libprometheus-cpp-pull.a
/usr/lib64/libprometheus-cpp-push.a
```

**Comment by adam-abed-abud** [comment]
Hi! 

I just built the project and the RPM again following exactly the instructions from: https://github.com/jupp0r/prometheus-cpp#packaging

Commands executed:
git submodule update --init
/usr/local/bin/cmake -B _build -DCPACK_GENERATOR=RPM -DBUILD_SHARED_LIBS=ON
/usr/local/bin/cmake --build _build --target package --parallel


$ rpm -ql prometheus-cpp-0.9.0-1 
/usr/include/prometheus
/usr/include/prometheus/check_names.h
/usr/include/prometheus/client_metric.h
/usr/include/prometheus/collectable.h
/usr/include/prometheus/counter.h
/usr/include/prometheus/detail
/usr/include/prometheus/detail/builder.h
/usr/include/prometheus/detail/ckms_quantiles.h
/usr/include/prometheus/detail/core_export.h
/usr/include/prometheus/detail/future_std.h
/usr/include/prometheus/detail/pull_export.h
/usr/include/prometheus/detail/push_export.h
/usr/include/prometheus/detail/time_window_quantiles.h
/usr/include/prometheus/detail/utils.h
/usr/include/prometheus/exposer.h
/usr/include/prometheus/family.h
/usr/include/prometheus/gateway.h
/usr/include/prometheus/gauge.h
/usr/include/prometheus/histogram.h
/usr/include/prometheus/metric_family.h
/usr/include/prometheus/metric_type.h
/usr/include/prometheus/registry.h
/usr/include/prometheus/serializer.h
/usr/include/prometheus/summary.h
/usr/include/prometheus/text_serializer.h
/usr/lib64/cmake
/usr/lib64/cmake/prometheus-cpp
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-targets-noconfig.cmake
/usr/lib64/cmake/prometheus-cpp/prometheus-cpp-targets.cmake
/usr/lib64/libprometheus-cpp-core.so
/usr/lib64/libprometheus-cpp-core.so.0.9
/usr/lib64/libprometheus-cpp-core.so.0.9.0
/usr/lib64/libprometheus-cpp-pull.so
/usr/lib64/libprometheus-cpp-pull.so.0.9
/usr/lib64/libprometheus-cpp-pull.so.0.9.0
/usr/lib64/libprometheus-cpp-push.so
/usr/lib64/libprometheus-cpp-push.so.0.9
/usr/lib64/libprometheus-cpp-push.so.0.9.0

**Comment by gjasny** [comment]
And does it work?

**Comment by adam-abed-abud** [comment]
No it does not work. 

How did you compile the example script? What are your CMake file and the commands that have you used?

**Comment by gjasny** [comment]
Coud you please paste the output of your CMake configure run?

**Comment by adam-abed-abud** [comment]
Here is the error from the CMake run:

CMake Error at /lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake:11 (message):
  File or directory //include referenced by variable
  prometheus-cpp_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake:18 (set_and_check)
  CMakeLists.txt:7 (find_package)

**Comment by gjasny** [comment]
I'm wondering why it prints `/lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake`

Does this file exist in your setup? Is `/lib64` a symlink to `/usr/lib64`?

**Comment by adam-abed-abud** [comment]
Yes it is a symlink to /usr/lib64

**Comment by gjasny** [comment]
Is this a CERN-internal modification? Then you also need a symlink from `/include` to `/usr/include` Or you need to work on the CMake lookup order so that `/usr/lib64` comes before `/lib64`.

Or you could hint CMake where prometheus-cpp is installed by passing `-Dprometheus-cpp_DIR=/usr/lib64/cmake/prometheus-cpp` when configuring your project.

**Comment by adam-abed-abud** [comment]
Okay, I will have a look at these options. Thanks!

**Comment by gjasny** [comment]
CMake 3.17 gained a `--debug-find` command line option which could help tracking down problems with find-package.

In my `centos:7` docker environment with the cpack-generated prometheus-cpp RPM installed I see the following:

```
  find_package considered the following locations for the Config module:

    /usr/local/prometheus-cppConfig.cmake
    /usr/local/prometheus-cpp-config.cmake
    /usr/prometheus-cppConfig.cmake
    /usr/prometheus-cpp-config.cmake
    /usr/lib64/cmake/prometheus-cpp/prometheus-cppConfig.cmake
    /usr/lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake

  The file was found at

    /usr/lib64/cmake/prometheus-cpp/prometheus-cpp-config.cmake
```

Maybe this helps you to track down the error.

**Comment by adam-abed-abud** [comment]
Indeed this helped a lot! I now can compile the project with the workaround "Dprometheus-cpp_DIR". There was an issue with my machine but it is working now. Thanks a lot!
