### ISSUE TITLE
Undefined reference while linking prometheus-cpp libs to existing codebase

### ISSUE THREAD

**Issue by daggarwal387** [jupp0r/prometheus-cpp#364]
Getting the following errors while linking
`undefined reference to 'prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'`

The g++ command contains reference to -lprometheus-cpp-core -lprometheus-cpp-push -lprometheus-cpp-pull
`ccache g++  -I /software/toolchain2/x86_64-linux/toolchain7-root/usr/extra/vix-disklib/include -Wnon-virtual-dtor -std=c++14 -Werror -D__STDC_FORMAT_MACROS -D_GNU_SOURCE -Wall -fno-omit-frame-pointer -funsigned-char -fPIC -rdynamic -Wno-maybe-uninitialized -mcx16 -fdiagnostics-color=always -Wno-misleading-indentation -g -O2 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free --sysroot /software/toolchain2/x86_64-linux/toolchain7-root -I /software/toolchain2/x86_64-linux/toolchain7-root/usr/include/breakpad/  -Wl,--dynamic-linker,/software/toolchain2/x86_64-linux/toolchain7-root/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/software/toolchain2/x86_64-linux/toolchain7-root/usr/lib -Wl,-rpath,/software/toolchain2/x86_64-linux/toolchain7-root/lib -Wl,-rpath,/software/toolchain2/x86_64-linux/toolchain7/lib64 -Wl,-rpath,/software/toolchain2/x86_64-linux/toolchain7-root/usr/extra/vix-disklib/lib64 -Wl,-rpath,/workspace/main/builds/build-master-qa/sharedlibs -lprometheus-cpp-core -lprometheus-cpp-push -lprometheus-cpp-pull -lglog -lgflags -lprotobuf -lssl -lcrypto -ldl -lz -lsnappy -llz4 -lzstd -latomic -ltcmalloc_and_profiler -lunwind -lcpu_features -lpthread -lboost54_system -lboost54_filesystem -lbreakpad_client`

The gcc and g++ version are:
`gcc (Ubuntu 7.5.0-3ubuntu1~14.04.1) 7.5.0`

nm- C lib/libprometheus-cpp-pull.so gives the following definition of Exposer.
`0000000000022fdc T prometheus::Exposer::Exposer(std::string const&, std::string const&, unsigned long)
00000000000231a0 T prometheus::Exposer::Exposer(std::vector<std::string, std::allocator<std::string> >, std::string const&)
0000000000022fdc T prometheus::Exposer::Exposer(std::string const&, std::string const&, unsigned long)
00000000000231a0 T prometheus::Exposer::Exposer(std::vector<std::string, std::allocator<std::string> >, std::string const&)`

I cannot change how the existing code is built but is there some way in which I can build this library so that I can get Exposer in the desired format.
`Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)`

running the cmake command as follows did not help
`cmake .. -DBUILD_SHARED_LIBS=ON -D_GLIBCXX_USE_CXX11_ABI=1
cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
cmake .. -DBUILD_SHARED_LIBS=ON -DOVERRIDE_CXX_STANDARD_FLAGS=OFF -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'`

**Comment by gjasny** [comment]
It looks like you're using a custom sysroot installed in `/software/toolchain2/x86_64-linux/toolchain7-root`. If you don't set up the prometheus-cpp build with the same flags and the same toolchain it will be incompatible.

For CMake please have a look at the [CMAKE_TOOLCHAIN](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSROOT.html) documentation. Maybe you should ask the one who created the toolchain who to properly compile software for it.

If that is not possible maybe start with a small c++ file with a function taking a `std::string` argument and work from there.

**Comment by daggarwal387** [comment]
Building this with the custom sysroot helped there. Closing this.
