### ISSUE TITLE
Dependency error with symbol 'maybe'

### ISSUE THREAD

**Issue by Jing-Luo** [jupp0r/prometheus-cpp#367]
When i try to bazel build it:

`prometheus-cpp/bazel/repositories.bzl:2:1: file '@bazel_tools//tools/build_defs/repo:utils.bzl' does not contain symbol 'maybe'`

**Comment by gjasny** [comment]
Which Bazel version do you use?

**Comment by Jing-Luo** [comment]
It is 0.23.

**Comment by gjasny** [comment]
Could you use a newer one? I believe the `maybe` function started to appear around 1.0.

**Comment by Jing-Luo** [comment]
I met another issue when I tried to include 
`"@com_github_jupp0r_prometheus_cpp//push",`
in the `deps` section of bazel `BUILD` file, saying 
ERROR: 

> /.cache/bazel/_bazel/0dd8767ed0284c7a6b0c151f6e4a6da6/external/com_github_jupp0r_prometheus_cpp/push/BUILD.bazel:9:1: no such package '@com_github_curl//': The repository could not be resolved and referenced by '@com_github_jupp0r_prometheus_cpp//push:push'
> ERROR: build aborted: no such package '@com_github_curl//': The repository could not be resolved

Is it due to the version issue too?

**Comment by gjasny** [comment]
Please have a look at the branch `bazel-0.23-compatibility`. I will not merge those changes to master because of all the regressions it causes.
