### ISSUE TITLE
Linking error when building with custom GCC

### ISSUE THREAD

**Issue by ramesht77** [jupp0r/prometheus-cpp#368]
In function `prometheus::Serializer::Serializer()':
handler.cc:(.text._ZN10prometheus10SerializerC2Ev[_ZN10prometheus10SerializerC5Ev]+0x9): undefined reference to `vtable for prometheus::Serializer'

In function `prometheus::TextSerializer::TextSerializer()':
handler.cc:(.text._ZN10prometheus14TextSerializerC2Ev[_ZN10prometheus14TextSerializerC5Ev]+0x19): undefined reference to `vtable for prometheus::TextSerializer'

**Comment by gjasny** [comment]
Hello,
a little bit more context would be helpful for me to actually being able to help you.

Please add the following:
* prometheus-cpp version used
* platform you try to compile for (OS, compiler)
* where does this error happen? Do you build prometheus-cpp itself or do you try to consume it?

Please upload the full verbose build log somewhere so that i can see how `handler.cc` is being compiled.

Thanks,
Gregor

**Comment by ramesht77** [comment]
hi,
Thanks for your help on this.
Downloaded latest source code from https://github.com/jupp0r/prometheus-cpp. 
I'm trying to compile prometheus cpp for centos 7.6 using GCC 5.4.
Successfully built: libgmock_main.a, libprometheus-cpp-core.a and libprometheus-cpp-pull, using cmake .. -DENABLE_PUSH=OFF 
Tried to compile the test application but got into below error:

In function `prometheus::detail::GZipCompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
handler.cc:(.text+0x79e): undefined reference to `deflateInit2_'
handler.cc:(.text+0x876): undefined reference to `deflate'
handler.cc:(.text+0x8a6): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
make: *** [exposerLibTest] Error 1

Copied zlib source code to prometheus-cpp-master/3rdparty/zlib, but still seeing error. To overcome this, set the option in CMakeLists.txt ENABLE_COMPRESSION OFF.
Now i'm seeing the above mentioned error.

**Comment by gjasny** [comment]
Thanks for the info. I'll try to reproduce.

**Comment by ramesht77** [comment]
Was able to resolve "prometheus::detail::GZipCompress" error by using -lz option s mentioned in README file.
Now need help to resolve 
prometheus::Serializer::Serializer()': handler.cc:(.text._ZN10prometheus10SerializerC2Ev[_ZN10prometheus10SerializerC5Ev]+0x9): undefined reference to vtable for prometheus::Serializer'

Another question: from the test application code, i'm able to have http server running on the required port. (verified same using netstat command) But using curl command i don't see any metrics. I'm observing below error:
root@vcmfms-74d5ff958f-bq94r:~# curl 172.16.1.123:8081/metrics
curl: (52) Empty reply from server

Please note this test application was running fine with a older rpm and metric values were visible with curl command. Only reason to move latest code, as we wanted prometheus lib built using GCC 5.4 . Please suggest ways to debug this issue.

**Comment by gjasny** [comment]
CentOS 7 seems to ship with GCC 4.8. Where do you got GCC 5.4 from? You probably encounter a symbol mismatch because you're mixing different toolchains.

If I run the `sample_server` that get build with prometheus-cpp I could scrape it like follows:
```
curl -s http://127.0.0.1:8080/metrics | head
# HELP exposer_transferred_bytes_total Transferred bytes to metrics services
# TYPE exposer_transferred_bytes_total counter
exposer_transferred_bytes_total 3539.000000
# HELP exposer_scrapes_total Number of times metrics were scraped
# TYPE exposer_scrapes_total counter
exposer_scrapes_total 4.000000
```

**Comment by ramesht77** [comment]
I'm using the same code base of CentOS 7 which is shipped with GCC 4.8. Our complete code is based on GCC 5.4 , so trying to compile it with GCC 5.4. 

Please suggest any solution as we need to compile it with GCC 5.4 or we need ".so"/".a" files compiled with GCC 5.4.

**Comment by gjasny** [comment]
I'd suggest you approach the C++ expert of you company / team with the issue to get it quickly resolved.

Do you compile prometheus-cpp also with GCC 5.4? Could you please quote the CMake output when creating the Makefiles? Like:
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```
```

**Comment by ramesht77** [comment]
Yes, compiled prometheus-cpp with GCC 5.4

-bash-4.2$ /usr/bin/cmake3 .. -DENABLE_PUSH=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/local/bin/x86_64-unknown-linux-gnu-gcc
-- Check for working C compiler: /usr/local/bin/x86_64-unknown-linux-gnu-gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/x86_64-unknown-linux-gnu-g++
-- Check for working CXX compiler: /usr/local/bin/x86_64-unknown-linux-gnu-g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find benchmark (missing: benchmark_DIR)
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- The following features have been enabled:

 * Pull, support for pulling metrics
 * Compression, support for zlib compression of metrics

-- The following REQUIRED packages have been found:

 * googlemock-3rdparty
 * civetweb-3rdparty
 * ZLIB

-- The following features have been disabled:

 * Push, support for pushing metrics to a push-gateway

-- The following OPTIONAL packages have not been found:

 * benchmark

-- Configuring done
-- Generating done
-- Build files have been written to: /opensource/prometheus-cpp-master/_build

**Comment by ramesht77** [comment]
-bash-4.2$ make
Scanning dependencies of target core
[  2%] Building CXX object core/CMakeFiles/core.dir/src/check_names.cc.o
[  5%] Building CXX object core/CMakeFiles/core.dir/src/counter.cc.o
[  7%] Building CXX object core/CMakeFiles/core.dir/src/detail/builder.cc.o
[ 10%] Building CXX object core/CMakeFiles/core.dir/src/detail/ckms_quantiles.cc.o
[ 12%] Building CXX object core/CMakeFiles/core.dir/src/detail/time_window_quantiles.cc.o
[ 15%] Building CXX object core/CMakeFiles/core.dir/src/detail/utils.cc.o
[ 17%] Building CXX object core/CMakeFiles/core.dir/src/family.cc.o
[ 20%] Building CXX object core/CMakeFiles/core.dir/src/gauge.cc.o
[ 22%] Building CXX object core/CMakeFiles/core.dir/src/histogram.cc.o
[ 25%] Building CXX object core/CMakeFiles/core.dir/src/registry.cc.o
[ 27%] Building CXX object core/CMakeFiles/core.dir/src/serializer.cc.o
[ 30%] Building CXX object core/CMakeFiles/core.dir/src/summary.cc.o
[ 32%] Building CXX object core/CMakeFiles/core.dir/src/text_serializer.cc.o
[ 35%] Linking CXX static library ../lib/libprometheus-cpp-core.a
[ 35%] Built target core
Scanning dependencies of target gmock_main
[ 37%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googletest/src/gtest-all.cc.o
[ 40%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googlemock/src/gmock-all.cc.o
[ 42%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googlemock/src/gmock_main.cc.o
[ 45%] Linking CXX static library lib/libgmock_main.a
[ 45%] Built target gmock_main
Scanning dependencies of target prometheus_core_test
[ 47%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/builder_test.cc.o
[ 50%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/check_names_test.cc.o
[ 52%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/counter_test.cc.o
[ 55%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/family_test.cc.o
[ 57%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/gauge_test.cc.o
[ 60%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/histogram_test.cc.o
[ 62%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/registry_test.cc.o
[ 65%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/serializer_test.cc.o
[ 67%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/summary_test.cc.o
[ 70%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/text_serializer_test.cc.o
[ 72%] Building CXX object core/tests/CMakeFiles/prometheus_core_test.dir/utils_test.cc.o
[ 75%] Linking CXX executable ../../bin/prometheus_core_test
[ 75%] Built target prometheus_core_test
Scanning dependencies of target civetweb
[ 77%] Building CXX object pull/CMakeFiles/civetweb.dir/__/3rdparty/civetweb/src/CivetServer.cpp.o
[ 80%] Building C object pull/CMakeFiles/civetweb.dir/__/3rdparty/civetweb/src/civetweb.c.o
[ 80%] Built target civetweb
Scanning dependencies of target pull
[ 82%] Building CXX object pull/CMakeFiles/pull.dir/src/exposer.cc.o
[ 85%] Building CXX object pull/CMakeFiles/pull.dir/src/handler.cc.o
[ 87%] Building CXX object pull/CMakeFiles/pull.dir/src/metrics_collector.cc.o
[ 90%] Linking CXX static library ../lib/libprometheus-cpp-pull.a
[ 90%] Built target pull
Scanning dependencies of target sample_server
[ 92%] Building CXX object pull/tests/integration/CMakeFiles/sample_server.dir/sample_server.cc.o
[ 95%] Linking CXX executable ../../../bin/sample_server
[ 95%] Built target sample_server
Scanning dependencies of target prometheus_pull_test
[ 97%] Building CXX object pull/tests/unit/CMakeFiles/prometheus_pull_test.dir/exposer_test.cc.o
[100%] Linking CXX executable ../../../bin/prometheus_pull_test
[100%] Built target prometheus_pull_test
-bash-4.2$

**Comment by gjasny** [comment]
Where did you get GCC 5.4 from? Could you post the URL and the instructions to build?

**Comment by ramesht77** [comment]
You need to install GCC 5.4 compiler, (I don't have the rpm details, will share tomorrow)
IN CMakeList.txt set CMAKE_C_COMPILER CMAKE_CXX_COMPILER to location GCC 5 compiler location.
Then follow the build steps capture in the document README document.

**Comment by ramesht77** [comment]
Ran built sample_server binary, but still no data is coming in curl output
root@vcmfms-74d5ff958f-bq94r:~# curl -s http://127.0.0.1:8080/metrics | head
root@vcmfms-74d5ff958f-bq94r:~# curl -s http://127.0.0.1:8080/metrics | head
root@vcmfms-74d5ff958f-bq94r:~# curl -s http://127.0.0.1:8080/metrics | head

Verified counter values are increment using Value function in counter.h. But some how data is not is displayed in curl command. Can you please explain how data is populated into the url location? I will try to debug based on that. And what does Collector function do?

**Comment by ramesht77** [comment]
GCC 5.4 was built from  https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2

**Comment by gjasny** [comment]
I tried to reproduce but was unable to do so:

```Dockerfile
FROM centos:7

RUN yum install -y epel-release

RUN yum install -y cmake3 
RUN yum install -y gcc-c++
RUN yum install -y git
RUN yum install -y libcurl-devel
RUN yum install -y make
RUN yum install -y ninja-build
RUN yum install -y zlib-devel
RUN yum install -y bzip2
RUN yum install -y gmp-devel
RUN yum install -y mpfr-devel
RUN yum install -y libmpc-devel

WORKDIR /root

RUN git clone https://github.com/jupp0r/prometheus-cpp.git
RUN cd prometheus-cpp && git submodule update --init

RUN curl -sLO https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
RUN tar -jxf gcc-5.4.0.tar.bz2

RUN cd gcc-5.4.0 && ./configure --disable-multilib --enable-languages=c,c++
RUN make -C gcc-5.4.0 -j$(nproc)
RUN make -C gcc-5.4.0 install

RUN cmake3 -GNinja -DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ -S prometheus-cpp -B prometheus-cpp/_build

RUN ninja-build -C prometheus-cpp/_build

RUN LD_LIBRARY_PATH=/usr/local/lib64 ninja-build -C prometheus-cpp/_build test
```

Please tweak the Dockerfile until you can reproduce your error. Maybe you used different configuration flags for GCC.

Within the image I'm able to successfully scrape:
```
LD_LIBRARY_PATH=/usr/local/lib64 bin/sample_server &

curl -s http://localhost:8080/metrics
# HELP exposer_transferred_bytes_total Transferred bytes to metrics services
# TYPE exposer_transferred_bytes_total counter
exposer_transferred_bytes_total 0.000000
# HELP exposer_scrapes_total Number of times metrics were scraped
# TYPE exposer_scrapes_total counter
exposer_scrapes_total 0.000000
# HELP exposer_request_latencies Latencies of serving scrape requests, in microseconds
# TYPE exposer_request_latencies summary
exposer_request_latencies_count 0
exposer_request_latencies_sum 0.000000
exposer_request_latencies{quantile="0.500000"} Nan
exposer_request_latencies{quantile="0.900000"} Nan
exposer_request_latencies{quantile="0.990000"} Nan
# HELP time_running_seconds_total How many seconds is this server running?
# TYPE time_running_seconds_total counter
time_running_seconds_total{label="value",another_label="value",yet_another_label="value"} 14.000000
```

**Comment by gjasny** [comment]
Do you know about the [devtoolset](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) from the Software Collections? Maybe you could use it next time you need a newer compiler on CentOS. It avoids most of these issues.

**Comment by ramesht77** [comment]
We had to re-align small code piece to get this compiled in our environment. Please close the case.

**Comment by maytheforth** [comment]
I encountered the same error when i tried to link static libraries.  Then I solved this problem by using compile flags like that
```
-lprometheus-cpp-core  -lprometheus-cpp-pull  -lprometheus-cpp-core
```
I think the reason is that there are some variables in libprometheus-cpp-pull.a  relying on  libprometheus-cpp-core.a.

**Comment by SuvarinA** [comment]
I have the same issue.

===> Building sample program monRoots for redhat7

rm -f ./monRoots
/usr/bin/g++ -m64 -o ./monRoots -I/test/include -Dx86_Linux_4X -Dx86_Linux_5X -Dx86_Linux_6X -D_iso_stdcpp_ -Dx86_64_OracleLinux_7X.64 -Dx86_Linux_CLOCK_MONOTONIC -DLinuxVersion=7 -DCOMPILE_64BITS -D_REENTRANT -D_SVID_SOURCE=1 -D_BSD_SOURCE=1 -D_POSIX_SOURCE=1 -D_POSIX_C_SOURCE=199506L -D_XOPEN_SOURCE=500 -DLinux -DLINUX -DDEV_LITTLE_ENDIAN -DDEV_POS_THR -D_POSIX_PTHREAD_SEMANTICS -D_GNU_SOURCE -DTRACING_ENABLED -D_RDEV_NO_STL_ -std=c++11 -lprometheus-cpp-core  -lprometheus-cpp-pull  -lprometheus-cpp-core -g \
 ./mainRoots_NO_STL.o ./monRoots.o \
/test/lib/redhat7/librmcpthrd_NO_STL.a /test/lib/redhat7/librmcsml_NO_STL.a /test/lib/redhat7/librmccon_NO_STL.a -lpthread -lrt /test/lib/redhat7/libprometheus-cpp-pull.a /test/lib/redhat7/libprometheus-cpp-core.a
/test/lib/redhat7/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::GZipCompress(std::string const&)':
handler.cc:(.text+0x7b7): undefined reference to `deflateInit2_'
handler.cc:(.text+0x88b): undefined reference to `deflate'
handler.cc:(.text+0x8b9): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
make: *** [monRoots] Error 1


I try to using the compile flags but it still doesn't work.

I also try to add libprometheus-cpp-pull.a before libprometheus-cpp-core.a but also it doesn't work.

**Comment by gjasny** [comment]
No you have a different error. You forgot to link against Linz. See: https://github.com/jupp0r/prometheus-cpp#plain-makefiles

**Comment by SuvarinA** [comment]
Thanks a lot. I can compile my code now.
