### ISSUE TITLE
How to run the /prometheus-cpp/cmake/project-import/sample_server.cc?

### ISSUE THREAD

**Issue by PongsatornChan** [jupp0r/prometheus-cpp#370]
Hello there,
I am really new to these CMake, shared library, Prometheus client library things.
I am struggling to run `/prometheus-cpp/cmake/project-import/sample_server.cc` , the example on README. 
I am working on MacBook Pro 2015 Catalina 10.15.4.

After I download prometheus-cpp and unzip it, I built using CMake following the Building Section on README successfully. File structure: `/prometheus-cpp/_build` 

So I tried to compile simple_server.cc with gcc:
`fatal error: 'prometheus/counter.h' file not found`

I assume that this is because I didn't link the library correctly, but I am not sure how.
So I tried to run `cmake .` in project-import directory and fail:
```
Could not find a package configuration file provided by "prometheus-cpp" with any of the following names:
    prometheus-cppConfig.cmake
    prometheus-cpp-config.cmake
...
```
So I tried many things, copy prometheus-cpp-config.cmake from _build directory to /project-import dir, /cmake dir, and others location. I copy simple_server.cc to different locations that have counter.h in them. I searched the Internet for similar problems and tried to change CMakeList.txt file. I feel really frustrated about my inexperience. It is just too many things I don't know. So I am asking for help from people who know. I really appreciate any help.

**Comment by gjasny** [comment]
Hello, this test project is intended to test the _installed_ prometheus-cpp tree (you need to call `make install` on the root project). It's meant for CI purposes.

**Comment by pralhadsapre** [comment]
Assuming you followed the instructions and installed the project to `<repo_location>/prometheus-cpp/build/deploy` directory, there are two options:

1. Use the `CMAKE_PREFIX_PATH` environment variable as:
`export CMAKE_PREFIX_PATH=<repo_location>/prometheus-cpp/build/deploy/usr/local/lib/cmake/prometheus-cpp/`

2. Add a line to the `CMakeLists.txt` in project-import directory with the same value, however this time for the `prometheus-cpp_DIR` variable as:
`set(prometheus-cpp_DIR "<repo_location>/prometheus-cpp/build/deploy/usr/local/lib/cmake/prometheus-cpp/")`

**Comment by PongsatornChan** [comment]
Hey, thank you for the reply.
I was confused about CMAKE_INSTALL_PREFIX. I didn't change it to the install directory (deploy).
So it is working now.
