### ISSUE TITLE
conflict with signature

### ISSUE THREAD

**Issue by nishup20** [jupp0r/prometheus-cpp#373]
seeing this issue while running sample_server.cc via g++
In function `main':
sample_server.cc:(.text+0x18a): undefined reference to `prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
sample_server.cc:(.text+0x4e0): undefined reference to `prometheus::Exposer::RegisterCollectable(std::weak_ptr<prometheus::Collectable> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by gjasny** [comment]
I guess you try to compile `sample_server.cc` in your own project. If that is the case please try to use CMake to protect yourself from this class of errors. If you cannot use CMake please read https://github.com/jupp0r/prometheus-cpp#plain-makefiles

**Comment by gendestry** [comment]
I have almost the same issue.

Running ```g++ `pkg-config --cflags prometheus-cpp-core` `pkg-config --libs prometheus-cpp-pull` -lz prometheus-t.cpp -std=c++11``` results in the following error:

```/usr/bin/ld: /tmp/ccJgRENv.o: in function `main':
prometheus-t.cpp:(.text+0x6d): undefined reference to `prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, CivetCallbacks const*)'
/usr/bin/ld: prometheus-t.cpp:(.text+0xfd): undefined reference to `prometheus::Exposer::~Exposer()'
collect2: error: ld returned 1 exit status```

On the other hand, CMake works just fine and I dont know why.

**Comment by gjasny** [comment]
Could you please paste the output of
```
echo g++ `pkg-config --cflags prometheus-cpp-core` `pkg-config --libs prometheus-cpp-pull` -lz prometheus-t.cpp -std=c++11
```

**Comment by gendestry** [comment]
> 
It evaluates to this:

```g++ -I/home/genergy/.local/include -L/home/genergy/.local/lib -lprometheus-cpp-pull -lprometheus-cpp-core -lz prometheus-t.cpp```

**Comment by gendestry** [comment]
Anything else to test?

**Comment by gjasny** [comment]
Hello,

which OS/distribution do you use? Is the compiler the default one for that platform or targeting some embedded platform?

To debug I usually look which symbols are exported by the libs and which symbols are required by the `.o` file:

```
nm -C lib/libprometheus-cpp-pull.a|grep 'prometheus::Exposer::Exposer'
0000000000000514 T prometheus::Exposer::Exposer(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, CivetCallbacks const*)
0000000000000310 T prometheus::Exposer::Exposer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, CivetCallbacks const*)
0000000000000284 T prometheus::Exposer::Exposer(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, CivetCallbacks const*)
0000000000000000 T prometheus::Exposer::Exposer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, CivetCallbacks const*)
```

```
 nm -C my.o |grep 'prometheus::Exposer::Exposer' 
                 U prometheus::Exposer::Exposer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, CivetCallbacks const*)
```

Here the `U` from the object has an exactly matching `T` in the lib.

What do you see?

**Comment by gendestry** [comment]
I use Ubuntu 20.04 LTS (```Linux toaster 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```)

I am using the default g++ compiler (```g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0```) and it is the default one yes.

```
nm -C /home/genergy/.local/lib/libprometheus-cpp-pull.a | grep 'prometheus::Exposer::Exposer'

0000000000000020 T prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, CivetCallbacks const*)
000000000000027c T prometheus::Exposer::Exposer(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, CivetCallbacks const*)
0000000000000020 T prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, CivetCallbacks const*)
000000000000027c T prometheus::Exposer::Exposer(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, CivetCallbacks const*)
```

Running ```nm -C prometheus-t.o | grep 'prometheus::Exposer::Exposer'``` yields:
```U prometheus::Exposer::Exposer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, CivetCallbacks const*)```.

**Comment by gjasny** [comment]
The error comes from the way [single pass linkers](https://stackoverflow.com/a/21854528/3738148) work. You need to put your C++ file in front and libs at the end of the command line. The following works for me:

```
g++ prometheus-t.cpp `pkg-config --cflags prometheus-cpp-core` `pkg-config --libs prometheus-cpp-pull` -lz -pthread  -std=c++11
```

I'll check why the `-lz` and `-pthread` flags are still necessary.

**Comment by gjasny** [comment]
If you link the static lib version of prometheus-cpp you need to add `--static` as well. This works for me:
```
g++ prometheus-t.cpp `pkg-config --cflags --libs --static prometheus-cpp-pull` -std=c++11
```

**Comment by gendestry** [comment]
Sweet, it works, thanks!
