### ISSUE TITLE
CMake Build Fails on windows

### ISSUE THREAD

**Issue by nishup20** [jupp0r/prometheus-cpp#375]
Hi,
I am trying to build the project on windows following the steps mentioned with cmake.
even though I have curl, the cmake build is failing with the below issue
**CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.70.0")
**Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILU**RE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindCURL.cmake:169 (find_package_handle_standard_args)
  push/CMakeLists.txt:2 (find_package)******
Can you please help me how to fix.

**Comment by gjasny** [comment]
Curl is only needed for the push-gateway integration. If you don't need that functionality (most users don't), disable it with `-DENABLE_PUSH=OFF`.
If you need it I'd suggest to use a package manager like vcpkg to install curl.

**Comment by nishup20** [comment]
that worked for me, thanks.
But after giving _cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF_ when follow with **make -j 4** as mentioned in the steps,
I get this 
**$ make -j 4
make: *** No targets specified and no makefile found.  Stop.**

**Comment by nishup20** [comment]
Thanks @gjasny, I'm able to build.. but seems like debug folder does not contain the lib and include folder as seen in case of linux when built, where can I find it?

**Comment by gjasny** [comment]
It's in `<builddir>/lib/<Config>`:

```
D:\Git\prometheus-cpp\_b>dir lib\Debug 

 Directory of D:\Git\prometheus-cpp\_b\lib\Debug

15/11/2020  20:25    <DIR>          .
15/11/2020  20:25    <DIR>          ..
15/11/2020  20:25        11.147.328 gmock_main.lib
15/11/2020  20:25         1.855.488 gmock_main.pdb
15/11/2020  20:25        13.759.352 prometheus-cpp-core.lib
15/11/2020  20:25         3.894.342 prometheus-cpp-pull.lib
```
