### ISSUE TITLE
Issue with cmake build in windows

### ISSUE THREAD

**Issue by nishup20** [jupp0r/prometheus-cpp#376]
Hi, I am trying to build the library in windows to generate libs.. when I follow the steps mentioned in Readme.. at this step when I give **make -j 4** 
I am getting this error (even though I see that mutex has been included)
`In file included from C:/Prometheus/cm2/core/include/prometheus/registry.h:12,                                                           from C:/Prometheus/cm2/core/src/detail/builder.cc:6:                                                   C:/Prometheus/cm2/core/include/prometheus/family.h:146:16: error: 'mutex' in namespace 'std' does not name a type         146 |   mutable std::mutex mutex_;                                                                                          |                ^~~~~                                                                                            C:/Prometheus/cm2/core/include/prometheus/family.h:22:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?                                                                                                  21 | #include "prometheus/metric_family.h"                                                                             +++ |+#include <mutex>                                                                                                   22 |                                                                                                                 In file included from C:/Prometheus/cm2/core/src/detail/builder.cc:6:                                                   C:/Prometheus/cm2/core/include/prometheus/registry.h:95:16: error: 'mutex' in namespace 'std' does not name a type         95 |   mutable std::mutex mutex_;                                                                                          |                ^~~~~                                                                                            C:/Prometheus/cm2/core/include/prometheus/registry.h:13:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?                                                                                                12 | #include "prometheus/family.h"                                                                                    +++ |+#include <mutex>                                                                                                   13 | #include "prometheus/metric_family.h"                                                                           In file included from C:/Prometheus/cm2/core/src/detail/builder.cc:7:                                                   C:/Prometheus/cm2/core/include/prometheus/summary.h:88:16: error: 'mutex' in namespace 'std' does not name a type          88 |   mutable std::mutex mutex_;                                                                                          |                ^~~~~                                                                                            C:/Prometheus/cm2/core/include/prometheus/summary.h:13:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?                                                                                                 12 | #include "prometheus/detail/time_window_quantiles.h"                                                              +++ |+#include <mutex>                                                                                                   13 | #include "prometheus/metric_type.h"                                                                             make[2]: *** [core/CMakeFiles/core.dir/src/detail/builder.cc.obj] Error 1                                               make[1]: *** [core/CMakeFiles/core.dir/all] Error 2                                                                     make: *** [all] Error 2        `

can you please help me how can I fix it

**Comment by nishup20** [comment]
![image](https://user-images.githubusercontent.com/25985720/84063099-1813b500-a9de-11ea-8b79-084696c66754.png)

**Comment by notopoloko** [comment]
I'm not an expert on windows, but i think e can help you. Can provide the output of cmake command?
