### ISSUE TITLE
Dependecies errors when installing prometheus-cpp package

### ISSUE THREAD

**Issue by Lola-Stankovic** [jupp0r/prometheus-cpp#378]
Hi! I've created prometheus-cpp RPM package for Centos 7 and I'm trying to install it. Unfortunately, I get the following errors:

error: Failed dependencies:
	libstdc++.so.6(CXXABI_1.3.11)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64
	libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.22)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64

Previously I've compiled prometheus-cpp project with GCC 8.2 with the following output:
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find benchmark (missing: benchmark_DIR)
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0")  
-- The following features have been enabled:

 * Pull, support for pulling metrics
 * Push, support for pushing metrics to a push-gateway
 * Compression, support for zlib compression of metrics

-- The following REQUIRED packages have been found:

 * googlemock-3rdparty
 * civetweb-3rdparty
 * cppcodec-3rdparty
 * ZLIB
 * CURL

-- The following OPTIONAL packages have not been found:

 * benchmark

-- Configuring done
-- Generating done
-- Build files have been written to: /home/fogkv/daqdb_200516/prometheus-installation/prometheus-cpp/_build

I've built the RPM package with the following commands:

git submodule update --init
cmake3 -B _build -DCPACK_GENERATOR=RPM -DBUILD_SHARED_LIBS=ON # or OFF for static libraries
cmake3 --build _build --target package --parallel $(nproc)

///////////////////////////////////////////////////////////////////////////////////////////////////////
strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX  results in:
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25

I've set and exported LD_LIBRARY_PATH=/usr/lib64/:$LD_LIBRARY_PATH before compiling the project and the result is the same. The project compiles successfully, the RPM package is built but when I try to install it I get the same dependencies issues. 

Can you please help me out?

More info:
OS : CentOS 7.6.1810 (Core) 
gcc:  version 8.2.0 (GCC) 

Thanks,
Lola

**Comment by gjasny** [comment]
My theory is that you installed GCC 8 yourself without any RPM involvement. Therefore your GCC 8 builds against the libstdc++ from your GCC8 installation and requires symbols RPM does not know about.

I'd recommend that you use the GCC 8 from the devtoolset-8 because it plays nicely with the existing centos 7 toolchain. You could install it by:
```
yum install -y centos-release-scl
yum install -y devtoolset-8-gcc-c++
```

Afterwards you could enable it by:
```
$ source scl_source enable devtoolset-8
$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

When I build the RPM with the devtoolset compiler I get the following dependencies:

```
rpm -qp prometheus-cpp-0.9.0-1.x86_64.rpm --requires
/bin/sh
/bin/sh
/bin/sh
/bin/sh
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libcurl.so.4()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libprometheus-cpp-core.so.0.9()(64bit)
libprometheus-cpp-pull.so.0.9()(64bit)
libprometheus-cpp-push.so.0.9()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.2)(64bit)
libstdc++.so.6(CXXABI_1.3.3)(64bit)
libstdc++.so.6(CXXABI_1.3.5)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.19)(64bit)
libstdc++.so.6(GLIBCXX_3.4.5)(64bit)
libz.so.1()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
```

The `CXXABI` is the one supported by the vanilla CentOS libstdc++6. Installing the RPM worked without any error.

PS: There's also devtoolset-9 with GCC 9 available.

**Comment by Lola-Stankovic** [comment]
Hi,

Thank you for your reply. 
As we need to use GCC 8.2 version( as devtoolset is shipped with broken sudo and prone to change some environmental )
could you please give your opinion on the following output:

These are the steps taken to install GCC 8.2 and to build prometheus-cpp RPM package:

 wget https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.gz
tar xzf gcc-8.2.0.tar.gz
cd gcc-8.2.0
./contrib/download_prerequisites
cd ..
mkdir gcc-8.2.0-build
cd gcc-8.2.0-build
../gcc-8.2.0/configure --enable-languages=c,c++ --disable-multilib
make -j$(nproc)
sudo make install

----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib/../lib64

-------------------------------------------------------------
echo $PATH
export PATH=/usr/local/bin:$PATH
unset LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
export CC=`which gcc`
export CXX=`which g++`

-----------------------------------------------------------------------
I've built the RPM package with the following commands:

git submodule update --init
cmake3 -B _build -DCPACK_GENERATOR=RPM -DBUILD_SHARED_LIBS=ON # or OFF for static libraries
cmake3 --build _build --target package --parallel $(nproc)
cd _build
sudo rpm -i prometheus-cpp-0.9.0-1.x86_64.rpm
error: Failed dependencies:
	libstdc++.so.6(CXXABI_1.3.11)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.22)(64bit) is needed by prometheus-cpp-0.9.0-1.x86_64

**Comment by Lola-Stankovic** [comment]
Previously I've compiled prometheus-cpp project with gcc 8.2:
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
