### ISSUE TITLE
Syntax errors from header files

### ISSUE THREAD

**Issue by nishup20** [jupp0r/prometheus-cpp#379]
Hi, when I include the header files in my project and build them, I am getting below errors even though I have not changed anything in the header files, please help me fix this.

![image](https://user-images.githubusercontent.com/25985720/85015697-0a9cbe80-b186-11ea-8dff-fd4c4895dc4e.png)

**Comment by gjasny** [comment]
Hello,

I guess the generated export header in `include/prometheus/detail/core_export.h` cannot be understood by the MSVC compiler. Could you please show the content?

Thanks,
Gregor
