### ISSUE TITLE
Providing some PromQL calculations ready

### ISSUE THREAD

**Issue by nnWhisperer** [jupp0r/prometheus-cpp#387]
Hi,
I have a couple of calculations based on the observations coming from the prometheus client; such as mean/max rate of a measured gauge in an interval like 30 seconds. I want the prometheus Web UI user to receive this information automatically, without having to resort to a PromQL query because I am delivering a product and it is not practical to expect the user to know how to query in my conditions. Is it possible to achieve that? Thank you,

**Comment by gjasny** [comment]
Hello,

I fear this is outside of the desired feature set of this library. If you want custom behaviour you could always implement your own Collectable (wrapper) class and add the functionality there. Then register it into the Exposer.

Thanks,
Gregor
