### ISSUE TITLE
Releases should include 3rdparty

### ISSUE THREAD

**Issue by wernight** [jupp0r/prometheus-cpp#388]
The current way to build a release is like:

```bash
git clone https://github.com/jupp0r/prometheus-cpp
cd prometheus-cpp
git checkout v0.9.0
git submodule init
git submodule update
```

This is okay but requires git and is rather slow when using container (Docker).

I'd suggest that 3rdparty to be included in generated releases, this would allow the above to be reduced to:

```bash
curl -L https://github.com/jupp0r/prometheus-cpp/archive/v.0.9.0.tar.gz | tar xz
```

**Comment by gjasny** [comment]
Hello,

do you know any existing release tool or github action which automates the tarball generation and upload?

Thanks,
Gregor
