### ISSUE TITLE
What if I want to increment the particular label value in the counter How can I acheive that?

### ISSUE THREAD

**Issue by ZainAli26** [jupp0r/prometheus-cpp#389]

**Comment by baozh** [comment]
I also encounter this problem, It only get reference, how to get pointer of family?

**Comment by jupp0r** [comment]
> What if I want to increment the particular label value in the counter How can I acheive that?

I'm going to assume that by label value you mean the second part of a label pair.

You can't. Labels are immutable and you can't change them after your counter is created. This is consistent with the [prometheus data model](https://www.prometheus.io/docs/concepts/data_model). Normally the thing you want to increment is the counter value. Labels are there to distinguish counters of the same family from each other (403 error counts from 404 error counts for example).

> I also encounter this problem, It only get reference, how to get pointer of family?

C++ has the `&` operator for obtaining addresses to values:

```c++
auto& family = /* create family here */
Family* pointer_to_family = &family;
```
