### ISSUE TITLE
Issue when building with -D_GLIBCXX_DEBUG

### ISSUE THREAD

**Issue by rmartinez3** [jupp0r/prometheus-cpp#392]
Was testing library and noticed when building with -D_GLIBCXX_DEBUG flag I see this issue with the sample server

```
sample_server.cc:(.text+0x184): undefined reference to `prometheus::detail::Builder<prometheus::Counter>::Labels(std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<c
har> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pa
ir<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
```

Was trying to to see if building the Prometheus library adding   -DCMAKE_BUILD_TYPE=Debug -Denable-glibcxx-debug=ON to cmake will help. However still same issue.

Maybe I'm missing something on my end . 

Any help or guidance will be great.

Thanks

**Comment by gjasny** [comment]
Hello,
the `-Denable-glibcxx-debug=ON` is not an universal way to use the extra debugging in the GNU STL. CMake also emits a warning about that:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    enable-glibcxx-debug
```

What should work is the following:
```
CXXFLAGS="-D_GLIBCXX_DEBUG" cmake .. -GNinja
```

Does that solve your problems?

**Comment by rmartinez3** [comment]
Hello thanks for the response. This is what we ended up  doing as other libraries we are using needed the prom library to have built with those flags. Thanks !
