### ISSUE TITLE
Pre-built/other build methods for Visual C++

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#400]
We have an established MSVC++ product (dozens of solutions, etc) and we do not use CMake or Bazel, and having used CMake in the past I would rather not introduce it to our build process just one for library.

I might have to settle for pre-building this as a 3rd-party dependency lib but even then I would rather avoid CMake. I don't suppose anyone provides pre-built or vcproj downloads for those in Windows-specific environments?

Thanks for providing this project, by the way.

**Comment by gjasny** [comment]
Hello,

we published it into vcpkg. Maybe you could integrate vcpkg without CMake.

Thanks,
Gregor

**Comment by jdx-john** [comment]
I'll look into that, thanks - I'm returning to C++ after quite a break working with other things so getting back up to speed with how VC++ does things

**Comment by gjasny** [comment]
Please re-open if you need further assistance.

**Comment by jdx-john** [comment]
@gjasny so looking a bit more, vcpkg is nice but I confirm we cannot use CMake or any of those things in our codebase - it's 20+ years old and has its own way of doing things  that nobody is going to want to rework now it's in fairly minimal development.

So I need a way to:

1. pre-build prometheus-cpp to static libs that we can add to our tool-chain
1. so we can manually add include paths and libs to our pre-existing VC++ projects

I think 1. is largely solved with vcpkg but what if we have our own fork to add some features you didn't want to accept, or whatever? Is it possible to hack existing vcpkg port to use a different URL so our modified sources get built instead? It seems a really handy tool I wouldn't want to re-invent!

Regarding 2, I exported from vcpkg after building to take a look how I would manually configure a VC++ project without CMake and of course there's quite a lot of dependencies :) I was wondering, if someone had a hello-world VC++ project using prometheus-cpp, could the vcxproj generated by CMake be shared for me to inspect - otherwise I expect I'll spend ages trial-and-error.

Clearly not optimal but sometimes you have to do what you have to do.

**Comment by jdx-john** [comment]
> Please re-open if you need further assistance.

I don't seem able to...
