### ISSUE TITLE
Precision loss in float rendering

### ISSUE THREAD

**Issue by brian-brazil** [jupp0r/prometheus-cpp#407]
We happened to be looking at this code as part of OpenMetrics, and noticed that there appears to be precision loss in how floating points are rendered by this client library:

https://github.com/jupp0r/prometheus-cpp/blob/3a8ed550e9fa805394e4506de5a1cd205163ef6f/core/src/text_serializer.cc#L13

The default precision for C++ floats is 6, which is not sufficient for a 64bit floating point which can have 17 significant digits. I believe this be changed to explicitly ask for 17 digits of precision.

**Comment by jupp0r** [comment]
Good catch, I'll fix it right away and release a new version.

**Comment by gjasny** [comment]
What would you recommend? `std::hexfloat`? The golang code uses the `g` format: https://golang.org/pkg/strconv/#FormatFloat

**Comment by jupp0r** [comment]
@gjasny I went with `std::setprecision`, are you concerned about the trailing zeroes or is it something else?

**Comment by jupp0r** [comment]
> We happened to be looking at this code as part of OpenMetrics, and noticed that there appears to be precision loss in how floating points are rendered by this client library

@brian-brazil Let me know if you find something else or have more feedback.

**Comment by brian-brazil** [comment]
Golang's `g` works differently, it always has sufficient precision by default.

> I went with std::setprecision

That sounds about right, though it has been many many years since I learned C++ iostreams.

**Comment by gjasny** [comment]
@jupp0r Could you please release a new 0.11.0 version?
