### ISSUE TITLE
question: calculation of histogram bucket count

### ISSUE THREAD

**Issue by umegaya** [jupp0r/prometheus-cpp#41]
hi, thank you for creating this, now I try to embed this library in my app. 
question is, doc says [histogram buckets are cumulative](https://prometheus.io/docs/practices/histograms/) but [implementation of this library](https://github.com/jupp0r/prometheus-cpp/blob/master/lib/histogram.cc#L35) does not seems to do so. 
``` c++
for (std::size_t i = 0; i < bucket_counts_.size(); i++) {
    auto& count = bucket_counts_[i];
    auto bucket = histogram->add_bucket();
    bucket->set_cumulative_count(count.Value()); //here
    bucket->set_upper_bound(i == bucket_boundaries_.size()
                                ? std::numeric_limits<double>::infinity()
                                : bucket_boundaries_[i]);
  }
```

I check another implementation eg. [golang](https://github.com/prometheus/client_golang/blob/master/prometheus/histogram.go#L264), it seems to be cumulative. 
``` golang
	var count uint64
	for i, upperBound := range h.upperBounds {
		count += atomic.LoadUint64(&h.counts[i]) //here
		buckets[i] = &dto.Bucket{
			CumulativeCount: proto.Uint64(count),
			UpperBound:      proto.Float64(upperBound),
		}
	}
```
is this bug or cpp implementation calculate cumulative counter in another place?

**Comment by jupp0r** [comment]
Hi, I think this is a bug, thanks for finding it.
