### ISSUE TITLE
Support delegates for simplicity and performance?

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#419]
If I have a `gauge` which is reporting the size of a collection, it would save a lot of boring coding if we could bind `std::vector::size`. It would save time coding, reduce opportunities for error, and potentially be a performance boost as we don't have to update the `gauge` every time the collection is modified.

I know other languages support this in their Prometheus client libs, obviously C++ is a bit different from Java but is it not feasible in modern C++?

**Comment by jupp0r** [comment]
Hey John,

you can accomplish this by implementing your own class implementing`Collectable`. Some untested code to give you an idea:

```
class VectorSizeGauge : public prometheus::Collectable {
  public:
    VectorSizeGauge(const std::vector& v) : v_{v} {
         // you'd probably want name, labels and help here, too
     }

    std::vector<prometheus::MetricFamily> Collect() const {
         // fill the gauge and family struct with labels, omitted here
        // you could also cache the gauge as object state if you want
        auto gauge = prometheus::Gauge{};
        gauge.value = v_.size();
        auto family = prometheus::MetricFamily{};
        family.gauge = gauge;
        return {family};
    }
  private:
    const std::vector& v_;   
};
```

**Comment by gjasny** [comment]
This is duplicated by #527. I'm closing this issue in favour if the other one.
