### ISSUE TITLE
Histograms are not cumulative

### ISSUE THREAD

**Issue by scotloach** [jupp0r/prometheus-cpp#43]
I believe Prometheus histograms should be cumulative, as described here:
https://prometheus.io/docs/concepts/metric_types/#histogram

This means all bins >= the one matching the value should be incremented when Observe() is called.
But this library seems to only increment the single bucket that the sample matches.

**Comment by gjasny** [comment]
What makes you think that they are not cummulative? If you have code, could you please create a falling test similar to #42?

**Comment by scotloach** [comment]
It's possible I am missing something or misunderstanding something. But check out the unit test I pasted below.  A cumulative histogram as expected by Prometheus would have 2 in the first bucket, 4 in the second bucket and 5 in the third bucket.

e.g. see this page: https://prometheus.io/docs/practices/histograms/ 
"...histogram buckets are cumulative. The le="0.3" bucket is also contained in the le="1.2" bucket..."

```
TEST_F(HistogramTest, bucket_count) {
  Histogram histogram{{1, 2}};
  histogram.Observe(0);
  histogram.Observe(0.5);
  histogram.Observe(1.5);
  histogram.Observe(1.5);
  histogram.Observe(3);
  auto metric = histogram.Collect();
  ASSERT_TRUE(metric.has_histogram());
  auto h = metric.histogram();
  ASSERT_EQ(h.bucket_size(), 3);
  auto firstBucket = h.bucket(0);
  EXPECT_EQ(firstBucket.cumulative_count(), 2);
  auto secondBucket = h.bucket(1);
  EXPECT_EQ(secondBucket.cumulative_count(), 2);
  auto thirdBucket = h.bucket(2);
  EXPECT_EQ(thirdBucket.cumulative_count(), 1);
}```
