### ISSUE TITLE
zlib1.dll?

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#431]
I've built using vcpkg and a brand-new test app in VS2019 built and ran perfectly.

However when I start using PrometheusCPP in an existing project, I find zlib1.dll is not put in the binary folder... unlike my test app.
We do already have zlib.dll so what is the difference and any idea why it would not be being copied over?

**Comment by Flying-Durian-Cake** [comment]
@jdx-john Hi,Can you tell me how to compile successfully under vs2019? I install curl:x64-windows and zlib:x64-windows with vcpkg. But when I start to use CMake to build, it report "unresolved external symbol" error.

**Comment by jdx-john** [comment]
@Flying-Durian-Cake I've only used prometheus via vcpkg which does all that CMake stuff for me. You might want to raise a separate issue so it get seen.
