### ISSUE TITLE
The quantile name Not very good for Summary/Histogram metrics

### ISSUE THREAD

**Issue by bigc2000** [jupp0r/prometheus-cpp#441]
test_duration_ms{instance="localhost:8080", job="run", module="run", quantile="0.75000000000000000"}
test_duration_ms{instance="localhost:8080", job="run", module="run", quantile="0.94999999999999996"}
test_duration_ms{instance="localhost:8080", job="run", module="run", quantile="0.98999999999999999"}

but compate to offical metrics:
prometheus_tsdb_wal_fsync_duration_seconds{instance="localhost:9090", job="prometheus", quantile="0.5"}
prometheus_tsdb_wal_fsync_duration_seconds{instance="localhost:9090", job="prometheus", quantile="0.9"}
prometheus_tsdb_wal_fsync_duration_seconds{instance="localhost:9090", job="prometheus", quantile="0.99"}

The quantile lable is too long for double value,  and if LabelNames provided may be much better.

**Comment by gjasny** [comment]
What do you mean with too long? Could you please be more verbose and describe what you expect and what is broken right now?

**Comment by bigc2000** [comment]
> What do you mean with too long? Could you please be more verbose and describe what you expect and what is broken right now?
 **quantile**="0.75000000000000000"   expected "0.75" ,other than "0.75000000...".

I modified the code, may be n

ot very good. 
 
- Add label for summay's quantile 

-Set precision(2)  for quantile's default lable 

A diff details:
`diff --git a/core/tests/summary_test.cc b/core/tests/summary_test.cc
index f902fbb..9f5ed0d 100644
--- a/core/tests/summary_test.cc
+++ b/core/tests/summary_test.cc
@@ -44,12 +44,13 @@ TEST(SummaryTest, quantile_size) {
 
 TEST(SummaryTest, quantile_bounds) {
   Summary summary{Summary::Quantiles{
-      {0.5, 0.05, "0.5"}, {0.90, 0.01, "0.90"}, {0.99, 0.001, "0.99"}}};
+      {0.50, 0.05, "0.50"}, {0.90, 0.01, "0.90"}, {0.99, 0.001, "0.99"}}};
+  
   auto metric = summary.Collect();
   auto s = metric.summary;
   ASSERT_EQ(s.quantile.size(), 3U);
-  EXPECT_EQ(s.quantile.at(0).quantile, "0.5");
-  EXPECT_EQ(s.quantile.at(1).quantile, "0.9");
+  EXPECT_EQ(s.quantile.at(0).quantile, "0.50");
+  EXPECT_EQ(s.quantile.at(1).quantile, "0.90");
   EXPECT_EQ(s.quantile.at(2).quantile, "0.99");
 }
 
diff --git a/core/tests/text_serializer_test.cc b/core/tests/text_serializer_test.cc
index bacd534..ca941b6 100644
--- a/core/tests/text_serializer_test.cc
+++ b/core/tests/text_serializer_test.cc
@@ -117,8 +117,13 @@ TEST_F(TextSerializerTest, shouldSerializeSummary) {
   EXPECT_THAT(
       serialized,
       testing::HasSubstr(
-          name + "{quantile=\"0.50000000000000000\"} 0.0000000000000000"));
-}
+          name + "{quantile=\"0.50\""));
+
+  EXPECT_THAT(
+      serialized,
+      testing::HasSubstr(
+          "} 0.000"));
 
+}
 }  // namespace
 }  // namespace prometheus
diff --git a/pull/tests/integration/sample_server.cc b/pull/tests/integration/sample_server.cc
index 72512fa..3e2cc0e 100644
--- a/pull/tests/integration/sample_server.cc
+++ b/pull/tests/integration/sample_server.cc
@@ -1,6 +1,7 @@
 #include <prometheus/counter.h>
 #include <prometheus/exposer.h>
 #include <prometheus/registry.h>
+#include <prometheus/summary.h>
 
 #include <chrono>
 #include <map>
@@ -26,17 +27,28 @@ int main() {
                              .Labels({{"label", "value"}})
                              .Register(*registry);
 
+  auto& summary_family = BuildSummary()
+                             .Name("time_running_duration_ms")
+                             .Help("How many seconds is this server running?")
+                             .Labels({{"label", "value"}})
+                             .Register(*registry);
+
   // add a counter to the metric family
   auto& second_counter = counter_family.Add(
       {{"another_label", "value"}, {"yet_another_label", "value"}});
 
+prometheus::Summary &first_summary =  summary_family.Add({{"label","value"}},
+prometheus::Summary::Quantiles{{0.5,0.01,"p50"},{0.90,0.005,"p90"},{0.9,0.001,"p99"}});
   // ask the exposer to scrape the registry on incoming scrapes
   exposer.RegisterCollectable(registry);
 
   for (;;) {
-    std::this_thread::sleep_for(std::chrono::seconds(1));
+    auto start = std::chrono::system_clock::now();
+    std::this_thread::sleep_for(std::chrono::milliseconds(1));
     // increment the counter by one (second)
     second_counter.Increment();
+    auto end = std::chrono::system_clock::now();
+    first_summary.Observe(std::chrono::duration_cast<std::chrono::milliseconds>(end-start).count());
   }
   return 0;
 }
`

**Comment by bigc2000** [comment]
And after change, we can label it any literal value. such as:
# TYPE time_running_duration_ms summary
time_running_duration_ms_count{label="value",label="value"} 62974917
time_running_duration_ms_sum{label="value",label="value"} 62978214.00000000000000000
time_running_duration_ms{label="value",label="value",**quantile="p50"**} 1.00000000000000000
time_running_duration_ms{label="value",label="value",**quantile="p90"**} 1.00000000000000000
time_running_duration_ms{label="value",label="value",**quantile="p99**"} 1.00000000000000000

**Comment by draveness** [comment]
met this issue too, and it's hard to query on the graph (have to copy the quantile)...
