### ISSUE TITLE
Install pkg-config file

### ISSUE THREAD

**Issue by Ericson2314** [jupp0r/prometheus-cpp#447]
See https://github.com/NixOS/nixpkgs/pull/110312 where we added this in our distro (NixOS/Nixpkgs). It would be nicer for the upstream package to install it, however.

**Comment by gjasny** [comment]
Hello,

thanks for opening the issue. In our case we also need to think about the different compilation options (like not using the embedded civetweb copy) or of we need a separate pkgconfig file for libprometheus-{core,push,pull}.

-Gregor

**Comment by Ericson2314** [comment]
We're not wedded to the current pkg-config file. Separate ones is fine if that is easier.
