### ISSUE TITLE
How to assign metric's timestamp?

### ISSUE THREAD

**Issue by Zhang-Xianglong** [jupp0r/prometheus-cpp#448]
Hello

The prometheus text-based format is
```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```
and i found function WriteTail in prometheus-cpp/core/src/text_serializer.cc use the metric.timestamp_ms, but i didn't found counter or gauge interface can assign timestamp_ms.

**Comment by Zhang-Xianglong** [comment]
I think `timestamp` is just used to identify metrics collect time on the Exporter, and the code implementation sets it to the Prometheus collect time by default, is that right?

Or, can I specify multiple samples at different times as follows to reduce prometheus collect interval?
```
# HELP http_request_total total number of http request
# TYPE http_request_total counter
http_request_total{status="200", method="GET"} 94355 1434417560938
http_request_total{status="200", method="GET"} 94355 1434417561938
http_request_total{status="200", method="GET"} 94355 1434417562938
```

**Comment by Zhang-Xianglong** [comment]
https://www.mail-archive.com/prometheus-users@googlegroups.com/msg06474.html

**Comment by jupp0r** [comment]
Exactly, you shouldn't have to worry about timestamps unless you are using the push system
