### ISSUE TITLE
build instructions need reworking

### ISSUE THREAD

**Issue by marcpawl** [jupp0r/prometheus-cpp#45]
Using bazel 0.4.5
on Centos 7.2.1511

bazel build lib:all
bazel test //tests:prometheus_test

I am brand new to Bazel.

$ docker build -t promoteheus-cpp:centos -f Dockerfile.centos .
<snip/>
Step 8/9 : RUN bazel build lib:all
 ---> Running in 3772e5028199
Extracting Bazel installation...
..........................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: while parsing 'lib:all': no such package 'lib': BUILD file not found on package path.
____Elapsed time: 2.652s
$cat Dockerfile.centos 
FROM centos:7.2.1511
RUN yum update -y && \
  yum install -y \
    curl \
    gcc \
    java-1.8.0-openjdk \
    java-1.8.0-openjdk-devel \
    unzip \
    which
RUN curl -L -o /bazel-0.4.5-installer-linux-x86_64.sh  \
  https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-installer-linux-x86_64.sh
RUN curl -L -o /prometheus-cpp-master.zip \
    https://codeload.github.com/jupp0r/prometheus-cpp/zip/master
RUN chmod +x /bazel-0.4.5-installer-linux-x86_64.sh  && \
    /bazel-0.4.5-installer-linux-x86_64.sh 
RUN mkdir /build && cd /build && unzip /prometheus-cpp-master.zip
WORKDIR /build/prometheus-cpp-master
RUN bazel build lib:all
RUN bazel test //tests:prometheus-test

**Comment by jupp0r** [comment]
Sorry the instructions are outdated. `bazel build //:prometheus-cpp` works, you could also use cmake. I'll update the readme asap.

**Comment by marcpawl** [comment]
The new bazel command builds, but seems to deletes the generated library

____[268 / 286] Executing genrule @protobuf//:generate_js_well_known_types_embed [for host]
____[272 / 286] Compiling lib/text_serializer.cc
____Building complete.
Target //:prometheus-cpp up-to-date:
  bazel-bin/libprometheus-cpp.a
____Elapsed time: 138.765s, Critical Path: 106.79s

Output from find is:
/build/prometheus-cpp-master/bazel-testlogs
/build/prometheus-cpp-master/bazel-genfiles
/build/prometheus-cpp-master/bazel-out
/build/prometheus-cpp-master/bazel-prometheus-cpp-master
/build/prometheus-cpp-master/bazel-bin
~

**Comment by jupp0r** [comment]
`libprometheus-cpp.a` should be in bazel-bin:

```bash
$ bazel build //:prometheus-cpp 
..............
INFO: Found 1 target...
Target //:prometheus-cpp up-to-date:
  bazel-bin/libprometheus-cpp.a
INFO: Elapsed time: 2.354s, Critical Path: 0.36s
$ ls bazel-bin
_objs               _virtual_includes   external            libprometheus-cpp.a tests
```
