### ISSUE TITLE
multiple exposers, one http server question

### ISSUE THREAD

**Issue by zalmoxis2019** [jupp0r/prometheus-cpp#457]
Hello,

  I have multiple programs and would like to expose metrics from each of them to the same Exposer (http server).
If i call this 2 or multiple times prometheus::Exposer exposer{"localhost:8091",100}, i get "...CivetException .. Possible problem binding to port." How can i do this with your library?

thank you!

**Comment by jupp0r** [comment]
You cannot listen on the same port from two different programs (unless you are binding to a different local IP address). You can export metrics from different ports and have prometheus scrape both.
