### ISSUE TITLE
Labels are not restricted to Prometheus data model restrictions

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#459]
I just spent ages trying to figure out why Prometheus wouldn't ingest my CPP endpoint (logs very unhelpful) before realising I had a label called "log-level" and this isn't a valid name (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

Invalid _Metric_ names _do_ seem to cause run-time failures in prometheus-cpp, but this label _name_ was being exposed by the endpoint without any problems.

**Comment by gjasny** [comment]
Thanks for the report. We disable some known-to-be-bad std::regex implementations:
https://github.com/jupp0r/prometheus-cpp/blob/fe4f437468c51e3b94fb1b4d74ea8c8996f17879/core/src/check_names.cc#L8-L13

What compiler do you use?

**Comment by jdx-john** [comment]
I'm on VS2019. However am I right these checks (CheckNames.h) are only done in DEBUG builds? It looks like they are ASSERTed?
 
I also noted in some quick testing you can set the same label twice, which I assume shouldn't be allowed?
```
# HELP time_running_seconds_total How many seconds is this server running?
# TYPE time_running_seconds_total counter
time_running_seconds_total{test_label="one",test_label="value1"} 11.00000000000000000

```

**Comment by gjasny** [comment]
The checks should not be dependent on assertions:
https://github.com/jupp0r/prometheus-cpp/blob/77a5b0172833786ec014498d61a4dd87c500dc3b/core/src/family.cc#L50-L55

Could you please try the following somewhere in your code?
```
#include "prometheus/check_names.h"

...

std::cout << "Label log-level is valid: " << prometheus::CheckLabelName("log-level") << '\n';
```

Additionally I worked on a patch to replace the sometimes unavailable name-check-regex with something less fancy: #462.

I'll take a look whether the same label name should be allowed multiple times.

**Comment by gjasny** [comment]
I believe the issue is fixed. Please re-open if that's not the case for you.
