### ISSUE TITLE
If body is empty when pushing 'GET' is used and result is 405 instead of 200

### ISSUE THREAD

**Issue by aldoshkind** [jupp0r/prometheus-cpp#469]
If all the metrics are being created dynamically there is a moment when there are no metrics registered.
If you push at this moment body will be empty and GET method will be used instead of POST/PUT.
Using GET method results in 405 response instead of 200 (if you use empty body with POST).

My suggestion is to use `curl_easy_setopt(curl, CURLOPT_POST, 1);`

**Comment by gjasny** [comment]
Good catch! Could you please open a PR with your proposed change?

**Comment by aldoshkind** [comment]
PR is here, please review
https://github.com/jupp0r/prometheus-cpp/pull/470
