### ISSUE TITLE
cmake build static library using shared libraries

### ISSUE THREAD

**Issue by marcpawl** [jupp0r/prometheus-cpp#47]
The static library built using cmake should only use static libraries for its dependencies.
One of the points of using a static library is that no other files need to be installed other than the executable that uses the library.
Currently libprotobuf.so.12 is required.

**Comment by gjasny** [comment]
That is a shortcoming of CMake. Please work around by either just provide the static library variant of protobuf in the search paths or point the protobuf find module to the static libraries: `-DProtobuf_LIBRARY=/path/to/libprotobuf.a` (see [FindProtobuf](https://cmake.org/cmake/help/v3.8/module/FindProtobuf.html)).

Does that solve your problem?
