### ISSUE TITLE
Endpoint should explicitly use UTF-8 character set

### ISSUE THREAD

**Issue by jdx-john** [jupp0r/prometheus-cpp#473]
I have Swedish special characters in label values (not names). Prometheus is reporting "invalid UTF8 in label value" when it scrapes endpoints containing these metrics, though they render fine in Chrome.

My investigation reveals Prometheus-CPP appears to be sending Windows-1252 encoded characters, rather than UTF8 and it does not explicitly specify character encoding in the header:
![image](https://user-images.githubusercontent.com/1654627/112473284-0f6e4e80-8d66-11eb-9e85-c4c9c37913e2.png)

I'm not sure if I am providing text in this encoding and I don't know if I expect Prometheus-CPP to convert text to UTF8, but it could at least check if it is serving invalid Prometheus-format data?

**Comment by jdx-john** [comment]
I investigated this and fixed in my case by forcing strings to be UTF8, but I think Prometheus-CPP _should_ be explicitly providing that charset. Here are some reasons:

1. The documentation seems to say so: https://prometheus.io/docs/instrumenting/exposition_formats/
2. It is confusing when manually inspecting metrics endpoints since browsers are bad at detecting charset.

I use Google Chrome. When my label values were including non-UTF8 content (Windows-1252 or MBCS) my /metrics endpoint was viewing _perfectly_ in Google Chrome but was being rejected by Prometheus.
When I fixed my content to be UTF8, it is now accepted in Prometheus _BUT_ the foreign characters are displayed incorrectly in Google Chrome since it still guessed the charset as Windows-1252 (I checked in Chrome DevTools). This led to me thinking there was still a problem when there wasn't. When I used an extension to force Chrome to use UTF8 charset, it looked great again. 

So by simply explicitly marking the charset as UTF8 in the headers, probably I would have noticed the initial problem sooner and it would make viewing endpoints manually for testing easier. I would imagine it is a trivial change?

Is it possible I can actually do this in my client code without modifying Prometeus-CPP source, or is Civet hidden from my code?

**Comment by gjasny** [comment]
Hello, could you give prometheus-cpp 0.12.2 a try? I recently fixed #377 .

**Comment by jdx-john** [comment]
Aha, @gjasny I hadn't seen that. I'll check what version we're on and see if I can update but it sounds like it _should_ fix this issue.

**Comment by jupp0r** [comment]
Did you take a look @jdx-john ? If it's not fixed feel free to reopen the issue.
