### ISSUE TITLE
Detect and use system's available civetweb

### ISSUE THREAD

**Issue by PerryWerneck** [jupp0r/prometheus-cpp#474]
I'm packaging the prometheus-cpp library to make it easier to use on linux systems (and, doing that I noticed the using an internal version of the civetweb library. It would be nice if the build process can detect and use the system available civetweb.

My project (for now it's only for opensue 15.2 but other distros can be easily added): https://build.opensuse.org/package/show/home:PerryWerneck:udjat/prometheus-cpp

**Comment by gjasny** [comment]
Hello,

please set the `USE_THIRDPARTY_LIBRARIES` to a falsy value.

like here: https://github.com/microsoft/vcpkg/blob/master/ports/prometheus-cpp/portfile.cmake#L28

or there: https://salsa.debian.org/debian/prometheus-cpp/-/blob/master/debian/rules#L14

The Debian packaging repo might provide you with more useful things to copy.

Thanks,
Gregor

**Comment by PerryWerneck** [comment]
This changed workerd! The package was build without errors.

Thanks!
