### ISSUE TITLE
is it possible to listen to multiple ip addresses

### ISSUE THREAD

**Issue by L0ric0** [jupp0r/prometheus-cpp#475]
as the title says i would like to listen to multiple ip addresses. is that curently supported?

**Comment by gjasny** [comment]
Hello,

by default (when only specifying a port) civetweb will listen on the `ANY` address `0.0.0.0` (and maybe on ipv6 `::`) which includes all present and future configured interfaces on your host.

If you want to exclude an interface you'll have to specify all other interfaces IPs. You could do that with the `bind_address` parameter: https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listening_ports-8080

Hope that helps!
-Gregor
