### ISSUE TITLE
run metrics collection when http endpoint is hit

### ISSUE THREAD

**Issue by L0ric0** [jupp0r/prometheus-cpp#476]
this is manly for colectors that expose the state of a sensor (by calling set of gauge). as the old values that are collected between scraps are useless and not stored they are exess work that would not have to be done. so there should be a possibility to run the collection of certain metrics when the http endpoint is hit to reduce work.

**Comment by gjasny** [comment]
Hello,

a HTTP GET request always results in a call to `Collectable::Collect` (and then down to `Gauge::Collect`:

```
 * frame #0: 0x0000000104cff240 libprometheus-cpp-core.0.12.dylib`prometheus::Counter::Collect(this=0x00000001306069d0) const at counter.cc:18:26
    frame #1: 0x0000000104d0cf1c libprometheus-cpp-core.0.12.dylib`prometheus::Family<prometheus::Counter>::CollectMetric(this=0x00000001306076a0, hash=0, metric=0x00000001306069d0) const at family.cc:109:28
    frame #2: 0x0000000104d0cb20 libprometheus-cpp-core.0.12.dylib`prometheus::Family<prometheus::Counter>::Collect(this=0x00000001306076a0) const at family.cc:102:39
    frame #3: 0x0000000104d42934 libprometheus-cpp-core.0.12.dylib`void prometheus::(anonymous namespace)::CollectAll<std::__1::vector<std::__1::unique_ptr<prometheus::Family<prometheus::Counter>, std::__1::default_delete<prometheus::Family<prometheus::Counter> > >, std::__1::allocator<std::__1::unique_ptr<prometheus::Family<prometheus::Counter>, std::__1::default_delete<prometheus::Family<prometheus::Counter> > > > > >(results=size=0, families=size=2) at registry.cc:20:33
    frame #4: 0x0000000104d427e8 libprometheus-cpp-core.0.12.dylib`prometheus::Registry::Collect(this=0x00000001306074f8) const at registry.cc:49:3
    frame #5: 0x0000000104c40394 libprometheus-cpp-pull.0.12.dylib`prometheus::detail::CollectMetrics(collectables=size=2) at metrics_collector.cc:20:35
    frame #6: 0x0000000104c36480 libprometheus-cpp-pull.0.12.dylib`prometheus::detail::MetricsHandler::handleGet(this=0x00000001306075b0, (null)=0x0000000130606dd0, conn=0x00000001308097f0) at handler.cc:151:15
    frame #7: 0x0000000104c082b8 libprometheus-cpp-pull.0.12.dylib`CivetServer::requestHandler(conn=0x00000001308097f0, cbdata=0x00000001306075b0) at CivetServer.cpp:140:20
    frame #8: 0x0000000104c2a69c libprometheus-cpp-pull.0.12.dylib`handle_request(conn=0x00000001308097f0) at civetweb.c:14566:8
    frame #9: 0x0000000104c29494 libprometheus-cpp-pull.0.12.dylib`process_new_connection(conn=0x00000001308097f0) at civetweb.c:18545:5
```

When reading your text it seems that you'd like to read your sensor in at the time of the GET request and not in-between. Maybe you event want to cache it for some time.

You could do all of that by creating your own subclass of `Collectable` and registering it to the `Exposer`. There you could implement on-demand reading of your sensor data and also perform any form of caching.

Thanks,
Gregor

**Comment by L0ric0** [comment]
i see what you mean and will probably do that.

But i also think that this library would benefit from having this functionality build in as it seems to be easy to implement and users would not have to know the internals of the library to get the effect. I will see if i can make a PR.

**Comment by gjasny** [comment]
This is duplicated by #527. I'm closing this issue in favour if the other one.
