### ISSUE TITLE
How to control log level, how to redirect logs to my own logger?

### ISSUE THREAD

**Issue by kuvaldini** [jupp0r/prometheus-cpp#479]

**Comment by gjasny** [comment]
Hello,

which output are you referring to? My suspicion is that it's either libcurl or civetweb.

Thanks,
Gregor

**Comment by kuvaldini** [comment]
It is civetweb.
I found that
1. civetweb must be built as RELEASE to suppress debug logs. They are controlled via #define DEBUG
2. civetweb has mg_callbacks or CivetCallbacks (in C++) to control log_message() and log_access() functions

So. What I do to suppress logs a) build civetweb RELEASE and b) see PR
