### ISSUE TITLE
How to disable "meta" metrics about the endpoint itself?

### ISSUE THREAD

**Issue by kuvaldini** [jupp0r/prometheus-cpp#480]

**Comment by gjasny** [comment]
Right now there is no such functionality. Would you like to do a PR?

**Comment by jupp0r** [comment]
I'm also curious about your reason for disabling them. Having these metrics is pretty common in other client libraries as well as in the prometheus server itself.

**Comment by gjasny** [comment]
The prometheus guideline suggest that users SHOULD be able to disable these: https://prometheus.io/docs/instrumenting/writing_clientlibs/#standard-and-runtime-collectors

**Comment by kuvaldini** [comment]
@jupp0r somebody of the users of our app asked to disable because this is uninteresting text. 

I simply commented the lines of code to reach the feature. I do not think people really need to disable self-metrics.

**Comment by kuvaldini** [comment]
@gjasny, no I would not. I do not think this has any real-world sense.
