### ISSUE TITLE
Conan center dependency conflicts

### ISSUE THREAD

**Issue by dnck** [jupp0r/prometheus-cpp#484]
Hi,

I'm not sure if this is your issue, or somewhere upstream, but the Conan center shows conflicting transitive dependencies for prometheus-cpp v0.12.1.

https://conan.io/center/prometheus-cpp?tab=dependencies

Specifically, the dependency civetweb/1.13 requires openssl/1.1.1**j**, but libcurl/7.74.0 needs openssl/1.1.1**k**.

**Comment by gjasny** [comment]
Hello,

we're not involved in any Conan-related work. Maybe @Fefer-Ivan could help you.

Thanks,
Gregor

**Comment by Fefer-Ivan** [comment]
Hi,

From my experience, it is not a problem. Little disclaimer: I am just a user of conan.

AFAIK, conan will pick only 1 version of the any package during `conan install`. If package is mentioned directly in your conanfile.txt, it will pick specified version. If not, it will pick the latest one from all the dependencies.

It will, however, generate a warning message.

So it should work fine, but if you are really want to get rid of this warning message, you can add the latest version of civetweb (1.14) to the conan-center-index and bump openssl dependency. And then bump prometheus-cpp version as well. The community will appreciate it.

If you have more questions, conan channel in cpplang slack is pretty welcoming.

**Comment by jupp0r** [comment]
Thanks for the info @Fefer-Ivan !
