### ISSUE TITLE
Url is different from prometheus-python

### ISSUE THREAD

**Issue by marcpawl** [jupp0r/prometheus-cpp#49]
Prometheus python (https://github.com/prometheus/client_python) the URL for the metrics is http://hostname:port/.

For prometheus-cpp the URL is http://hostname:port/metrics/

**Comment by jupp0r** [comment]
According to https://prometheus.io/docs/instrumenting/writing_exporters/, metrics should be available at `/metrics`:

> It’s nicer for users if visiting http://yourexporter/ has a simple html page with the name of the exporter, and a link to the /metrics.

Imho, `Exposer` should have the url as a configurable setting (with `/metrics` as default). Would you be willing to create a pull request for this?
