### ISSUE TITLE
how to support  "https"?

### ISSUE THREAD

**Issue by bruce12123** [jupp0r/prometheus-cpp#492]
how to support  "https" for prometheuse?
i tried to add suffix in the port  "9092s", but it can not work and print the following log.

---------------------
 "null context when constructing CivetServer. Possible problem binding to port"
---------------

**Comment by gjasny** [comment]
Hello,

you need to compile civetweb against OpenSSL and follow the configuration outlined in #329.

Thanks,
Gregor

**Comment by satyabratabharati** [comment]
How to keep the port alive after creating it using Exposure() method. currently if no data to scrap. the connection is getting closed.
