### ISSUE TITLE
prometheus exemplars support to correlate traces and metrics

### ISSUE THREAD

**Issue by nleeuskadi** [jupp0r/prometheus-cpp#494]
Hi,

I would like to know if the support for prometheus exemplars is planned in prometheus-cpp library?
We are using openTelemetry for our traces and prometheus-cpp for our metrics. 
Being able to correlate both with the help of prometheus exemplars would be great.

Thank you.

**Comment by jupp0r** [comment]
Yes, we are definitely planning to add it, together with full OpenMetrics support. We'll mostly stick with what the prometheus server supports for now, though. Pull requests making incremental progress are extremely welcome, but some of these changes will probably require a bit of a redesign of the existing data model in the library.

**Comment by nleeuskadi** [comment]
thank you for your answer.
