### ISSUE TITLE
Timeline for 1.0 release?

### ISSUE THREAD

**Issue by dparasam** [jupp0r/prometheus-cpp#525]
Hi all,

Could you please let me know what the timeline is for the official 1.0 release?  We are a bit concerned to go with a beta version of the library into production, although we haven't seen any issues using it in our setup currently.

Thank you,
Deepak

**Comment by jupp0r** [comment]
Hi, I think it's time for a 1.0 version. The reason that there hasn't been one so far was that APIs were still evolving, not that it wasn't considered stable enough.

**Comment by gjasny** [comment]
v1.0.0 has been released. 🎉
