### ISSUE TITLE
Could you please write an examples of Histogram ?

### ISSUE THREAD

**Issue by baiwfg2** [jupp0r/prometheus-cpp#53]
Hi, jupp0r. I want to use Histogram in my program. But I can't figure out how to use it such as its method Collect/Observe. Could you please give me an example about building a histogram and set value for it ?

Many Thanks.

**Comment by jupp0r** [comment]
Hi, do the unit tests at https://github.com/jupp0r/prometheus-cpp/blob/master/tests/histogram_test.cc help answer your question? In general, you use `Observer()` to count an observation. When a prometheus server is scraping your service, `Collect()` is called on the histogram to create a snapshot of the values it has counted so far.

**Comment by baiwfg2** [comment]
I checked the unit test. It seems that it doesn't use the Build* method to create a metric family and call Add() to add a metric the same as you did in README.md. So may I do like this ?
```
	auto& hist_cmd_cost_family = BuildHistogram()
			.Name("cerberus_cmd_cost")
			.Help("command cost")
			.Buckets({0,20,30,50}) //is this BucketBoundaries ?
			.Register(*registry);
		auto& hist_cmd_cost = hist_cmd_cost_family.Add({{"cmd_cost","value"}});
		hist_cmd_cost.Observe(proxy->last_cmd_elapse().count());
		hist_cmd_cost.Collect();//just like you said, this is optional
```

**Comment by jupp0r** [comment]
There is still a bug open, because bucket boundaries specified through the histogram builder are not used - #46 . A working example can be found at https://github.com/jupp0r/prometheus-cpp/blob/master/tests/family_test.cc#L66

This should work and I'll add it as a test case:
```c++
Registry registry{};
auto& histogram_family =
    BuildHistogram().Name("hist").Help("Test Histogram").Register(registry);
auto& histogram = histogram_family.Add({{"name", "test_histogram_1"}},
                                       Histogram::BucketBoundaries{0, 1, 2});
histogram.Observe(1.1);
auto collected = registry.Collect();
```

**Comment by baiwfg2** [comment]
Thanks. I'll try that. ![](http://cache.soso.com/img/img/e100.gif)

**Comment by baiwfg2** [comment]
Sorry to bother you.  Here's my issue. When I import prometheus data to grafana, I can see the Gauge and Counter value by using Set method, but I can't see the histogram value(I only use Observe method). I know there are some calculations in histogram, why can't histogram method show calculations results on the grafana directly ? Did I miss something ?
