### ISSUE TITLE
Cases where hash collisions are not handled properly

### ISSUE THREAD

**Issue by ethanvc** [jupp0r/prometheus-cpp#532]
Affect the following code snippets:
```c++
template <typename T>
T& Family<T>::Add(const std::map<std::string, std::string>& labels,
                  std::unique_ptr<T> object) {
  const auto hash = detail::hash_labels(labels);
  std::lock_guard<std::mutex> lock{mutex_};
  auto metrics_iter = metrics_.find(hash);

  if (metrics_iter != metrics_.end()) {
#ifndef NDEBUG
    auto labels_iter = labels_.find(hash);
    assert(labels_iter != labels_.end());
    const auto& old_labels = labels_iter->second;
    assert(labels == old_labels);
#endif
    return *metrics_iter->second;
  }
```

**Comment by gjasny** [comment]
What problem do you see in the code above?

**Comment by ZaMaZaN4iK** [comment]
@ethanvc what is the problem in the code above?

**Comment by anatoly-p** [comment]
@gjasny in the current implementation hash is used as a key for map, it's not a proper way of using maps, there will be collision if two different sets of labels have the same hash, as a result one of them will be lost.

**Comment by gjasny** [comment]
Although the probability is n in 2^64, I have a cleaner implementation in #544.

**Comment by ZaMaZaN4iK** [comment]
Would be awesome, if this fix will land into the next release. Thanks!
