### ISSUE TITLE
Histogram requires buckets to be sorted

### ISSUE THREAD

**Issue by odeits** [jupp0r/prometheus-cpp#55]
This requirement is undocumented and not enforced even in debug builds. 

Recommend:
1. Document requirement
2. `assert(std::is_sorted(std::begin(buckets), std::end(buckets)));` during construction of Histogram

**Comment by jupp0r** [comment]
Good point, what's your opinion on sorting them on histogram construction?

**Comment by odeits** [comment]
I think that an assert is sufficient. Providing documentation on the expectation is key. I think that during release sorting would be a waste if input is already sorted in most cases.

**Comment by jupp0r** [comment]
@odeits thanks for the offer, please use
```c++
/// Method description using markdown
```
