### ISSUE TITLE
ERROR: Failed requirement 'prometheus-cpp/0.12.1' 

### ISSUE THREAD

**Issue by goon94** [jupp0r/prometheus-cpp#550]
Hi, 
I'm trying to add the prometheus-cpp client to my project with conan. 
From what I see on [https://conan.io/center/prometheus-cpp](url) the package name is prometheus-cpp and adding a requirement to prometheus-cpp/0.12.3 should work.

I'm trying the following line: 
`conanfile.requires.add("prometheus-cpp/0.12.1")`

Error I got:
`prometheus-cpp/0.12.1: Not found in local cache, looking in remotes...`
`Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.`

The other libraries are retrieved sucessfully. Only with prometheus-cpp that I got this error.

I am not comfortable working with conan so any help from you guys is welcome.

Tks

**Comment by gjasny** [comment]
Hello,

I guess you'll have to switch the registry from bintray.com to conan.io as outlined in this blog post:
https://blog.conan.io/2021/09/03/conancenter-declare-bintray-obsolete.html

BTW: I have a PR open (conan-io/conan-center-index#8089) to update prometheus-cpp to latest. Once it is published you should upgrade to get all bug fixes.

Thanks,
Gregor
