### ISSUE TITLE
Prometheus Push gateway is not working

### ISSUE THREAD

**Issue by anilknayak** [jupp0r/prometheus-cpp#551]
Write a small program to push metrics to gateway localhost:9100

```
const auto labels = prometheus::Gateway::GetInstanceLabel(GetHostName());
  prometheus::Gateway gateway{"localhost", "9100", "XYZ", labels};
auto& counter_family = prometheus::BuildCounter()
      .Name("time_running_seconds_total")
      .Help("How many seconds is this server running?")
      .Labels({{"label", "value"}})
      .Register(*registry);

  auto& second_counter = counter_family.Add(
      {{"another_label", "value"}, {"yet_another_label", "value"}});

  gateway.RegisterCollectable(registry);

  for (;;) {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    // increment the counter by one (second)
    second_counter.Increment();

    // push metrics
    auto returnCode = gateway.Push();
    std::cout << "returnCode is " << returnCode << std::endl;
  }
```

Node exporter is listening to this port. But I can not see the metric time_running_seconds_total in prometheus UI

**Comment by anilknayak** [comment]
```
const auto labels = prometheus::Gateway::GetInstanceLabel(GetHostName());
  prometheus::Gateway gateway{"localhost", "9100", "XYZ", labels};
  auto registry = std::make_shared<prometheus::Registry>();

  auto& family = prometheus::BuildGauge()
      .Name("gauge_family")
      .Help("How many seconds is this server running?")
      .Register(*registry);

  auto& gauge = family.Add({{"is_available", "value"}});

  gateway.RegisterCollectable(registry);

  for (;;) {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    // increment the counter by one (second)
    const auto random_value = std::rand();
    if (random_value & 1) gauge.Set(1.0);
    if (random_value & 2) gauge.Set(0.0);
    if (random_value & 4) gauge.Set(0.0);
    if (random_value & 8) gauge.Set(1.0);

    // push metrics
    auto returnCode = gateway.Push();
    std::cout << "returnCode is " << returnCode << std::endl;
  }
```

Node exporter is listening to "localhost", "9100"

**Comment by anilknayak** [comment]
Nothing is working or am I making any mistake. Please help me here.

**Comment by gjasny** [comment]
The following works for me.

First I start the push gateway:
```
docker run -d -p 9091:9091 prom/pushgateway
```

Then the `sample_client` from `prometheus-cpp`:
```
$ _build/bin/sample_client 
returnCode is 200
returnCode is 200
returnCode is 200
returnCode is 200
```

Here you already see the "successful" `200` http status code from the push. I can now open the push gateway metrics in my browser: http://localhost:9091/metrics

There I see:
```
# HELP time_running_seconds_total How many seconds is this server running?
# TYPE time_running_seconds_total counter
time_running_seconds_total{another_label="value",instance="drswgregorj03",job="sample_client",label="value",yet_another_label="value"} 15
```

If the steps above do not work for you, I'd suggest that you observe your network traffic with WireShark and see there what goes wrong.

Cheers,
-Gregor

**Comment by gjasny** [comment]
Please note that you should use push gateways only in some rare situations like mentioned on their home page:
> The Prometheus Pushgateway exists to allow ephemeral and batch jobs to expose their metrics to Prometheus. Since these kinds of jobs may not exist long enough to be scraped, they can instead push their metrics to a Pushgateway. The Pushgateway then exposes these metrics to Prometheus.

**Comment by anilknayak** [comment]
Instead of prom/pushgateway can I not use node_exporter to create server

Following are the approach
1. I have started node_exporter to create a scrape at post 9091
2. CPP code has created a Gateway at 9091 to write the metrics
3. ```gateway.Push();``` after the metrics are written is returning 200 code from node_exporter 
4. But the ```http://localhost:9091/metrics``` is not showing the metrics

So I have to use the prom/pushgateway

**Comment by anilknayak** [comment]
I could able to get the metrics

**Comment by anilknayak** [comment]
one more thing I would like to know. 

```
auto returnCode = gateway.Push();
```

I have 3 threads and each have their metrics. If I do gateway.Push() in each thread is this fine. Is this push() thread safe
