### ISSUE TITLE
Ability to control affinity of http workers

### ISSUE THREAD

**Issue by tdiff** [jupp0r/prometheus-cpp#552]
Hi,

Is there a way to configure CPU affinity of the civetweb worker threads?

**Comment by gjasny** [comment]
Hello,

not that I'm aware of. We're passing the [number of threads](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#num_threads-50) down to [civetweb](https://github.com/civetweb/civetweb). Maybe you could implement the desired functionality there.

As a work-around you might be able to:

1. store the cpu mask
2. set the desired cpu mask
3. create the exposer (and its http threads)
4. restore the cpu mask

Thanks,
Gregor
