### ISSUE TITLE
Recovering from client crash

### ISSUE THREAD

**Issue by noamzafrir** [jupp0r/prometheus-cpp#554]
Hello,
I am using prometheus-cpp on my client application to count the number of events processed by the client. I am using a Counter for this purpose.
I want to be able to recover the counter after the client application stopped working and restarted. Right now when that happens a new Counter is created with a value of zero and the counter's value before the crash is lost.
I'm thinking that I should read the previous value from the server when re-creating the counter after the crash. Is that the proper way to handle this or is there a different recommended way?
I see that it's not possible to create a counter with a value other than 0. Should I use a Gauge?

Thanks.

**Comment by gjasny** [comment]
If you really need it you could use the `void Counter::Increment(double);` function to increment to the last known value. But all services I know reset their counters at startup.

**Comment by noamzafrir** [comment]
Hello @gjasny ,
Yes, `void Counter::Increment(double)` is indeed useful for setting a counter to a specific value. Thanks for pointing that out. I somehow overlooked it.
I think that I will have to query the Prometheus server for the last know value.
Is it possible to query the Prometheus server using prometheus-cpp?

**Comment by gjasny** [comment]
prometheus-cpp is a "client" library that only generates metrics. Usually you wouldn't restore values but start from zero, again. Any accumulation and processing would happen through the prometheus query language on server side.

**Comment by noamzafrir** [comment]
Understood.
Thanks.
