### ISSUE TITLE
gatway.Push will block my program

### ISSUE THREAD

**Issue by DeserterW** [jupp0r/prometheus-cpp#555]
if I didn't create  metrics for collector, my program will stopped right there. I wonder know if there is any possible do not how to create gateway successfully without metrics, because sometimes, I need to create gateway first so I can add metrics later.

**Comment by anatoly-p** [comment]
got the same issue… curl_wrapper handles empty data on POST improperly… need to set CURLOPT_POSTFIELDSIZE to 0, otherwise curl is waiting for chunked data to be provided, but wrapper doesn't do that
