### ISSUE TITLE
http connection getting closed when there is no data to send to the port.

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#559]
How to keep the port alive after creating it using Exposer exposer{"127.0.0.1:8080"}. Currently if no data to scrap., the connection is getting lost.

**Comment by gjasny** [comment]
Hello,
the Exposer is powered by [Civetweb](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md). It supports server-side keep-alive by setting the [`enable_keep_alive`](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#enable_keep_alive-no) and [`keep_alive_timeout_ms`](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#keep_alive_timeout_ms-500-or-0) options.

You could pass those to the Exposer here:
https://github.com/jupp0r/prometheus-cpp/blob/d2c9d38f86a7f82e1a42df2d50a7cb2ec6dbd725/pull/include/prometheus/exposer.h#L27-L28

You also need to add your current options. Combined it should be something like:
```
{
  "listening_ports", "127.0.0.1:8080",
  "num_threads", "2",
  "enable_keep_alive", "yes",
  "keep_alive_timeout_ms", "90000",
}
```

**Comment by satyabratabharati** [comment]
> Hello, the Exposer is powered by [Civetweb](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md). It supports server-side keep-alive by setting the [`enable_keep_alive`](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#enable_keep_alive-no) and [`keep_alive_timeout_ms`](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#keep_alive_timeout_ms-500-or-0) options.
> 
> You could pass those to the Exposer here:
> 
> https://github.com/jupp0r/prometheus-cpp/blob/d2c9d38f86a7f82e1a42df2d50a7cb2ec6dbd725/pull/include/prometheus/exposer.h#L27-L28
> 
> You also need to add your current options. Combined it should be something like:
> 
> ```
> {
>   "listening_ports", "127.0.0.1:8080",
>   "num_threads", "2",
>   "enable_keep_alive", "yes",
>   "keep_alive_timeout_ms", "90000",
> }
> ```

Hi Gregor,
Thanks for the reply.!!

After passing the parameters above, we are getting following error:
we are getting following error .

terminate called after throwing an instance of 'CivetException'
what(): null context when constructing CivetServer. Possible problem binding to port.
Aborted

we checked the port is not in used currently.

**Comment by gjasny** [comment]
That works for me. Are you sure that nothing else (like another instance of your process) is listening on the port?
You could debug the syscalls by prefixing your binary startup with `strace -e trace=network -f -o output.txt`.
Then look for failed `bind` calls.

**Comment by satyabratabharati** [comment]
#include <chrono>
#include <map>
#include <memory>
#include <string>
#include <thread>

#include <prometheus/gauge.h>
#include <prometheus/exposer.h>
#include <prometheus/registry.h>

int main(int argc, char** argv) {
using namespace prometheus;

// create an http server running on port 9091
Exposer exposer{
{
**"listening_ports", "0.0.0.0:9091",**
"num_threads", "2",
**"enable_keep_alive", "yes",**
"keep_alive_timeout_ms", "90000",
}
};

auto registry = std::make_shared<Registry>();

// add a new counter family to the registry (families combine values with the
// same name, but distinct label dimensions)
auto& gauge_family = BuildGauge()
.Name("pkt_in")
.Help("%s metric pkt_in")
.Labels({{"function", "capture"}})
.Register(*registry);

// add a counter to the metric family
auto& pkt_in = gauge_family.Add({{"system_id", "0"}});

// ask the exposer to scrape the registry on incoming scrapes
exposer.RegisterCollectable(registry);

**//for (;;)
{
pkt_in.Set(4004);
}**

return 0;
}

curl 0.0.0.0:9091/metrics
curl: (7) Failed connect to 0.0.0.0:9091; Connection refused

In the above sample program, we expect when we set enable_keep_alive="yes". The port keep alive and we don't have to use the infinite for loop here.

Or our understanding is wrong.

**Comment by satyabratabharati** [comment]
> 

Hi Gregor,
Thank You for the quick response. 

Our ultimate goal was to keep the port alive . However still without the infinite for loop, the connection getting lost even after setting the keep-alive flag set to "yes". 

kindle have a look at the example program above.

Thank You.

**Comment by gjasny** [comment]
Hello,
I misunderstood what you meant with keeping the port open. What you experience is the normal life cycle of a C/C++ program. As soon as the control flow leaves the block all of its variables get destroyed. If the main function is left then the program exits.
To prevent that in the example, we use an infinite loop to keep the program infinitely running.

I hope this somehow clarifies what you’re experiencing.

**Comment by satyabratabharati** [comment]
Hi Gregor,

Many thanks for the support. and sorry for the confusion.

Thanks.
