### ISSUE TITLE
Null context when constructing CivetServer

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#560]
while creating the http server port using Exposer exposer() with following parameters, 
Exposer exposer({"127.0.0.1:8080","2","yes","90000")

{
  "listening_ports", "127.0.0.1:8080",
  "num_threads", "2",
  "enable_keep_alive", "yes",
  "keep_alive_timeout_ms", "90000",
}

we are getting following error:

**terminate called after throwing an instance of 'CivetException'
what(): null context when constructing CivetServer. Possible problem binding to port.
Aborted**

**Comment by gjasny** [comment]
This call look wrong:
> Exposer exposer({"127.0.0.1:8080","2","yes","90000")

It should be:
```c++
  Exposer exposer{
      {
          "listening_ports", "127.0.0.1:8081",
          "num_threads", "2",
          "enable_keep_alive", "yes",
          "keep_alive_timeout_ms", "90000",
      }
  };
```
