### ISSUE TITLE
sample_server metrics not showing up

### ISSUE THREAD

**Issue by havi0019** [jupp0r/prometheus-cpp#561]
Trying to get sample_server metrics to show up in localhost:9090

Using default prometheus.exe yaml file. I changed sample_server to connect to localhost 9090 which is prometheus default port. 

But I cannot see any of the metrics when running it. Was trying to get a sample to work before customizing it.

**Comment by gjasny** [comment]
Hmm. Maybe an IPv4 vs. IPv6 thing where `localhost` is resolved differently. Could you please try to use `127.0.0.1` instead of localhost everywhere? You could also try to point your browser to `http://127.0.0.1:9090/metrics`.

**Comment by gjasny** [comment]
Otherwise you could check with `lsof` to see if/where the sample_server actually listens on.

**Comment by gjasny** [comment]
Did you solve your problem?
