### ISSUE TITLE
Unable to expose prometheus port : for application running in background 

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#565]
Hi ,
I have a application which runs as demon on the background.

    // daemonize or stay foreground:
    if (!m_cfg.m_bForeground) {
        assert(!m_cfg.m_bDebug); // in debug mode we enable foreground mode!

        // disconnect from terminal
        printf("collector will now run in background, collecting data as requested.\n");
        pid_t childpid;
        if ((childpid = fork()) != 0) {
            exit(0); /* parent returns OK */
        }
      **m_Promethues.init();**
   
      
   void Promethues::init()
  {
     m_prometheus_exposer.RegisterCollectable(m_prometheus_registry);
  }

[root@centosbbtemplate ~]# curl 0.0.0.0:9090/metrics

//could not srcap anything on the port..!!

**However I can , when run my application on foreground..!**

**Comment by satyabratabharati** [comment]
Also can we really change the expose port after its initialized to a different port ?
Lets say I want to configure it from command line ..!! I have set it to default 9090 and later from command line I want to set it to 8080 in my application.

           std::string m_prometheus_port = "0.0.0.0:9090";
           prometheus::Exposer m_prometheus_exposer{m_prometheus_port};
           
           setExposePort.(0.0.0.0:8080) 
           
   Thank You.

**Comment by gjasny** [comment]
No, you cannot change the port of an exposer. But you can create as many exposers as you need. Just replace the old exposer with the new one.

About the background problem. Something in the civetweb web stack is not coping well with the fork/exit. I'd suggest to move your daemonizing code closer to the beginning of the program. Don't create any sockets or file descriptors prior to it.
