### ISSUE TITLE
 Unable to change Prometheus Exposer port at runtime

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#566]
At  run time can we really change the Exposer port after its initialized to a different port ?
Lets say I want to configure it from command line ..!! I have set it to default 9090 and later from command line I want to set it to 8080 in my application.

Here the Exposer object is a class member.

       std::string m_prometheus_port = "0.0.0.0:9090";
       prometheus::Exposer m_prometheus_exposer{m_prometheus_port};
       
       setExposePort(0.0.0.0:8080) 
Thank You.

**Comment by satyabratabharati** [comment]
Hi Gregor,
can you please elaborate a bit , what do you exactly mean by replacing the old exposer with new one ?
 Do you mean to create multiple Exposer object with different ports ? Does that mean you need to change your code every time we need to add a new Port ?

**Comment by satyabratabharati** [comment]
> No, you cannot change the port of an exposer. But you can create as many exposers as you need. Just replace the old exposer with the new one.

Hi @gjasny ,
By design we need the port to be exposed from command line as input and set it in Exposer.
is there way we achieve this.  As you say once we define Exposer with a port , we can not change it.

even if we create a new Exposer with another port, how can we pass it to a class member  ,  meaning how to replace the old exposer which is define in another class.

**Comment by satyabratabharati** [comment]
Hi Gregor,
I was looking for something like :
std::unique_ptr<prometheus::Exposer> m_exposer;

and later I can set it the port from command line as :

    void setExposePort(const std::string& str)
      {
        m_exposer = prometheus::detail::make_unique<prometheus::Exposer>(str);
      }

sorry to bother you.!!

Thanks for your support as always.

**Comment by gjasny** [comment]
You mean like this?

```diff
diff --git a/pull/tests/integration/sample_server.cc b/pull/tests/integration/sample_server.cc
index 742a365..5a7b1de 100644
--- a/pull/tests/integration/sample_server.cc
+++ b/pull/tests/integration/sample_server.cc
@@ -1,6 +1,7 @@
 #include <array>
 #include <chrono>
 #include <cstdlib>
+#include <iostream>
 #include <memory>
 #include <string>
 #include <thread>
@@ -11,11 +12,19 @@
 #include "prometheus/family.h"
 #include "prometheus/registry.h"
 
-int main() {
+int main(int argc, char *argv[]) {
   using namespace prometheus;
 
-  // create an http server running on port 8080
-  Exposer exposer{"127.0.0.1:8080"};
+  if (argc < 2) {
+    std::cerr << "Missing listening port" << std::endl;
+    return -1;
+  }
+
+  auto listenAddress = std::string{"127.0.0.1:"} + argv[1];
+  std::cout << "Listening on: " << listenAddress << std::endl;
+
+  // create an http server running on listenAddress
+  Exposer exposer{listenAddress};
 
   // create a metrics registry
   // @note it's the users responsibility to keep the object alive
```

**Comment by satyabratabharati** [comment]
Hi Gregor,
Exactly, perfect.!!!

Thank You.
