### ISSUE TITLE
Adding multiple labels to gauge  metric .

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#573]
Hi,

How can we add multiple labels to the Gauge  ?

        **more_labels = {{"label_1", "val_1"}};**

        auto& metrics = prometheus::BuildGauge()
                                          .Name(str)
                                          .Help(str)
                                          .Labels({{"XYZ", "001"}})
                                          .Register(*m_prometheus_registry)
                                          **.Add(more_labels);**

        **metrics.Add({{"lablel_2","val_2"}});**
        
        This seems to be does not work..!!

**Comment by gjasny** [comment]
Hello,

the `prometheus::BuildGauge::Labels` function accepts multiple labels at once. Like
```
.Labels({{"XYZ", "001"}, {"ASDF", "002"}})
```
Those are constant labels and are present for each time series within the metric. You add different time series by storing the Family returned by `prometheus::BuildGauge::Register()` and call `.Add` on it.

I'd suggest that you extensively study the [sample_server](https://github.com/jupp0r/prometheus-cpp/blob/master/pull/tests/integration/sample_server.cc) and [Family documentation](https://jupp0r.github.io/prometheus-cpp/classprometheus_1_1Family.html).

Thanks,
Gregor
