### ISSUE TITLE
Can multiple registries be found in Exposer? Whether they are the same is as follows

### ISSUE THREAD

**Issue by one-twos** [jupp0r/prometheus-cpp#576]
```c++
registry_ = std::make_shared<prometheus::Registry>();
exposer_ = std::make_shared<prometheus::Exposer>(prom_server);
exposer_->RegisterCollectable(registry_);
```

**Comment by dinglonghe** [comment]
while () {

  registry_ = std::make_sharedprometheus::Registry();
exposer_ = std::make_sharedprometheus::Exposer(prom_server);
exposer_->RegisterCollectable(registry_);
}

**Comment by gjasny** [comment]
Sorry, I don't understand your question.

You can register multiple registries to an exposer. They are added, not replaced:
https://github.com/jupp0r/prometheus-cpp/blob/01b42a9327e7dd39a8967f73e2305e893e040870/pull/src/handler.cc#L121-L126

Your loop won't work because you cannot create exposers that listens on the same ip/port combination (an exposer is a kind of HTTP-Server that is contacted by the prometheus server, not vice versa).

**Comment by gjasny** [comment]
Maybe reading about the general concept will clear-up things: https://prometheus.io/docs/introduction/overview/

**Comment by dinglonghe** [comment]
en，If the registry_ registry goes out of scope, will it be automatically deleted from exposer_? As follows:
{
 registry_ = std::make_sharedprometheus::Registry();
 exposer_->RegisterCollectable(registry_);
}

**Comment by dinglonghe** [comment]
registry_ = std::make_shared<prometheus::Registry>();
 exposer_ = std::make_shared<prometheus::Exposer>(para_.prom_server);
while() {
 exposer_->RegisterCollectable(registry_);
}
Will this result in more and more registries on Exposer_?

**Comment by dinglonghe** [comment]
exposer_ = std::make_sharedprometheus::Exposer(para_.prom_server);
while() {
registry_ = std::make_sharedprometheus::Registry();
exposer_->RegisterCollectable(registry_);
}
Will this result in more and more registries on Exposer_?

**Comment by gjasny** [comment]
No, they are cleaned up in line 124 (`CleanupStalePointers `)
https://github.com/jupp0r/prometheus-cpp/blob/01b42a9327e7dd39a8967f73e2305e893e040870/pull/src/handler.cc#L121-L126

**Comment by gjasny** [comment]
It will be lost because the Exposer implements pull semantics not push. Push semantics is implemented in the Gateway class from the pull module.
But except for short-lived services using a push model is discouraged.

**Comment by dinglonghe** [comment]
Ok, so is data loss inevitable, data that was not pulled the last time will be lost, how does the service fail?

**Comment by gjasny** [comment]
If you care about the data just retain the registry. Exposer and registry are supposed to be created once in the service lifetime and kept “forever”.

**Comment by dinglonghe** [comment]
OK

**Comment by dinglonghe** [comment]
Will there be a conflict if I have the same label stored in both registries?

**Comment by gjasny** [comment]
Of cause they would conflict. Why do you need two registries?

**Comment by one-twos** [comment]
This was because I had failed in the 2 exposer initializations
exposer_ = std::make_shared<prometheus::Exposer>(server);
exposer_ = std::make_shared<prometheus::Exposer>(server);

Can I manually close the Exposer connection?

**Comment by one-twos** [comment]
This was because I had failed in the 2 exposer initializations
exposer_ = std::make_shared<prometheus::Exposer>(server);
exposer_ = std::make_shared<prometheus::Exposer>(server);

Can I manually close the Exposer connection?

**Comment by one-twos** [comment]
I used close, but the connection still exists. Why?

**Comment by gjasny** [comment]
I don't know what you mean with that. Usually the prometheus server calls to our prometheus-cpp exposer. If all data has been transferred the connection will close.

This issue does not seem to be a bug and I don't have the bandwidth to help any further.

**Comment by one-twos** [comment]
ok, I've got it
