### ISSUE TITLE
Error installing prometheus-cpp package from conan-center 

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#582]
Hi Team,

I wanted to know the best way to install the prometheus-cpp package in my application.  I am using conancenter for the same. But I am not able to , following errors occurs while trying to int.

kindly help.

--------------
**conan install --remote conancenter  prometheus-cpp/1.0.0@**

Installing (downloading, building) binaries...
ERROR: Missing binary: civetweb/1.14:f35cf3f7995ea3b53267c52a2d785183c56c0d75
ERROR: Missing binary: libcurl/7.79.1:207729a68364ce05e62f30b55fac494ca8a91c50
ERROR: Missing binary: openssl/1.1.1n:3a5f72c8cd50641b8efa6ed13e6914c6ced2747c
ERROR: Missing binary: prometheus-cpp/1.0.0:d89341c178f55dffb68e278934145d2725d4bcf5
ERROR: Missing binary: zlib/1.2.11:3a5f72c8cd50641b8efa6ed13e6914c6ced2747c

openssl/1.1.1n: WARN: Can't find a 'openssl/1.1.1n' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=4.8, os=Linux
- Options: 386=False, enable_weak_ssl_ciphers=False, fPIC=True, no_aria=False, no_asm=False, no_async=False, no_bf=False, no_blake2=False, no_camellia=False, no_cast=False, no_chacha=False, no_cms=False, no_comp=False, no_ct=False, no_deprecated=False, no_des=False, no_dgram=False, no_dh=False, no_dsa=False, no_dso=False, no_ec=False, no_ecdh=False, no_ecdsa=False, no_engine=False, no_filenames=False, no_gost=False, no_hmac=False, no_idea=False, no_md4=False, no_md5=False, no_mdc2=False, no_ocsp=False, no_pinshared=False, no_rc2=False, no_rfc3779=False, no_rmd160=False, no_rsa=False, no_seed=False, no_sha=False, no_sm2=False, no_sm3=False, no_sm4=False, no_sock=False, no_srp=False, no_srtp=False, no_sse2=False, no_ssl=False, no_ssl3=False, no_stdio=False, no_tests=False, no_threads=False, no_tls1=False, no_ts=False, no_whirlpool=False, openssldir=None, shared=False
- Dependencies:
- Requirements:
- Package ID: 3a5f72c8cd50641b8efa6ed13e6914c6ced2747c

ERROR: Missing prebuilt package for 'civetweb/1.14', 'libcurl/7.79.1', 'openssl/1.1.1n', 'prometheus-cpp/1.0.0', 'zlib/1.2.11'
Use 'conan search openssl/1.1.1n --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=missing'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

Again when trying with option --build=missing, following is the error.
---
**conan install --remote conancenter  prometheus-cpp/1.0.0@ --build=missing**
--

ERROR: Could not detect Ninja v1.8.2 or newer

A full log can be found at 
_/build/3a5f72c8cd50641b8efa6ed13e6914c6ced2747c/build_subfolder/meson-logs/meson-log.txt
pkgconf/1.7.4:
pkgconf/1.7.4: ERROR: Package '3a5f72c8cd50641b8efa6ed13e6914c6ced2747c' build failed

ERROR: pkgconf/1.7.4: Error in build() method, line 96
        meson = self._configure_meson()
while calling '_configure_meson', line 79

**Comment by gjasny** [comment]
This is not a bug with prometheus-cpp but with your Conan setup. Please follow up with the Conan support channels or find and follow a Conan tutorial. 

By reading the last error message stating the missing ninja binary, maybe installing ninja or ninja-build on your machine will already do the trick.
