### ISSUE TITLE
How to reuse Prometheus gauge metric Instance?

### ISSUE THREAD

**Issue by satyabratabharati** [jupp0r/prometheus-cpp#584]
Hi @gjasny 

I have a loop, inside which I  instantiate the BuidGauge() , and set the metric and its value.

while()
{
    auto& **metrics** = prometheus::BuildGauge()
                        .Name(metric_name)
                        .Help(metric_name)
                        .Labels({ { m_metadata_key, m_metadata_value } })
                        .Register(GetPrometheusRegistry())
                        .Add(labels);
    metrics.Set(value);
}

but I want to instantiate it once out side the loop and set the metric for that instance.  if  the metric is already set i want to reuse the BuildGuage instance.

To achieve this I want to store the metric and gauge in a map.  And if that gauge is available I dont have to recreate prometheus::BuildGauge() inside the loop. just I want to reuse it.

std::map<std::string /* metric name /, prometheus::Gauge /* the gauge */>

**How can I do it ?**  is there a better way to do it ?

    prometheus::Gauge* m_metric;
 
    if(search_metric != map.end())
    {
	  printf("found metric:%s",metric_name.c_str());
      //prometheus::Gauge* gauge= (search_metric->second);
      m_metric= (search_metric->second);
      m_metric->Set(value);
 
    }
    else
    {
       printf("Not found metric:%s",metric_name.c_str());
       auto& metrics = prometheus::BuildGauge()
                        .Name(metric_name)
                        .Help(metric_name)
                        .Labels({ { m_metadata_key, m_metadata_value } })
                        .Register(GetPrometheusRegistry());
                        //.Add(labels);
       //prometheus::Gauge* gauge = &(metrics.Add(labels));
       m_metric = &(metrics.Add(labels));
       m_metric->Set(value);
       map.insert(std::make_pair(metric_name,m_metric));

**A small example could help ..!!**

Thank You.

**Comment by satyabratabharati** [comment]
Found the way .  Closing it.

**Comment by VenkateswaranJ** [comment]
@satyabratabharati could you please the way you find it? It might be helpful for me
