### ISSUE TITLE
Null context when constructing exposer

### ISSUE THREAD

**Issue by NJU-Eden** [jupp0r/prometheus-cpp#603]
while creating the http server port using Exposer exposer() with following parameters
 
exposer = std::unique_ptr<::prometheus::Exposer>(new ::prometheus::Exposer("0.0.0.0:10000"));

we get the following error
 
[__GI_raise] :? [0x363d6]
    <== [__GI_abort] :? [0x37ac7]
     <== [__gnu_cxx::__verbose_terminate_handler()] /root/gcc-8.4.0/build/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/vterminate.cc:95 [0x8bc72]
      <== [__cxxabiv1::__terminate(void (*)())] /root/gcc-8.4.0/build/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47 [0x91df5]
       <== [std::terminate()] /root/gcc-8.4.0/build/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57 [0x91e30]
        <== [__cxa_throw] /root/gcc-8.4.0/build/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/eh_throw.cc:95 [0x92062]
         <== [CivetServer::CivetServer(std::vector<std::string, std::allocator<std::string> > const&, CivetCallbacks const*, void const*)] ??:? [0x2215462]
         
 Also, I use the way in [https://github.com/jupp0r/prometheus-cpp/issues/560](https://github.com/jupp0r/prometheus-cpp/issues/560) , it does not work 

when I change the way above by using

Exposer exposer{"127.0.0.1:8080"};

the error also appear

**Comment by NJU-Eden** [comment]
when I change the way above by using 
Exposer exposer{"127.0.0.1:8080"};
the error also appear

**Comment by jupp0r** [comment]
What's the exception being thrown?

**Comment by NJU-Eden** [comment]
Null context

**Comment by NJU-Eden** [comment]
> What's the exception being thrown?

Null context when constructing CivetServer

throw CivetException("null context when constructing CivetServer. "
"Possible problem binding to port.");

**Comment by gjasny** [comment]
Hi,
either your environment does not have a loopback network device at 127.0.0.1 or both ports are already bound.

Does that help?

-Gregor
