### ISSUE TITLE
CurlWrapper doesn't implement debug callback

### ISSUE THREAD

**Issue by anatoly-p** [jupp0r/prometheus-cpp#607]
CURLOPT_DEBUGFUNCTION not set. So there is no way to access/log debug info to trace network issues. It would be great to have some kind of callback in Gateway.

**Comment by gjasny** [comment]
Hello,

the latest 1.3.0 release exposes a `presetupCurl` where you can change the libcurl settings prior to each request:
https://github.com/jupp0r/prometheus-cpp/blob/e5fada43131d251e9c4786b04263ce98b6767ba5/push/include/prometheus/gateway.h#L34

Thanks,
Gregor
