### ISSUE TITLE
Add C++11 support with a make_unique workaround

### ISSUE THREAD

**Issue by juandemanjon** [jupp0r/prometheus-cpp#615]
I need to use prometheus-cpp in a build system that only supports C++11 and utilizing std::make_unique forces me to create a patch on top of this wonderful library.

It will be easier if the library itself recognizes that it is building in C++11 and uses it owns make_unique function like 
```cpp
/**
 *  std::make_unique replacement for C++11
 *
 *  @param args the arguments to make_unique (forwarded)
 *
 *  @return the unique pointer
 */
template <typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args) {
  return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}
}
```
source: https://gist.github.com/chinmaygarde/970fd5bbd124754b7d36

**Comment by gjasny** [comment]
Please use the 1.0.x releases for that. I'll try to backport any bugfixes to them.
