### ISSUE TITLE
Need to change BUILD.bazel file in target @net_zlib_zlib prometheus-cpp/pull/BUILD.bazel

### ISSUE THREAD

**Issue by JessicaBarai** [jupp0r/prometheus-cpp#616]
When building with Bazel we need to change from z to zlib in Bazel in target @net_zlib_zlib/BUILD.bazel. https://github.com/jupp0r/prometheus-cpp/tree/master/pull/BUILD.bazel

**Comment by gjasny** [comment]
See #225 (#507, #513, #581): we use the same names for zlib like grpc does. 

Maybe `repo_mapping` works for you: https://github.com/bazelbuild/bazel/issues/6845

**Comment by gjasny** [comment]
I guess it is time for another overview:
* grpc [@zlib](https://github.com/grpc/grpc/blob/038994009339ca729bb3a78f01493ee1a0091ac5/bazel/grpc_deps.bzl#L223)/[zlib](https://github.com/grpc/grpc/blob/038994009339ca729bb3a78f01493ee1a0091ac5/third_party/zlib.BUILD#L2)
* rules_boost [@net_zlib_zlib](https://github.com/nelhage/rules_boost/blob/2cd6e7b540403fe737a10f90bc53de86a16a6eed/boost/boost.bzl#L162)/[zlib](https://github.com/nelhage/rules_boost/blob/2cd6e7b540403fe737a10f90bc53de86a16a6eed/BUILD.zlib#L6)
* cartographer [@]()/[]()
