### ISSUE TITLE
Split web server into Interface

### ISSUE THREAD

**Issue by curtpm** [jupp0r/prometheus-cpp#62]
It would be nice to have an interface (abstract base class) for the webserver or some kind of templating interface to allow a different web server to be used. 

I am investigating using this with grpc and it would be nice to just reuse that server instead of running multiple different ones.

**Comment by jupp0r** [comment]
Basically this interface already exists. Registries implement `Collectable`. You could add your web server in the same way that https://github.com/jupp0r/prometheus-cpp/blob/master/include/prometheus/exposer.h does it. It's not a lot of boilerplate, I've done this at work.
