### ISSUE TITLE
SHA256 Hash changes for v1.0.1

### ISSUE THREAD

**Issue by rmccorm4** [jupp0r/prometheus-cpp#632]
Hi prometheus-cpp team,

We have a project that pulls the tagged [v1.0.1](https://github.com/jupp0r/prometheus-cpp/releases/tag/v1.0.1) release and verifies the hash before using it.

For the past few months, it has had the same hash `593e028d401d3298eada804d252bc38d8cab3ea1c9e88bcd72095281f85e6d16` below:
```
$ sha256sum prometheus-cpp-1.0.1.tar.gz 
593e028d401d3298eada804d252bc38d8cab3ea1c9e88bcd72095281f85e6d16  prometheus-cpp-1.0.1.tar.gz
```

As of today, the hash appears to have changed to `e5b50a26801dc9696337319bdbd0796e6a205717d4f726e5dd324458b9cfcde6`:
```
$ sha256sum prometheus-cpp-1.0.1\ \(1\).tar.gz 
e5b50a26801dc9696337319bdbd0796e6a205717d4f726e5dd324458b9cfcde6  prometheus-cpp-1.0.1 (1).tar.gz
```

ref: I have an old download locally from August, and a new download from today that appear the same from a `diff -r ...`:
```
$ ls -lrth prometheus-cpp-1*
... 56K Aug 11 12:19  prometheus-cpp-1.0.1.tar.gz
... 56K Jan 30 12:53 'prometheus-cpp-1.0.1 (1).tar.gz'

$ diff -r prom101_old/prometheus-cpp-1.0.1/ prom101_new/prometheus-cpp-1.0.1/
... # no diff
```

It's possible this may be an [issue with github](https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745), but I wanted to raise this here just in case there's some unexpected vulnerability.

**Comment by jupp0r** [comment]
Hey, thanks a ton for pointing this out. What's the output of

`diff -y <(xxd prometheus-cpp-1.0.1.tar.gz) <(xxd 'prometheus-cpp-1.0.1 (1).tar.gz")`

I'm wondering if github inserts some binary zero character or newline at the end that `diff -r` is ignoring.

**Comment by jupp0r** [comment]
Also, could you upload the file from August 2022?

**Comment by jupp0r** [comment]
Looks like github recently changed their default compression settings: https://github.com/git/git/commit/4f4be00d302bc52d0d9d5a3d4738bb525066c710, which what I think caused this to break. You can safely update your shasums to the new value.

**Comment by kthui** [comment]
Looks like GitHub will be reverting their change: https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954
