### ISSUE TITLE
civetweb checksum mismatch

### ISSUE THREAD

**Issue by 0xjohnwarila** [jupp0r/prometheus-cpp#633]
Hey folks, 

We are running v1.0.0 (also checked on v1.0.1 and v1.4.0) and are running into a checksum failure in one of the prometheus-cpp dependencies civetweb.

Expecting `90a533422944ab327a4fbb9969f0845d0dba05354f9cacce3a5005fa59f593b9` but getting `c73c82d878c1f421248cbf3a772e690946891f079a411203689bc4a4b6ccda47` from `https://github.com/civetweb/civetweb/archive/v1.15.tar.gz`. I also mannualy verified that the checksum was the new one found by bazel, and not the hardcoded value.

I dropped a link to the definition that has the civetweb dependency.

https://github.com/jupp0r/prometheus-cpp/blob/8f0612ce965821722ae13b1e2d3bf78a06762358/bazel/repositories.bzl#L5-L14

**Comment by jupp0r** [comment]
Looks like Github accidentally broke this: https://github.com/orgs/community/discussions/45830 and it will be reverted back to normal soon. I'll leave the issue open until it's confirmed to be resolved.
