### ISSUE TITLE
I got compile error

### ISSUE THREAD

**Issue by jeffreycsj** [jupp0r/prometheus-cpp#639]
the error is this :prometheus/lib/libprometheus-cpp-pull.a(handler.cc.o): In function `prometheus::detail::MetricsHandler::handleGet(CivetServer*, mg_connection*)':
handler.cc:(.text+0xb0e): undefined reference to `vtable for prometheus::TextSerializer'
handler.cc:(.text+0xb2f): undefined reference to `prometheus::Serializer::Serialize[abi:cxx11](std::vector<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> > const&) const'
It seems like the virtual destructor wrong，but i saw the class destructor is default.I'm confused.

**Comment by jeffreycsj** [comment]
solved.

**Comment by mengbieting** [comment]
Hi, jeffreycsj, I am also confused by this problem, could you tell me your solution? thanks

**Comment by mengbieting** [comment]
I switched the order of the links, linking libprometheus-cpp-pull and then libprometheus-cpp-core, so this error does not occur.

**Comment by gjasny** [comment]
The link order is described [here](https://github.com/jupp0r/prometheus-cpp/blob/master/README.md#plain-makefiles).

**Comment by jeffreycsj** [comment]
sry,I didn't saw that.Right,I use that way. (*^▽^*)&nbsp;



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 30, 2023 18:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jupp0r/prometheus-cpp] I got compile error (Issue #639)




 
I switched the order of the links, linking libprometheus-cpp-pull and then libprometheus-cpp-core, so this error does not occur.
