### ISSUE TITLE
Push does not work with blank grouping key values

### ISSUE THREAD

**Issue by BrandonY** [jupp0r/prometheus-cpp#652]
Pushgateway encodes grouping label keys and values as URL path segments. Those values may be blank, but URL path segments may not be blank. To get around this, pushgateway requires that empty values be encoded as the character '='.

See https://github.com/prometheus/pushgateway#url for details.

This project doesn't do this and leaves the value blank, so if you have a label with a name like "label1" and a blank value, you get a request path like this: `/metrics/job/label1//label2/bla`. That's not a valid request path, or worse, it is, but it's equivalent to `/metrics/job/label1/label2/bla`, which doesn't work.

**Comment by gjasny** [comment]
Thanks for reporting and the initial PR.
