### ISSUE TITLE
Old versions of g++/clang crash on name_checker regexes

### ISSUE THREAD

**Issue by jhferris** [jupp0r/prometheus-cpp#66]
This is not a bug in the project perse but since it does impact the usability I thought I'd file an issue. 

I am building with a relatively ancient g++ (4.8.4) and while it compiles fine when it runs and tries to compile the regex it throws an exception.

Specifying a different regex parser makes the problem go away, I'll submit a PR with that if you are okay accepting that change.

**Comment by jhferris** [comment]
Actually I think my g++ is so old that std::regex might not be fully implemented (it no longer terminates with another regex_type but it always says it doesnt match). Probably not worth fixing, but might be worth making a note of somewhere or something

**Comment by jupp0r** [comment]
I verified this is broken on GCC 4.7 as well. I think I'll disable the check for these compilers, thanks for the bug report!

**Comment by gaschler** [comment]
Is there a PR to fix this issue? I can confirm it for g++ 4.8.4 and clang++-3.8.
Would be glad to have it fixed.

**Comment by jupp0r** [comment]
It's not related to the compiler, but is triggered by a bug in old versions of `libstdc++`, which for some reason do have a skeleton version of `<regex>` that simply always throw.

**Comment by gaschler** [comment]
Thank you very much for fixing this!
