### ISSUE TITLE
Compilation error with std::is_trivially_copy_constructible

### ISSUE THREAD

**Issue by ArkadySh** [jupp0r/prometheus-cpp#660]
i have the following compiler:
[root@LT-ZgNp0406Ag73 _build]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
[root@LT-ZgNp0406Ag73 _build]# uname -r
4.4.0-19041-Microsoft 

i try compile the library but get the following errors:

In file included from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest.h:64,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:47,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googlemock/include/gmock/gmock-actions.h:145,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googlemock/include/gmock/gmock.h:59,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googlemock/src/gmock-all.cc:39:
/mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In static member function 'static constexpr bool testing::internal::MatcherBase<T>::IsInlined()':
/mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:12: error: 'is_trivially_copy_constructible' is not a member of 'std'
            std::is_trivially_copy_constructible<M>::value &&
            ^
In file included from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest.h:64,
                 from /mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/src/gtest-all.cc:38:
/mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In static member function 'static constexpr bool testing::internal::MatcherBase<T>::IsInlined()':
/mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:12: error: 'is_trivially_copy_constructible' is not a member of 'std'
            std::is_trivially_copy_constructible<M>::value &&
            ^
/mnt/c/prometheus-cpp-with-submodules/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:50: error: expected primary-expression before '>' token

Can you help ?

**Comment by gjasny** [comment]
Hello, your compiler is pretty old. Just disable the option to build and execute the tests.

**Comment by ArkadySh** [comment]
Thank you ,it is works !
