### ISSUE TITLE
how should I create a customized path ?

### ISSUE THREAD

**Issue by baiwfg2** [jupp0r/prometheus-cpp#67]
I know prometheus will automatically scrape /metrics path. But what if I want to create another path and show some data ? How should I do that in prometheus-cpp ?

For example , when I do `curl localhost:9090` or `curl localhost:9090/info`, it can also give me some data I specify.

Thanks.

**Comment by jupp0r** [comment]
There are two possibilies:

1. run a http server of your choice on a different port (recommended)
2. implement your own `Exposer` similar to https://github.com/jupp0r/prometheus-cpp/blob/master/lib/exposer.cc and use the built-in civetweb server

Please be aware that civetweb is a minimal embedded http server and will probably not support normal web workloads very well the way it's configured by prometheus-cpp.

**Comment by baiwfg2** [comment]
Thanks.
