### ISSUE TITLE
[Notice]: the CMake version need to be higher than 3.19 

### ISSUE THREAD

**Issue by TuringLiu** [jupp0r/prometheus-cpp#684]
I got some building errors by CMake method, and the error info is below：

```
-- Could NOT find benchmark (missing: benchmark_DIR)
CMake Error at util/CMakeLists.txt:1 (add_library):
  add_library INTERFACE library requires no source arguments.


CMake Error at util/CMakeLists.txt:5 (add_library):
  add_library cannot create ALIAS target "prometheus-cpp::util" because
  target "util" does not already exist.


CMake Error at util/CMakeLists.txt:7 (target_compile_features):
  Cannot specify compile features for target "util" which is not built by
  this project.


CMake Error at util/CMakeLists.txt:12 (target_include_directories):
  Cannot specify include directories for target "util" which is not built by
  this project.


CMake Error at util/CMakeLists.txt:17 (set_target_properties):
  set_target_properties Can not find target to add properties to: util


CMake Error at util/CMakeLists.txt:22 (install):
  install TARGETS given target "util" which does not exist.
```
After a lot of checking works done, I found this error caused by the cmake version. And you guys can find it in the[ official DOC](https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries:~:text=New%20in%20version%203.19%3A),

**Comment by TuringLiu** [comment]
The curl version will cause the same building problems, too. I haven't much time to care about it, so I deleted the relative test code, and build was finally successful.  

It was a bad experience to build this program. :(

**Comment by gjasny** [comment]
> The curl version will cause the same building problems, too.

Could you please elaborate? What build problems did you run into?
