### ISSUE TITLE
CheckMetricName 

### ISSUE THREAD

**Issue by QuanjieDeng** [jupp0r/prometheus-cpp#686]
I generated static libraries by compiling the source code I got libprometheus-cpp-pull.a and libprometheus-cpp-core.a  
At the time of launching the report 
The rest of the code has compiled fine, I tried to use the CheckMetricName function and included the #include <prometheus/check_names.h> header file
The way I use it is  
```
    // Name checking
    if (!prometheus::CheckMetricName(metric_family))
    {
        GFATAL("Metrics collection agent", "Wrong metrics collection name, not according to specification:{} Refer to documentation:https://prometheus.io/docs/concepts/data_model/", metric_family);
        return; }
    }
```

But at compile time error
` ld.lld: error: undefined symbol: prometheus::CheckMetricName(std::__cxx11::basic_string<char, std::char_traits<char>, std:. allocator<char> > const&)`

**Comment by QuanjieDeng** [comment]
BTW, I'm using version 1.1.0

**Comment by gjasny** [comment]
Please check with `nm` how the `CheckMetricName` symbol looks like in your lib. This is for example on macOS:
```
nm -C cmake-build-debug/lib/libprometheus-cpp-core.a | grep CheckMetricName

0000000000000000 T prometheus::CheckMetricName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
0000000000000178 t std::__1::__wrap_iter<char const*> std::__1::find_if_not[abi:v160006]<std::__1::__wrap_iter<char const*>, prometheus::CheckMetricName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::$_0>(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>, prometheus::CheckMetricName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::$_0)
0000000000000900 t prometheus::CheckMetricName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::$_0::operator()(char) const
                 U prometheus::CheckMetricName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
```

The line with `T` shows the definition of the function. It should be exactly the same as in the `ld` error message.

Another source of problems is the ordering of libs (and object files). The `libprometheus-cpp-core.a` lib should come last.
