### ISSUE TITLE
Native support for sidecar container process

### ISSUE THREAD

**Issue by jaystarshot** [jupp0r/prometheus-cpp#692]
Background: I am considering using this library for presto/velox. https://github.com/prestodb/presto/pull/21753 is my intial PR.

I am wondering if there is any work going on or any POCs to provide a complete sidecar which can attach to a main container running a cpp program. Because a sidecar can help isolate resources, also provide more metrics during container crashes etc.

eg: In the java world https://github.com/prometheus/jmx_exporter Jmx exporter can be attached to a sidecar jvm

**Comment by gjasny** [comment]
Hello,

the prometheus-cpp library cannot work in a sidecar. In your example JMX is used as an intermediate representation which is then converted into prometheus compatible metrics. This conversion could happen in a sidecar container.

For C++ there is no such "native" representation. This library is meant to define and populate the metrics. It is used directly within the source code of an C++ application where the developer decides what conditions to observe.

Thanks,
Gregor
