### ISSUE TITLE
Compilation issue on CentOS

### ISSUE THREAD

**Issue by captKBK** [jupp0r/prometheus-cpp#694]
I am facing issues in compilation (using cmake --build . --parallel 4), the setup has all the dependencies installed as well. I am using CMake 3.28 and GCC 11.2.0 on CentOS 7.9. The prometheus-cpp version I am trying to compile is v1.0.1 for -std=C++ 11.

Reference compilation logs:

[  1%] Building CXX object core/CMakeFiles/core.dir/src/check_names.cc.o
[  3%] Building CXX object core/CMakeFiles/core.dir/src/counter.cc.o
[  5%] Building CXX object core/CMakeFiles/core.dir/src/detail/builder.cc.o
[  7%] Building CXX object core/CMakeFiles/core.dir/src/detail/ckms_quantiles.cc.o
[  9%] Building CXX object core/CMakeFiles/core.dir/src/detail/time_window_quantiles.cc.o
[ 10%] Building CXX object core/CMakeFiles/core.dir/src/detail/utils.cc.o
[ 12%] Building CXX object core/CMakeFiles/core.dir/src/family.cc.o
[ 14%] Building CXX object core/CMakeFiles/core.dir/src/gauge.cc.o
[ 16%] Building CXX object core/CMakeFiles/core.dir/src/histogram.cc.o
[ 18%] Building CXX object core/CMakeFiles/core.dir/src/registry.cc.o
[ 20%] Building CXX object core/CMakeFiles/core.dir/src/serializer.cc.o
[ 21%] Building CXX object core/CMakeFiles/core.dir/src/summary.cc.o
[ 23%] Building CXX object core/CMakeFiles/core.dir/src/text_serializer.cc.o
[ 25%] Linking CXX shared library ../lib/libprometheus-cpp-core.so
[ 25%] Built target core
[ 27%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googletest/src/gtest-all.cc.o
In file included from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest.h:64,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-all.cc:38:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In static member function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined()’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:12: error: ‘is_trivially_copy_constructible’ is not a member of ‘std’
            std::is_trivially_copy_constructible<M>::value &&
            ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:50: error: expected primary-expression before ‘>’ token
            std::is_trivially_copy_constructible<M>::value &&
                                                  ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:51: error: ‘::value’ has not been declared
            std::is_trivially_copy_constructible<M>::value &&
                                                   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:516:55:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:516:55:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:538:48:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:538:48:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:540:48:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:540:48:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:521:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-matchers.cc:45:68:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:521:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-matchers.cc:45:68:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^

[ 23%] Building CXX object core/CMakeFiles/core.dir/src/text_serializer.cc.o
[ 25%] Linking CXX shared library ../lib/libprometheus-cpp-core.so
[ 25%] Built target core
[ 27%] Building CXX object CMakeFiles/gmock_main.dir/3rdparty/googletest/googletest/src/gtest-all.cc.o
In file included from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest.h:64,
                 from /root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-all.cc:38:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In static member function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined()’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:12: error: ‘is_trivially_copy_constructible’ is not a member of ‘std’
            std::is_trivially_copy_constructible<M>::value &&
            ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:50: error: expected primary-expression before ‘>’ token
            std::is_trivially_copy_constructible<M>::value &&
                                                  ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:414:51: error: ‘::value’ has not been declared
            std::is_trivially_copy_constructible<M>::value &&
                                                   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:516:55:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/prometheus_poc/prometheus-cpp/3rdparty/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
make[2]: *** [CMakeFiles/gmock_main.dir/3rdparty/googletest/googletest/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/gmock_main.dir/all] Error 2
make: *** [all] Error 2

**Comment by jupp0r** [comment]
Looks like gtest switched over to requiring C++14.

**Comment by captKBK** [comment]
I disabled testing and it got compiled successfully. Thanks for the response.
