### ISSUE TITLE
Use with boost::beast Webserver

### ISSUE THREAD

**Issue by dufferzafar** [jupp0r/prometheus-cpp#698]
I'm adding a bunch of metrics to an application that uses `boost::beast` based webserver. I'd like to have a `/metrics` endpoint, but WITHOUT using the current Exposer (and it's associated civet webserver).

Has anyone tried something similar? What changes would need to happen for this? 

If I had to replace `Prometheus::Exposer` with a function that returns a `String` in the prometheus metric format, would it look something like:

```
std::string prometheusMetricsView(std::weak_ptr<prometheus::Collectable> wcollectable)
{
    auto collectable = wcollectable.lock();
    if (!collectable) {
        return "";
    }

    std::ostringstream output;
    prometheus::TextSerializer serializer;
    auto&& metrics = collectable->Collect();
    serializer.Serialize(metrics, &output);
    return output.str();
}
```

I could then attach this function to a particular boost::beast view. 

Does this sound reasonable? Am I missing something obvious?

**Comment by jupp0r** [comment]
Sounds totally reasonable to me. We designed the interface to be easily reusable if you bring your own web server (or no web server because you want to write to a file to log metrics during performance tests, etc) for this exact same reason.

**Comment by dufferzafar** [comment]
For anyone in the same boat, I was able to do this in opentelemetry itself.

Please see this discussion: https://github.com/open-telemetry/opentelemetry-cpp/discussions/2554

And the issue https://github.com/open-telemetry/opentelemetry-cpp/issue/2565
