### ISSUE TITLE
Installing on ubuntu 22.04

### ISSUE THREAD

**Issue by nekiro** [jupp0r/prometheus-cpp#703]
What's the apt package name on ubuntu 22.04 to install this lib?

**Comment by rockdrilla** [comment]
Hello there!

Ubuntu 22.04 doesn't have packaged this library: [packages.ubuntu.com/prometheus-cpp-dev](https://packages.ubuntu.com/search?keywords=prometheus-cpp-dev).

You may build/backport by yourself or use newer Ubuntu release.

**Comment by nekiro** [comment]
Any chance there will be possibility to simply install the lib on ubuntu 22?

**Comment by rockdrilla** [comment]
TL;DR Simply - no way.

https://github.com/jupp0r/prometheus-cpp#via-cmake
https://github.com/jupp0r/prometheus-cpp#packaging

So here we are:

via podman/buildah:
```sh
buildah bud -t prometheus-cpp-builder -v ${PWD}:/work
podman image rm prometheus-cpp-builder
```

or via docker (I've not tested that way):

```sh
docker build -t prometheus-cpp-builder -v ${PWD}:/work
docker image rm prometheus-cpp-builder
```

Dockerfile itself:

```dockerfile
FROM docker.io/library/ubuntu:22.04
SHELL [ "/bin/sh", "-ec" ]

ARG LIB_VERSION=v1.2.4

## bind-mount this directory in order to store artifacts
RUN ls -ld /work

RUN apt update ; \
    apt upgrade -y ; \
    apt install -y \
      git \
      debhelper \
      cmake \
      civetweb \
      doxygen \
      graphviz \
      libcivetweb-dev \
      libcurl4-openssl-dev \
      ninja-build \
      zlib1g-dev \
    ; \
    find /var/lib/apt/lists/ /var/cache/apt/archives/ -xdev -type f -delete

RUN cd /tmp ; \
    git clone -b ${LIB_VERSION} https://github.com/jupp0r/prometheus-cpp.git prometheus.git ; \
    cd prometheus.git ; \
    mkdir -p _build ; \
    cmake -B_build \
      -DCPACK_GENERATOR=DEB \
      -DENABLE_TESTING=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DUSE_THIRDPARTY_LIBRARIES=OFF \
    ; \
    cmake --build _build --target package --parallel $(nproc) ; \
    cp -at /work _build/*.deb
```

**Comment by gjasny** [comment]
Hi,
I created a [PPA for prometheus-cpp](https://code.launchpad.net/~prometheus-cpp/+archive/ubuntu/prometheus-cpp-stable) It might take some time until it is publicly reachable.

Thanks,
Gregor

**Comment by nekiro** [comment]
> Hi, I created a [PPA for prometheus-cpp](https://code.launchpad.net/~prometheus-cpp/+archive/ubuntu/prometheus-cpp-stable) It might take some time until it is publicly reachable. Once installation works, please give it a try. I used the same packaging scripts like I used for Debian.
> 
> Thanks, Gregor

Thanks!
