### ISSUE TITLE
Publish to BCR ?

### ISSUE THREAD

**Issue by mmorel-35** [jupp0r/prometheus-cpp#704]
Prometheus-cpp doesn't seems to be available on https://github.com/bazelbuild/bazel-central-registry/tree/main/modules

Have you considered publishing Prometheus-cpp in the registry ?

That could be really helpful to use it without needing to use git_override.

Thank you !

**Comment by gjasny** [comment]
Hi,

yes, I considered it but there are two dependencies missing in BCR: civetweb and curl.

Right now I don’t have the bandwidth to add them myselves.

Thanks,
Gregor

**Comment by mmorel-35** [comment]
I don't think you need to have all the dependencies of a project in the BCR to add it.
I believe Prometheus-cpp could be added with it's actual MODULE.bazel

**Comment by gjasny** [comment]
Thanks for your work! Once the PR in BCR is merged, could you please add a small section to the readme?
