### ISSUE TITLE
can not create http server on AWS instance

### ISSUE THREAD

**Issue by jinmeiz** [jupp0r/prometheus-cpp#72]
Hi jupp0r, I built prometheus-cpp on an AWS instance (ubuntu). Tests passed, but when I tried to run /tests/integration/sample_server. I got the following error:

terminate called after throwing an instance of 'CivetException'
  what():  null context when constructing CivetServer. Possible problem binding to port.
Aborted (core dumped)

I changed the line:  auto&& exposer = Exposer{"127.0.0.1:8080"} to auto&& exposer = Exposer{"<pulic_dns>:8080"}, where pulic_dns is AWS Public DNS (has format like ecx-xx-xxx-x-xx.us-west-2.compute.amazonaws.com, x is number). I also changed the security to allow access to 8080 on the AWS instance, but did not help.

I would really appreciate your help.

**Comment by jupp0r** [comment]
Hi, in order to rule out that it is prometheus-cpp related, can you install the `netcat` package and run `netcat -l 8080` in order to open a simple server at that port?

**Comment by jupp0r** [comment]
You can also replace "127.0.0.1:8080" by just "8080" in order to listen on all network devices.

**Comment by jinmeiz** [comment]
just "8080" works. Thanks a lot.
