### ISSUE TITLE
Make new release 1.3.0 ?

### ISSUE THREAD

**Issue by marcalff** [jupp0r/prometheus-cpp#722]
Are there any plans for a new release ?

I am asking because we downstream (opentelemetry-cpp) depends on a fix which is not available in 1.2.4.

See related:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2642
* https://github.com/jupp0r/prometheus-cpp/pull/715

Thanks.

**Comment by gjasny** [comment]
Hello,

please try: https://github.com/jupp0r/prometheus-cpp/releases/tag/v1.3.0

Thanks,
Gregor
