### ISSUE TITLE
`promlint` in cpp

### ISSUE THREAD

**Issue by dio** [jupp0r/prometheus-cpp#89]
Hi, is it possible to build `promlint` as a lib in c++ on top of this project? Since it will be useful to have it in integration tests for custom servers built in c++. Thanks!

**Comment by jupp0r** [comment]
As I see it, you can already use `promlint` on the output produced by your prometheus-cpp server:

`curl -s http://localhost:8080/metrics | promtool check metrics`

Running the upstream linter would be the preferred way to integrate promlint into an integration test written in C++ for me. You can technically use go libraries from C++, but it would require changes in the go library and also not be worth the hassle in my book.

You could write a small C++ library that does an HTTP request to your server, executes `promtool check metrics` on the response and returns the resulting errors (should be one per output line). I'd gladly integrate that into the `prometheus-cpp` integration tests!
