### ISSUE TITLE
Canonical workspace name?

### ISSUE THREAD

**Issue by drigz** [jupp0r/prometheus-cpp#96]
The WORKSPACE file currently sets `name = "prometheus_cpp"`. This goes against Bazel's advice to use

> Bazel [...] advises that a `WORKSPACE` call itself the reverse of the "canonical" URL of that repository, like `com_example_foo_utils`.

([source](https://docs.google.com/document/d/1qPOUeoqDA3eWFFXS1shWX1FT3e4BQB8yuSMrfQL4QrA/edit#heading=h.1kkuneerfl14))

I would expect WORKSPACE to set `name = "com_github_jupp0r_prometheus_cpp"`.

Is this intentional or would you consider changing this?

**Comment by jupp0r** [comment]
It's an oversight and should definitely be changed.
